/* panel-shell.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-shell.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <stdio.h>


#define TYPE_PANEL_END_SESSION_DIALOG (panel_end_session_dialog_get_type ())
#define PANEL_END_SESSION_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_END_SESSION_DIALOG, PanelEndSessionDialog))
#define PANEL_END_SESSION_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_END_SESSION_DIALOG, PanelEndSessionDialogClass))
#define IS_PANEL_END_SESSION_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_END_SESSION_DIALOG))
#define IS_PANEL_END_SESSION_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_END_SESSION_DIALOG))
#define PANEL_END_SESSION_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_END_SESSION_DIALOG, PanelEndSessionDialogClass))

typedef struct _PanelEndSessionDialog PanelEndSessionDialog;
typedef struct _PanelEndSessionDialogClass PanelEndSessionDialogClass;
typedef struct _PanelEndSessionDialogPrivate PanelEndSessionDialogPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block10Data Block10Data;
typedef struct _PanelEndSessionDialogOpenData PanelEndSessionDialogOpenData;

#define TYPE_PANEL_SHELL (panel_shell_get_type ())
#define PANEL_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_SHELL, PanelShell))
#define PANEL_SHELL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_SHELL, PanelShellClass))
#define IS_PANEL_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_SHELL))
#define IS_PANEL_SHELL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_SHELL))
#define PANEL_SHELL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_SHELL, PanelShellClass))

typedef struct _PanelShell PanelShell;
typedef struct _PanelShellClass PanelShellClass;
typedef struct _PanelShellPrivate PanelShellPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _PanelEndSessionDialog {
	GObject parent_instance;
	PanelEndSessionDialogPrivate * priv;
};

struct _PanelEndSessionDialogClass {
	GObjectClass parent_class;
};

struct _PanelEndSessionDialogPrivate {
	GtkLabel* label;
	gint countdown;
	guint update_title_source;
	gchar* current_title;
	guint default_action;
	GtkDialog* dialog;
	gboolean action_called;
};

struct _Block10Data {
	int _ref_count_;
	PanelEndSessionDialog* self;
	GtkDialog* d;
	guint type;
};

struct _PanelEndSessionDialogOpenData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	PanelEndSessionDialog* self;
	guint type;
	guint timestamp;
	guint waiting_time;
	char** inhibitors;
	gint inhibitors_length1;
	gchar* title;
	gchar* _tmp0_;
	gchar* button_text;
	gchar* _tmp1_;
	guint _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	const gchar* _tmp13_;
	gchar* _tmp14_;
	const gchar* _tmp15_;
	gchar* _tmp16_;
	const gchar* _tmp17_;
	gchar* _tmp18_;
	guint _tmp19_;
	const gchar* _tmp20_;
	const gchar* _tmp21_;
};

struct _PanelShell {
	GObject parent_instance;
	PanelShellPrivate * priv;
};

struct _PanelShellClass {
	GObjectClass parent_class;
};


static gpointer panel_end_session_dialog_parent_class = NULL;
static gpointer panel_shell_parent_class = NULL;

GType panel_end_session_dialog_get_type (void) G_GNUC_CONST;
guint panel_end_session_dialog_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
#define PANEL_END_SESSION_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_END_SESSION_DIALOG, PanelEndSessionDialogPrivate))
enum  {
	PANEL_END_SESSION_DIALOG_DUMMY_PROPERTY
};
PanelEndSessionDialog* panel_end_session_dialog_new (void);
PanelEndSessionDialog* panel_end_session_dialog_construct (GType object_type);
static void panel_end_session_dialog_start_update_title (PanelEndSessionDialog* self, const gchar* title);
static gboolean panel_end_session_dialog_update_title (PanelEndSessionDialog* self);
static gboolean _panel_end_session_dialog_update_title_gsource_func (gpointer self);
static void panel_end_session_dialog_launch_action (PanelEndSessionDialog* self, guint type);
static void panel_end_session_dialog_show_dialog (PanelEndSessionDialog* self, guint type, const gchar* title, const gchar* button_text);
static Block10Data* block10_data_ref (Block10Data* _data10_);
static void block10_data_unref (void * _userdata_);
static void __lambda15_ (Block10Data* _data10_, gint id);
static void ___lambda15__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static gboolean __lambda16_ (Block10Data* _data10_, GdkEventKey* e);
static gboolean ___lambda16__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
static void panel_end_session_dialog_open_data_free (gpointer _data);
void panel_end_session_dialog_open (PanelEndSessionDialog* self, guint type, guint timestamp, guint waiting_time, char** inhibitors, int inhibitors_length1, GAsyncReadyCallback _callback_, gpointer _user_data_);
void panel_end_session_dialog_open_finish (PanelEndSessionDialog* self, GAsyncResult* _res_);
static gboolean panel_end_session_dialog_open_co (PanelEndSessionDialogOpenData* _data_);
void panel_end_session_dialog_close (PanelEndSessionDialog* self);
static void panel_end_session_dialog_finalize (GObject* obj);
static void _dbus_panel_end_session_dialog_open (PanelEndSessionDialog* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void _dbus_panel_end_session_dialog_open_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_);
static void _dbus_panel_end_session_dialog_close (PanelEndSessionDialog* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void panel_end_session_dialog_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* panel_end_session_dialog_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean panel_end_session_dialog_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_panel_end_session_dialog_canceled (GObject* _sender, gpointer* _data);
static void _dbus_panel_end_session_dialog_confirmed_logout (GObject* _sender, gpointer* _data);
static void _dbus_panel_end_session_dialog_confirmed_reboot (GObject* _sender, gpointer* _data);
static void _dbus_panel_end_session_dialog_confirmed_shutdown (GObject* _sender, gpointer* _data);
static void _dbus_panel_end_session_dialog_closed (GObject* _sender, gpointer* _data);
static void _panel_end_session_dialog_unregister_object (gpointer user_data);
GType panel_shell_get_type (void) G_GNUC_CONST;
enum  {
	PANEL_SHELL_DUMMY_PROPERTY
};
PanelShell* panel_shell_new (void);
PanelShell* panel_shell_construct (GType object_type);
static void __lambda14_ (PanelShell* self);
static void ___lambda14__gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void panel_shell_on_name_acquired (PanelShell* self, GDBusConnection* conn, const gchar* name);
static void _panel_shell_on_name_acquired_gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void __lambda17_ (PanelShell* self);
static void ___lambda17__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

static const GDBusArgInfo _panel_end_session_dialog_dbus_arg_info_open_type = {-1, "type", "u"};
static const GDBusArgInfo _panel_end_session_dialog_dbus_arg_info_open_timestamp = {-1, "timestamp", "u"};
static const GDBusArgInfo _panel_end_session_dialog_dbus_arg_info_open_waiting_time = {-1, "waiting_time", "u"};
static const GDBusArgInfo _panel_end_session_dialog_dbus_arg_info_open_inhibitors = {-1, "inhibitors", "ao"};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_open_in[] = {&_panel_end_session_dialog_dbus_arg_info_open_type, &_panel_end_session_dialog_dbus_arg_info_open_timestamp, &_panel_end_session_dialog_dbus_arg_info_open_waiting_time, &_panel_end_session_dialog_dbus_arg_info_open_inhibitors, NULL};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_open_out[] = {NULL};
static const GDBusMethodInfo _panel_end_session_dialog_dbus_method_info_open = {-1, "Open", (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_open_in), (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_open_out)};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_close_in[] = {NULL};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_close_out[] = {NULL};
static const GDBusMethodInfo _panel_end_session_dialog_dbus_method_info_close = {-1, "Close", (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_close_in), (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_close_out)};
static const GDBusMethodInfo * const _panel_end_session_dialog_dbus_method_info[] = {&_panel_end_session_dialog_dbus_method_info_open, &_panel_end_session_dialog_dbus_method_info_close, NULL};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_canceled[] = {NULL};
static const GDBusSignalInfo _panel_end_session_dialog_dbus_signal_info_canceled = {-1, "Canceled", (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_canceled)};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_confirmed_logout[] = {NULL};
static const GDBusSignalInfo _panel_end_session_dialog_dbus_signal_info_confirmed_logout = {-1, "ConfirmedLogout", (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_confirmed_logout)};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_confirmed_reboot[] = {NULL};
static const GDBusSignalInfo _panel_end_session_dialog_dbus_signal_info_confirmed_reboot = {-1, "ConfirmedReboot", (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_confirmed_reboot)};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_confirmed_shutdown[] = {NULL};
static const GDBusSignalInfo _panel_end_session_dialog_dbus_signal_info_confirmed_shutdown = {-1, "ConfirmedShutdown", (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_confirmed_shutdown)};
static const GDBusArgInfo * const _panel_end_session_dialog_dbus_arg_info_closed[] = {NULL};
static const GDBusSignalInfo _panel_end_session_dialog_dbus_signal_info_closed = {-1, "Closed", (GDBusArgInfo **) (&_panel_end_session_dialog_dbus_arg_info_closed)};
static const GDBusSignalInfo * const _panel_end_session_dialog_dbus_signal_info[] = {&_panel_end_session_dialog_dbus_signal_info_canceled, &_panel_end_session_dialog_dbus_signal_info_confirmed_logout, &_panel_end_session_dialog_dbus_signal_info_confirmed_reboot, &_panel_end_session_dialog_dbus_signal_info_confirmed_shutdown, &_panel_end_session_dialog_dbus_signal_info_closed, NULL};
static const GDBusPropertyInfo * const _panel_end_session_dialog_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _panel_end_session_dialog_dbus_interface_info = {-1, "org.gnome.SessionManager.EndSessionDialog", (GDBusMethodInfo **) (&_panel_end_session_dialog_dbus_method_info), (GDBusSignalInfo **) (&_panel_end_session_dialog_dbus_signal_info), (GDBusPropertyInfo **) (&_panel_end_session_dialog_dbus_property_info)};
static const GDBusInterfaceVTable _panel_end_session_dialog_dbus_interface_vtable = {panel_end_session_dialog_dbus_interface_method_call, panel_end_session_dialog_dbus_interface_get_property, panel_end_session_dialog_dbus_interface_set_property};

PanelEndSessionDialog* panel_end_session_dialog_construct (GType object_type) {
	PanelEndSessionDialog * self = NULL;
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	self = (PanelEndSessionDialog*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkLabel*) gtk_label_new (NULL);
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp0_;
	_tmp1_ = self->priv->label;
	gtk_label_set_justify (_tmp1_, GTK_JUSTIFY_CENTER);
	return self;
}


PanelEndSessionDialog* panel_end_session_dialog_new (void) {
	return panel_end_session_dialog_construct (TYPE_PANEL_END_SESSION_DIALOG);
}


static gboolean _panel_end_session_dialog_update_title_gsource_func (gpointer self) {
	gboolean result;
	result = panel_end_session_dialog_update_title ((PanelEndSessionDialog*) self);
	return result;
}


static void panel_end_session_dialog_start_update_title (PanelEndSessionDialog* self, const gchar* title) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	g_return_if_fail (self != NULL);
	g_return_if_fail (title != NULL);
	self->priv->countdown = 10;
	_tmp0_ = title;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->current_title);
	self->priv->current_title = _tmp1_;
	panel_end_session_dialog_update_title (self);
	_tmp2_ = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 1, _panel_end_session_dialog_update_title_gsource_func, g_object_ref (self), g_object_unref);
	self->priv->update_title_source = _tmp2_;
}


static gboolean panel_end_session_dialog_update_title (PanelEndSessionDialog* self) {
	gboolean result = FALSE;
	GtkLabel* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp11_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->label;
	_tmp1_ = self->priv->countdown;
	_tmp2_ = g_strdup_printf ("<span font-weight='heavy' font_size='xx-large'>%d</span>\n", _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = self->priv->current_title;
	_tmp5_ = g_strconcat (_tmp3_, _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	gtk_label_set_markup (_tmp0_, _tmp6_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp3_);
	_tmp7_ = self->priv->countdown;
	if (_tmp7_ <= 0) {
		guint _tmp8_ = 0U;
		GtkDialog* _tmp9_ = NULL;
		self->priv->countdown = 0;
		_tmp8_ = self->priv->default_action;
		panel_end_session_dialog_launch_action (self, _tmp8_);
		_tmp9_ = self->priv->dialog;
		if (_tmp9_ != NULL) {
			GtkDialog* _tmp10_ = NULL;
			_tmp10_ = self->priv->dialog;
			gtk_widget_destroy ((GtkWidget*) _tmp10_);
		}
		result = FALSE;
		return result;
	}
	_tmp11_ = self->priv->countdown;
	self->priv->countdown = _tmp11_ - 1;
	result = TRUE;
	return result;
}


static Block10Data* block10_data_ref (Block10Data* _data10_) {
	g_atomic_int_inc (&_data10_->_ref_count_);
	return _data10_;
}


static void block10_data_unref (void * _userdata_) {
	Block10Data* _data10_;
	_data10_ = (Block10Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data10_->_ref_count_)) {
		PanelEndSessionDialog* self;
		self = _data10_->self;
		_g_object_unref0 (_data10_->d);
		_g_object_unref0 (self);
		g_slice_free (Block10Data, _data10_);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda15_ (Block10Data* _data10_, gint id) {
	PanelEndSessionDialog* self;
	guint _tmp0_ = 0U;
	gboolean _tmp1_ = FALSE;
	gint _tmp2_ = 0;
	self = _data10_->self;
	_tmp0_ = self->priv->update_title_source;
	g_source_remove (_tmp0_);
	self->priv->update_title_source = (guint) (-1);
	_tmp2_ = id;
	if (_tmp2_ == (-4)) {
		_tmp1_ = TRUE;
	} else {
		gint _tmp3_ = 0;
		_tmp3_ = id;
		_tmp1_ = _tmp3_ == 2;
	}
	if (_tmp1_) {
		gint _tmp4_ = 0;
		g_signal_emit_by_name (self, "canceled");
		_tmp4_ = id;
		if (_tmp4_ == 2) {
			GtkDialog* _tmp5_ = NULL;
			_tmp5_ = _data10_->d;
			gtk_widget_destroy ((GtkWidget*) _tmp5_);
		}
	} else {
		guint _tmp6_ = 0U;
		GtkDialog* _tmp7_ = NULL;
		_tmp6_ = _data10_->type;
		panel_end_session_dialog_launch_action (self, _tmp6_);
		_tmp7_ = _data10_->d;
		gtk_widget_destroy ((GtkWidget*) _tmp7_);
	}
}


static void ___lambda15__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	__lambda15_ (self, response_id);
}


static gboolean __lambda16_ (Block10Data* _data10_, GdkEventKey* e) {
	PanelEndSessionDialog* self;
	gboolean result = FALSE;
	GdkEventKey _tmp0_ = {0};
	guint _tmp1_ = 0U;
	const gchar* _tmp2_ = NULL;
	self = _data10_->self;
	g_return_val_if_fail (e != NULL, FALSE);
	_tmp0_ = *e;
	_tmp1_ = _tmp0_.keyval;
	_tmp2_ = gdk_keyval_name (_tmp1_);
	if (g_strcmp0 (_tmp2_, "Escape") == 0) {
		GtkDialog* _tmp3_ = NULL;
		g_signal_emit_by_name (self, "canceled");
		_tmp3_ = _data10_->d;
		gtk_widget_destroy ((GtkWidget*) _tmp3_);
	}
	result = FALSE;
	return result;
}


static gboolean ___lambda16__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = __lambda16_ (self, event);
	return result;
}


static void panel_end_session_dialog_show_dialog (PanelEndSessionDialog* self, guint type, const gchar* title, const gchar* button_text) {
	Block10Data* _data10_;
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
	const gchar* _tmp2_ = NULL;
	GtkDialog* _tmp3_ = NULL;
	GtkDialog* _tmp4_ = NULL;
	GtkDialog* _tmp5_ = NULL;
	GtkDialog* _tmp6_ = NULL;
	guint _tmp7_ = 0U;
	gchar* cancel_title = NULL;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	GtkDialog* _tmp14_ = NULL;
	GtkWidget* _tmp15_ = NULL;
	GtkLabel* _tmp16_ = NULL;
	GtkLabel* _tmp17_ = NULL;
	GtkDialog* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	GtkDialog* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	GtkDialog* _tmp22_ = NULL;
	GtkDialog* _tmp23_ = NULL;
	GtkDialog* _tmp24_ = NULL;
	GtkDialog* _tmp25_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (title != NULL);
	g_return_if_fail (button_text != NULL);
	_data10_ = g_slice_new0 (Block10Data);
	_data10_->_ref_count_ = 1;
	_data10_->self = g_object_ref (self);
	_tmp0_ = type;
	_data10_->type = _tmp0_;
	_tmp1_ = _data10_->type;
	self->priv->default_action = _tmp1_;
	_tmp2_ = _ ("Confirmation");
	_tmp3_ = (GtkDialog*) gtk_dialog_new_with_buttons (_tmp2_, NULL, GTK_DIALOG_MODAL, NULL, NULL);
	g_object_ref_sink (_tmp3_);
	_data10_->d = _tmp3_;
	_tmp4_ = _data10_->d;
	_tmp5_ = _g_object_ref0 (_tmp4_);
	_g_object_unref0 (self->priv->dialog);
	self->priv->dialog = _tmp5_;
	_tmp6_ = _data10_->d;
	gtk_window_fullscreen ((GtkWindow*) _tmp6_);
	_tmp7_ = self->priv->update_title_source;
	if (_tmp7_ >= ((guint) 0)) {
		guint _tmp8_ = 0U;
		_tmp8_ = self->priv->update_title_source;
		g_source_remove (_tmp8_);
		self->priv->update_title_source = (guint) (-1);
	}
	_tmp9_ = _ ("\nYou can prevent it by pressing <b>Cancel</b> button");
	_tmp10_ = g_strdup (_tmp9_);
	cancel_title = _tmp10_;
	_tmp11_ = title;
	_tmp12_ = g_strconcat (_tmp11_, cancel_title, NULL);
	_tmp13_ = _tmp12_;
	panel_end_session_dialog_start_update_title (self, _tmp13_);
	_g_free0 (_tmp13_);
	_tmp14_ = _data10_->d;
	_tmp15_ = gtk_dialog_get_content_area (_tmp14_);
	_tmp16_ = self->priv->label;
	gtk_box_pack_start (G_TYPE_CHECK_INSTANCE_TYPE (_tmp15_, GTK_TYPE_BOX) ? ((GtkBox*) _tmp15_) : NULL, (GtkWidget*) _tmp16_, TRUE, TRUE, (guint) 0);
	_tmp17_ = self->priv->label;
	gtk_widget_show ((GtkWidget*) _tmp17_);
	_tmp18_ = _data10_->d;
	_tmp19_ = button_text;
	gtk_dialog_add_button (_tmp18_, _tmp19_, 1);
	_tmp20_ = _data10_->d;
	_tmp21_ = _ ("Cancel");
	gtk_dialog_add_button (_tmp20_, _tmp21_, 2);
	_tmp22_ = _data10_->d;
	gtk_dialog_set_default_response (_tmp22_, 2);
	_tmp23_ = _data10_->d;
	g_signal_connect_data (_tmp23_, "response", (GCallback) ___lambda15__gtk_dialog_response, block10_data_ref (_data10_), (GClosureNotify) block10_data_unref, 0);
	_tmp24_ = _data10_->d;
	g_signal_connect_data ((GtkWidget*) _tmp24_, "key-press-event", (GCallback) ___lambda16__gtk_widget_key_press_event, block10_data_ref (_data10_), (GClosureNotify) block10_data_unref, 0);
	_tmp25_ = _data10_->d;
	gtk_dialog_run (_tmp25_);
	_g_free0 (cancel_title);
	block10_data_unref (_data10_);
	_data10_ = NULL;
}


static void panel_end_session_dialog_launch_action (PanelEndSessionDialog* self, guint type) {
	gboolean _tmp0_ = FALSE;
	guint _tmp1_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->action_called;
	if (_tmp0_ == TRUE) {
		return;
	}
	self->priv->action_called = TRUE;
	_tmp1_ = type;
	switch (_tmp1_) {
		case 3:
		case 2:
		{
			g_signal_emit_by_name (self, "confirmed-reboot");
			break;
		}
		case 1:
		{
			g_signal_emit_by_name (self, "confirmed-shutdown");
			break;
		}
		default:
		case 0:
		{
			g_signal_emit_by_name (self, "confirmed-logout");
			break;
		}
	}
}


static void panel_end_session_dialog_open_data_free (gpointer _data) {
	PanelEndSessionDialogOpenData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (PanelEndSessionDialogOpenData, _data_);
}


void panel_end_session_dialog_open (PanelEndSessionDialog* self, guint type, guint timestamp, guint waiting_time, char** inhibitors, int inhibitors_length1, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	PanelEndSessionDialogOpenData* _data_;
	PanelEndSessionDialog* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	guint _tmp3_ = 0U;
	char** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	_data_ = g_slice_new0 (PanelEndSessionDialogOpenData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, panel_end_session_dialog_open);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, panel_end_session_dialog_open_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = type;
	_data_->type = _tmp1_;
	_tmp2_ = timestamp;
	_data_->timestamp = _tmp2_;
	_tmp3_ = waiting_time;
	_data_->waiting_time = _tmp3_;
	_tmp4_ = inhibitors;
	_tmp4__length1 = inhibitors_length1;
	_data_->inhibitors = _tmp4_;
	_data_->inhibitors_length1 = _tmp4__length1;
	panel_end_session_dialog_open_co (_data_);
}


void panel_end_session_dialog_open_finish (PanelEndSessionDialog* self, GAsyncResult* _res_) {
	PanelEndSessionDialogOpenData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean panel_end_session_dialog_open_co (PanelEndSessionDialogOpenData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = NULL;
	_data_->_tmp0_ = g_strdup ("");
	_data_->title = _data_->_tmp0_;
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = g_strdup ("");
	_data_->button_text = _data_->_tmp1_;
	_data_->_tmp2_ = 0U;
	_data_->_tmp2_ = _data_->type;
	switch (_data_->_tmp2_) {
		case 1:
		{
			_data_->_tmp3_ = NULL;
			_data_->_tmp3_ = _ ("Shutdown Now");
			_data_->_tmp4_ = NULL;
			_data_->_tmp4_ = g_strdup (_data_->_tmp3_);
			_g_free0 (_data_->button_text);
			_data_->button_text = _data_->_tmp4_;
			_data_->_tmp5_ = NULL;
			_data_->_tmp5_ = _ ("This computer will go to a shutdown.");
			_data_->_tmp6_ = NULL;
			_data_->_tmp6_ = g_strdup (_data_->_tmp5_);
			_g_free0 (_data_->title);
			_data_->title = _data_->_tmp6_;
			break;
		}
		case 2:
		{
			_data_->_tmp7_ = NULL;
			_data_->_tmp7_ = _ ("Restart Now");
			_data_->_tmp8_ = NULL;
			_data_->_tmp8_ = g_strdup (_data_->_tmp7_);
			_g_free0 (_data_->button_text);
			_data_->button_text = _data_->_tmp8_;
			_data_->_tmp9_ = NULL;
			_data_->_tmp9_ = _ ("This computer will be restarted.");
			_data_->_tmp10_ = NULL;
			_data_->_tmp10_ = g_strdup (_data_->_tmp9_);
			_g_free0 (_data_->title);
			_data_->title = _data_->_tmp10_;
			break;
		}
		case 3:
		{
			_data_->_tmp11_ = NULL;
			_data_->_tmp11_ = _ ("Restart Now");
			_data_->_tmp12_ = NULL;
			_data_->_tmp12_ = g_strdup (_data_->_tmp11_);
			_g_free0 (_data_->button_text);
			_data_->button_text = _data_->_tmp12_;
			_data_->_tmp13_ = NULL;
			_data_->_tmp13_ = _ ("This computer will be restarted.");
			_data_->_tmp14_ = NULL;
			_data_->_tmp14_ = g_strdup (_data_->_tmp13_);
			_g_free0 (_data_->title);
			_data_->title = _data_->_tmp14_;
			break;
		}
		default:
		case 0:
		{
			_data_->_tmp15_ = NULL;
			_data_->_tmp15_ = _ ("Logout Now");
			_data_->_tmp16_ = NULL;
			_data_->_tmp16_ = g_strdup (_data_->_tmp15_);
			_g_free0 (_data_->button_text);
			_data_->button_text = _data_->_tmp16_;
			_data_->_tmp17_ = NULL;
			_data_->_tmp17_ = _ ("Your account will be logged-out.");
			_data_->_tmp18_ = NULL;
			_data_->_tmp18_ = g_strdup (_data_->_tmp17_);
			_g_free0 (_data_->title);
			_data_->title = _data_->_tmp18_;
			break;
		}
	}
	_data_->_tmp19_ = 0U;
	_data_->_tmp19_ = _data_->type;
	_data_->_tmp20_ = NULL;
	_data_->_tmp20_ = _data_->title;
	_data_->_tmp21_ = NULL;
	_data_->_tmp21_ = _data_->button_text;
	panel_end_session_dialog_show_dialog (_data_->self, _data_->_tmp19_, _data_->_tmp20_, _data_->_tmp21_);
	_g_free0 (_data_->button_text);
	_g_free0 (_data_->title);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


void panel_end_session_dialog_close (PanelEndSessionDialog* self) {
	g_return_if_fail (self != NULL);
}


static void panel_end_session_dialog_class_init (PanelEndSessionDialogClass * klass) {
	panel_end_session_dialog_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PanelEndSessionDialogPrivate));
	G_OBJECT_CLASS (klass)->finalize = panel_end_session_dialog_finalize;
	g_signal_new ("canceled", TYPE_PANEL_END_SESSION_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("confirmed_logout", TYPE_PANEL_END_SESSION_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("confirmed_reboot", TYPE_PANEL_END_SESSION_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("confirmed_shutdown", TYPE_PANEL_END_SESSION_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("closed", TYPE_PANEL_END_SESSION_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void panel_end_session_dialog_instance_init (PanelEndSessionDialog * self) {
	self->priv = PANEL_END_SESSION_DIALOG_GET_PRIVATE (self);
	self->priv->label = NULL;
	self->priv->countdown = 10;
	self->priv->update_title_source = (guint) (-1);
	self->priv->default_action = (guint) 0;
	self->priv->dialog = NULL;
	self->priv->action_called = FALSE;
}


static void panel_end_session_dialog_finalize (GObject* obj) {
	PanelEndSessionDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_END_SESSION_DIALOG, PanelEndSessionDialog);
	_g_object_unref0 (self->priv->label);
	_g_free0 (self->priv->current_title);
	_g_object_unref0 (self->priv->dialog);
	G_OBJECT_CLASS (panel_end_session_dialog_parent_class)->finalize (obj);
}


GType panel_end_session_dialog_get_type (void) {
	static volatile gsize panel_end_session_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&panel_end_session_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelEndSessionDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_end_session_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelEndSessionDialog), 0, (GInstanceInitFunc) panel_end_session_dialog_instance_init, NULL };
		GType panel_end_session_dialog_type_id;
		panel_end_session_dialog_type_id = g_type_register_static (G_TYPE_OBJECT, "PanelEndSessionDialog", &g_define_type_info, 0);
		g_type_set_qdata (panel_end_session_dialog_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) panel_end_session_dialog_register_object);
		g_once_init_leave (&panel_end_session_dialog_type_id__volatile, panel_end_session_dialog_type_id);
	}
	return panel_end_session_dialog_type_id__volatile;
}


static void _dbus_panel_end_session_dialog_open (PanelEndSessionDialog* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GVariantIter _arguments_iter;
	guint type = 0U;
	GVariant* _tmp11_;
	guint timestamp = 0U;
	GVariant* _tmp12_;
	guint waiting_time = 0U;
	GVariant* _tmp13_;
	char** inhibitors = NULL;
	int inhibitors_length1 = 0;
	GVariant* _tmp14_;
	char** _tmp15_;
	int _tmp15__length;
	int _tmp15__size;
	int _tmp15__length1;
	GVariantIter _tmp16_;
	GVariant* _tmp17_;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_tmp11_ = g_variant_iter_next_value (&_arguments_iter);
	type = g_variant_get_uint32 (_tmp11_);
	g_variant_unref (_tmp11_);
	_tmp12_ = g_variant_iter_next_value (&_arguments_iter);
	timestamp = g_variant_get_uint32 (_tmp12_);
	g_variant_unref (_tmp12_);
	_tmp13_ = g_variant_iter_next_value (&_arguments_iter);
	waiting_time = g_variant_get_uint32 (_tmp13_);
	g_variant_unref (_tmp13_);
	_tmp14_ = g_variant_iter_next_value (&_arguments_iter);
	_tmp15_ = g_new (char*, 5);
	_tmp15__length = 0;
	_tmp15__size = 4;
	_tmp15__length1 = 0;
	g_variant_iter_init (&_tmp16_, _tmp14_);
	for (; (_tmp17_ = g_variant_iter_next_value (&_tmp16_)) != NULL; _tmp15__length1++) {
		if (_tmp15__size == _tmp15__length) {
			_tmp15__size = 2 * _tmp15__size;
			_tmp15_ = g_renew (char*, _tmp15_, _tmp15__size + 1);
		}
		_tmp15_[_tmp15__length++] = g_variant_dup_string (_tmp17_, NULL);
		g_variant_unref (_tmp17_);
	}
	inhibitors_length1 = _tmp15__length1;
	_tmp15_[_tmp15__length] = NULL;
	inhibitors = _tmp15_;
	g_variant_unref (_tmp14_);
	panel_end_session_dialog_open (self, type, timestamp, waiting_time, inhibitors, inhibitors_length1, (GAsyncReadyCallback) _dbus_panel_end_session_dialog_open_ready, invocation);
	inhibitors = (_vala_array_free (inhibitors, inhibitors_length1, (GDestroyNotify) g_free), NULL);
}


static void _dbus_panel_end_session_dialog_open_ready (GObject * source_object, GAsyncResult * _res_, gpointer _user_data_) {
	GDBusMethodInvocation * invocation;
	GError* error = NULL;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	invocation = _user_data_;
	panel_end_session_dialog_open_finish ((PanelEndSessionDialog*) source_object, _res_);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_panel_end_session_dialog_close (PanelEndSessionDialog* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	panel_end_session_dialog_close (self);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void panel_end_session_dialog_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "Open") == 0) {
		_dbus_panel_end_session_dialog_open (object, parameters, invocation);
	} else if (strcmp (method_name, "Close") == 0) {
		_dbus_panel_end_session_dialog_close (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* panel_end_session_dialog_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean panel_end_session_dialog_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


static void _dbus_panel_end_session_dialog_canceled (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.gnome.SessionManager.EndSessionDialog", "Canceled", _arguments, NULL);
}


static void _dbus_panel_end_session_dialog_confirmed_logout (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.gnome.SessionManager.EndSessionDialog", "ConfirmedLogout", _arguments, NULL);
}


static void _dbus_panel_end_session_dialog_confirmed_reboot (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.gnome.SessionManager.EndSessionDialog", "ConfirmedReboot", _arguments, NULL);
}


static void _dbus_panel_end_session_dialog_confirmed_shutdown (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.gnome.SessionManager.EndSessionDialog", "ConfirmedShutdown", _arguments, NULL);
}


static void _dbus_panel_end_session_dialog_closed (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.gnome.SessionManager.EndSessionDialog", "Closed", _arguments, NULL);
}


guint panel_end_session_dialog_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_panel_end_session_dialog_dbus_interface_info), &_panel_end_session_dialog_dbus_interface_vtable, data, _panel_end_session_dialog_unregister_object, error);
	if (!result) {
		return 0;
	}
	g_signal_connect (object, "canceled", (GCallback) _dbus_panel_end_session_dialog_canceled, data);
	g_signal_connect (object, "confirmed-logout", (GCallback) _dbus_panel_end_session_dialog_confirmed_logout, data);
	g_signal_connect (object, "confirmed-reboot", (GCallback) _dbus_panel_end_session_dialog_confirmed_reboot, data);
	g_signal_connect (object, "confirmed-shutdown", (GCallback) _dbus_panel_end_session_dialog_confirmed_shutdown, data);
	g_signal_connect (object, "closed", (GCallback) _dbus_panel_end_session_dialog_closed, data);
	return result;
}


static void _panel_end_session_dialog_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_signal_handlers_disconnect_by_func (data[0], _dbus_panel_end_session_dialog_canceled, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_panel_end_session_dialog_confirmed_logout, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_panel_end_session_dialog_confirmed_reboot, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_panel_end_session_dialog_confirmed_shutdown, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_panel_end_session_dialog_closed, data);
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


static void __lambda14_ (PanelShell* self) {
}


static void ___lambda14__gbus_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	__lambda14_ ((PanelShell*) self);
}


static void _panel_shell_on_name_acquired_gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	panel_shell_on_name_acquired ((PanelShell*) self, connection, name);
}


static void __lambda17_ (PanelShell* self) {
	FILE* _tmp0_ = NULL;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Unable to claim Shell from gnome-session");
}


static void ___lambda17__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	__lambda17_ ((PanelShell*) self);
}


PanelShell* panel_shell_construct (GType object_type) {
	PanelShell * self = NULL;
	self = (PanelShell*) g_object_new (object_type, NULL);
	g_bus_own_name_with_closures (G_BUS_TYPE_SESSION, "org.gnome.Shell", 0, (GClosure*) ((___lambda14__gbus_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ___lambda14__gbus_acquired_callback, g_object_ref (self), g_object_unref)), (GClosure*) ((_panel_shell_on_name_acquired_gbus_name_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) _panel_shell_on_name_acquired_gbus_name_acquired_callback, g_object_ref (self), g_object_unref)), (GClosure*) ((___lambda17__gbus_name_lost_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ___lambda17__gbus_name_lost_callback, g_object_ref (self), g_object_unref)));
	return self;
}


PanelShell* panel_shell_new (void) {
	return panel_shell_construct (TYPE_PANEL_SHELL);
}


static void panel_shell_on_name_acquired (PanelShell* self, GDBusConnection* conn, const gchar* name) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (conn != NULL);
	g_return_if_fail (name != NULL);
	{
		GDBusConnection* _tmp0_ = NULL;
		PanelEndSessionDialog* _tmp1_ = NULL;
		PanelEndSessionDialog* _tmp2_ = NULL;
		FILE* _tmp3_ = NULL;
		_tmp0_ = conn;
		_tmp1_ = panel_end_session_dialog_new ();
		_tmp2_ = _tmp1_;
		panel_end_session_dialog_register_object (_tmp2_, _tmp0_, "/org/gnome/SessionManager/EndSessionDialog", &_inner_error_);
		_g_object_unref0 (_tmp2_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_IO_ERROR) {
				goto __catch33_g_io_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_tmp3_ = stderr;
		fprintf (_tmp3_, "EndSessionDialog hooked\n");
	}
	goto __finally33;
	__catch33_g_io_error:
	{
		GError* e = NULL;
		FILE* _tmp4_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stderr;
		fprintf (_tmp4_, "Unable to hook EndSessionDialog\n");
		_g_error_free0 (e);
	}
	__finally33:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void panel_shell_class_init (PanelShellClass * klass) {
	panel_shell_parent_class = g_type_class_peek_parent (klass);
}


static void panel_shell_instance_init (PanelShell * self) {
}


GType panel_shell_get_type (void) {
	static volatile gsize panel_shell_type_id__volatile = 0;
	if (g_once_init_enter (&panel_shell_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelShellClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_shell_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelShell), 0, (GInstanceInitFunc) panel_shell_instance_init, NULL };
		GType panel_shell_type_id;
		panel_shell_type_id = g_type_register_static (G_TYPE_OBJECT, "PanelShell", &g_define_type_info, 0);
		g_once_init_leave (&panel_shell_type_id__volatile, panel_shell_type_id);
	}
	return panel_shell_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



