/* panel-abstract-window.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-abstract-window.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <stdio.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/Xregion.h>
#include <gdk/gdkx.h>


#define TYPE_PANEL_ABSTRACT_WINDOW (panel_abstract_window_get_type ())
#define PANEL_ABSTRACT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_ABSTRACT_WINDOW, PanelAbstractWindow))
#define PANEL_ABSTRACT_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_ABSTRACT_WINDOW, PanelAbstractWindowClass))
#define IS_PANEL_ABSTRACT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_ABSTRACT_WINDOW))
#define IS_PANEL_ABSTRACT_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_ABSTRACT_WINDOW))
#define PANEL_ABSTRACT_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_ABSTRACT_WINDOW, PanelAbstractWindowClass))

typedef struct _PanelAbstractWindow PanelAbstractWindow;
typedef struct _PanelAbstractWindowClass PanelAbstractWindowClass;
typedef struct _PanelAbstractWindowPrivate PanelAbstractWindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _PanelAbstractWindow {
	GtkWindow parent_instance;
	PanelAbstractWindowPrivate * priv;
};

struct _PanelAbstractWindowClass {
	GtkWindowClass parent_class;
};


static gpointer panel_abstract_window_parent_class = NULL;

GType panel_abstract_window_get_type (void) G_GNUC_CONST;
enum  {
	PANEL_ABSTRACT_WINDOW_DUMMY_PROPERTY
};
void panel_abstract_window_set_struts (PanelAbstractWindow* self);
void panel_screen_get_primary_monitor_geometry (GdkRectangle* result);
PanelAbstractWindow* panel_abstract_window_new (void);
PanelAbstractWindow* panel_abstract_window_construct (GType object_type);
static void __lambda18_ (PanelAbstractWindow* self);
static void ___lambda18__gdk_screen_monitors_changed (GdkScreen* _sender, gpointer self);
static void __lambda19_ (PanelAbstractWindow* self);
static void ___lambda19__gdk_screen_size_changed (GdkScreen* _sender, gpointer self);


void panel_abstract_window_set_struts (PanelAbstractWindow* self) {
	gulong* struts = NULL;
	gulong* _tmp0_ = NULL;
	gint struts_length1 = 0;
	gint _struts_size_ = 0;
	GdkRectangle r = {0};
	GdkRectangle _tmp1_ = {0};
	gint left = 0;
	gint right = 0;
	gint top = 0;
	gint bottom = 0;
	gint left_y0 = 0;
	gint left_y1 = 0;
	gint right_y0 = 0;
	gint right_y1 = 0;
	gint top_x0 = 0;
	gint top_x1 = 0;
	gint bottom_x0 = 0;
	gint bottom_x1 = 0;
	gint x = 0;
	gint y = 0;
	GdkWindow* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint width = 0;
	GdkWindow* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint height = 0;
	GdkWindow* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	GdkRectangle _tmp10_ = {0};
	gint _tmp11_ = 0;
	gint _tmp23_ = 0;
	GdkRectangle _tmp24_ = {0};
	gint _tmp25_ = 0;
	gulong* _tmp37_ = NULL;
	gint _tmp37__length1 = 0;
	gint _tmp38_ = 0;
	gulong _tmp39_ = 0UL;
	gulong* _tmp40_ = NULL;
	gint _tmp40__length1 = 0;
	gint _tmp41_ = 0;
	gulong _tmp42_ = 0UL;
	gulong* _tmp43_ = NULL;
	gint _tmp43__length1 = 0;
	gint _tmp44_ = 0;
	gulong _tmp45_ = 0UL;
	gulong* _tmp46_ = NULL;
	gint _tmp46__length1 = 0;
	gint _tmp47_ = 0;
	gulong _tmp48_ = 0UL;
	gulong* _tmp49_ = NULL;
	gint _tmp49__length1 = 0;
	gint _tmp50_ = 0;
	gulong _tmp51_ = 0UL;
	gulong* _tmp52_ = NULL;
	gint _tmp52__length1 = 0;
	gint _tmp53_ = 0;
	gulong _tmp54_ = 0UL;
	gulong* _tmp55_ = NULL;
	gint _tmp55__length1 = 0;
	gint _tmp56_ = 0;
	gulong _tmp57_ = 0UL;
	gulong* _tmp58_ = NULL;
	gint _tmp58__length1 = 0;
	gint _tmp59_ = 0;
	gulong _tmp60_ = 0UL;
	gulong* _tmp61_ = NULL;
	gint _tmp61__length1 = 0;
	gint _tmp62_ = 0;
	gulong _tmp63_ = 0UL;
	gulong* _tmp64_ = NULL;
	gint _tmp64__length1 = 0;
	gint _tmp65_ = 0;
	gulong _tmp66_ = 0UL;
	gulong* _tmp67_ = NULL;
	gint _tmp67__length1 = 0;
	gint _tmp68_ = 0;
	gulong _tmp69_ = 0UL;
	gulong* _tmp70_ = NULL;
	gint _tmp70__length1 = 0;
	gint _tmp71_ = 0;
	gulong _tmp72_ = 0UL;
	FILE* _tmp73_ = NULL;
	gint _tmp74_ = 0;
	gint _tmp75_ = 0;
	gint _tmp76_ = 0;
	gint _tmp77_ = 0;
	gint _tmp78_ = 0;
	GdkRectangle _tmp79_ = {0};
	gint _tmp80_ = 0;
	Display* display = NULL;
	Display* _tmp81_ = NULL;
	Window xid = 0;
	GdkWindow* _tmp82_ = NULL;
	Window _tmp83_ = 0;
	Atom _tmp84_ = {0};
	gulong* _tmp85_ = NULL;
	gint _tmp85__length1 = 0;
	Atom _tmp86_ = {0};
	gulong* _tmp87_ = NULL;
	gint _tmp87__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_new0 (gulong, 12);
	struts = _tmp0_;
	struts_length1 = 12;
	_struts_size_ = struts_length1;
	panel_screen_get_primary_monitor_geometry (&_tmp1_);
	r = _tmp1_;
	left = 0;
	right = 0;
	top = 0;
	bottom = 0;
	left_y0 = 0;
	left_y1 = 0;
	right_y0 = 0;
	right_y1 = 0;
	top_x0 = 0;
	top_x1 = 0;
	bottom_x0 = 0;
	bottom_x1 = 0;
	x = 0;
	y = 0;
	_tmp2_ = gtk_widget_get_window ((GtkWidget*) self);
	gdk_window_get_position (_tmp2_, &_tmp3_, &_tmp4_);
	x = _tmp3_;
	y = _tmp4_;
	_tmp5_ = gtk_widget_get_window ((GtkWidget*) self);
	_tmp6_ = gdk_window_get_width (_tmp5_);
	width = _tmp6_;
	_tmp7_ = gtk_widget_get_window ((GtkWidget*) self);
	_tmp8_ = gdk_window_get_height (_tmp7_);
	height = _tmp8_;
	_tmp9_ = width;
	_tmp10_ = r;
	_tmp11_ = _tmp10_.width;
	if (_tmp9_ != _tmp11_) {
		gint _tmp12_ = 0;
		GdkRectangle _tmp13_ = {0};
		gint _tmp14_ = 0;
		_tmp12_ = x;
		_tmp13_ = r;
		_tmp14_ = _tmp13_.width;
		if (_tmp12_ < (_tmp14_ / 2)) {
			gint _tmp15_ = 0;
			gint _tmp16_ = 0;
			gint _tmp17_ = 0;
			gint _tmp18_ = 0;
			_tmp15_ = width;
			left = _tmp15_;
			_tmp16_ = y;
			left_y0 = _tmp16_;
			_tmp17_ = y;
			_tmp18_ = height;
			left_y1 = _tmp17_ + _tmp18_;
		} else {
			gint _tmp19_ = 0;
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			gint _tmp22_ = 0;
			_tmp19_ = width;
			right = _tmp19_;
			_tmp20_ = y;
			right_y0 = _tmp20_;
			_tmp21_ = y;
			_tmp22_ = height;
			right_y1 = _tmp21_ + _tmp22_;
		}
	}
	_tmp23_ = height;
	_tmp24_ = r;
	_tmp25_ = _tmp24_.height;
	if (_tmp23_ != _tmp25_) {
		gint _tmp26_ = 0;
		GdkRectangle _tmp27_ = {0};
		gint _tmp28_ = 0;
		_tmp26_ = y;
		_tmp27_ = r;
		_tmp28_ = _tmp27_.height;
		if (_tmp26_ < (_tmp28_ / 2)) {
			gint _tmp29_ = 0;
			gint _tmp30_ = 0;
			gint _tmp31_ = 0;
			gint _tmp32_ = 0;
			_tmp29_ = height;
			top = _tmp29_;
			_tmp30_ = x;
			top_x0 = _tmp30_;
			_tmp31_ = x;
			_tmp32_ = width;
			top_x1 = _tmp31_ + _tmp32_;
		} else {
			gint _tmp33_ = 0;
			gint _tmp34_ = 0;
			gint _tmp35_ = 0;
			gint _tmp36_ = 0;
			_tmp33_ = height;
			bottom = _tmp33_;
			_tmp34_ = x;
			bottom_x0 = _tmp34_;
			_tmp35_ = x;
			_tmp36_ = width;
			bottom_x1 = _tmp35_ + _tmp36_;
		}
	}
	_tmp37_ = struts;
	_tmp37__length1 = struts_length1;
	_tmp38_ = left;
	_tmp37_[0] = (gulong) _tmp38_;
	_tmp39_ = _tmp37_[0];
	_tmp40_ = struts;
	_tmp40__length1 = struts_length1;
	_tmp41_ = right;
	_tmp40_[1] = (gulong) _tmp41_;
	_tmp42_ = _tmp40_[1];
	_tmp43_ = struts;
	_tmp43__length1 = struts_length1;
	_tmp44_ = top;
	_tmp43_[2] = (gulong) _tmp44_;
	_tmp45_ = _tmp43_[2];
	_tmp46_ = struts;
	_tmp46__length1 = struts_length1;
	_tmp47_ = bottom;
	_tmp46_[3] = (gulong) _tmp47_;
	_tmp48_ = _tmp46_[3];
	_tmp49_ = struts;
	_tmp49__length1 = struts_length1;
	_tmp50_ = left_y0;
	_tmp49_[4] = (gulong) _tmp50_;
	_tmp51_ = _tmp49_[4];
	_tmp52_ = struts;
	_tmp52__length1 = struts_length1;
	_tmp53_ = left_y1;
	_tmp52_[5] = (gulong) _tmp53_;
	_tmp54_ = _tmp52_[5];
	_tmp55_ = struts;
	_tmp55__length1 = struts_length1;
	_tmp56_ = right_y0;
	_tmp55_[6] = (gulong) _tmp56_;
	_tmp57_ = _tmp55_[6];
	_tmp58_ = struts;
	_tmp58__length1 = struts_length1;
	_tmp59_ = right_y1;
	_tmp58_[7] = (gulong) _tmp59_;
	_tmp60_ = _tmp58_[7];
	_tmp61_ = struts;
	_tmp61__length1 = struts_length1;
	_tmp62_ = top_x0;
	_tmp61_[8] = (gulong) _tmp62_;
	_tmp63_ = _tmp61_[8];
	_tmp64_ = struts;
	_tmp64__length1 = struts_length1;
	_tmp65_ = top_x1;
	_tmp64_[9] = (gulong) _tmp65_;
	_tmp66_ = _tmp64_[9];
	_tmp67_ = struts;
	_tmp67__length1 = struts_length1;
	_tmp68_ = bottom_x0;
	_tmp67_[10] = (gulong) _tmp68_;
	_tmp69_ = _tmp67_[10];
	_tmp70_ = struts;
	_tmp70__length1 = struts_length1;
	_tmp71_ = bottom_x1;
	_tmp70_[11] = (gulong) _tmp71_;
	_tmp72_ = _tmp70_[11];
	_tmp73_ = stdout;
	_tmp74_ = left;
	_tmp75_ = right;
	_tmp76_ = top;
	_tmp77_ = bottom;
	_tmp78_ = y;
	_tmp79_ = r;
	_tmp80_ = _tmp79_.height;
	fprintf (_tmp73_, "%d %d %d %d %d %d\n", _tmp74_, _tmp75_, _tmp76_, _tmp77_, _tmp78_, _tmp80_);
	_tmp81_ = gdk_x11_get_default_xdisplay ();
	display = _tmp81_;
	_tmp82_ = gtk_widget_get_window ((GtkWidget*) self);
	_tmp83_ = gdk_x11_window_get_xid (_tmp82_);
	xid = _tmp83_;
	_tmp84_ = XInternAtom (display, "_NET_WM_STRUT_PARTIAL", FALSE);
	_tmp85_ = struts;
	_tmp85__length1 = struts_length1;
	XChangeProperty (display, xid, _tmp84_, XA_CARDINAL, 32, (gint) PropModeReplace, (guchar*) _tmp85_, 12);
	_tmp86_ = XInternAtom (display, "_NET_WM_STRUT", FALSE);
	_tmp87_ = struts;
	_tmp87__length1 = struts_length1;
	XChangeProperty (display, xid, _tmp86_, XA_CARDINAL, 32, (gint) PropModeReplace, (guchar*) _tmp87_, 4);
	struts = (g_free (struts), NULL);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda18_ (PanelAbstractWindow* self) {
	g_signal_emit_by_name (self, "screen-size-changed");
}


static void ___lambda18__gdk_screen_monitors_changed (GdkScreen* _sender, gpointer self) {
	__lambda18_ ((PanelAbstractWindow*) self);
}


static void __lambda19_ (PanelAbstractWindow* self) {
	g_signal_emit_by_name (self, "screen-size-changed");
}


static void ___lambda19__gdk_screen_size_changed (GdkScreen* _sender, gpointer self) {
	__lambda19_ ((PanelAbstractWindow*) self);
}


PanelAbstractWindow* panel_abstract_window_construct (GType object_type) {
	PanelAbstractWindow * self = NULL;
	GdkScreen* screen = NULL;
	GdkScreen* _tmp0_ = NULL;
	GdkScreen* _tmp1_ = NULL;
	self = (PanelAbstractWindow*) g_object_new (object_type, NULL);
	gtk_widget_add_events ((GtkWidget*) self, (gint) (((GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK) | GDK_STRUCTURE_MASK) | GDK_POINTER_MOTION_MASK));
	gtk_window_set_skip_taskbar_hint ((GtkWindow*) self, TRUE);
	gtk_window_set_decorated ((GtkWindow*) self, FALSE);
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
	gtk_window_set_focus_on_map ((GtkWindow*) self, TRUE);
	gtk_window_set_accept_focus ((GtkWindow*) self, TRUE);
	gtk_window_stick ((GtkWindow*) self);
	_tmp0_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	screen = _tmp1_;
	g_signal_connect_object (screen, "monitors-changed", (GCallback) ___lambda18__gdk_screen_monitors_changed, self, 0);
	g_signal_connect_object (screen, "size-changed", (GCallback) ___lambda19__gdk_screen_size_changed, self, 0);
	_g_object_unref0 (screen);
	return self;
}


PanelAbstractWindow* panel_abstract_window_new (void) {
	return panel_abstract_window_construct (TYPE_PANEL_ABSTRACT_WINDOW);
}


static void panel_abstract_window_class_init (PanelAbstractWindowClass * klass) {
	panel_abstract_window_parent_class = g_type_class_peek_parent (klass);
	g_signal_new ("screen_size_changed", TYPE_PANEL_ABSTRACT_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void panel_abstract_window_instance_init (PanelAbstractWindow * self) {
}


GType panel_abstract_window_get_type (void) {
	static volatile gsize panel_abstract_window_type_id__volatile = 0;
	if (g_once_init_enter (&panel_abstract_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelAbstractWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_abstract_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelAbstractWindow), 0, (GInstanceInitFunc) panel_abstract_window_instance_init, NULL };
		GType panel_abstract_window_type_id;
		panel_abstract_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "PanelAbstractWindow", &g_define_type_info, 0);
		g_once_init_leave (&panel_abstract_window_type_id__volatile, panel_abstract_window_type_id);
	}
	return panel_abstract_window_type_id__volatile;
}



