/* panel-places.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-places.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <JavaScriptCore/JavaScript.h>
#include <gio/gio.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gobject/gvaluecollector.h>


#define TYPE_PANEL_PLACES (panel_places_get_type ())
#define PANEL_PLACES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_PLACES, PanelPlaces))
#define PANEL_PLACES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_PLACES, PanelPlacesClass))
#define IS_PANEL_PLACES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_PLACES))
#define IS_PANEL_PLACES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_PLACES))
#define PANEL_PLACES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_PLACES, PanelPlacesClass))

typedef struct _PanelPlaces PanelPlaces;
typedef struct _PanelPlacesClass PanelPlacesClass;
typedef struct _PanelPlacesPrivate PanelPlacesPrivate;
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _JSStringRelease0(var) ((var == NULL) ? NULL : (var = (JSStringRelease (var), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _JSClassRelease0(var) ((var == NULL) ? NULL : (var = (JSClassRelease (var), NULL)))
#define _panel_places_unref0(var) ((var == NULL) ? NULL : (var = (panel_places_unref (var), NULL)))
typedef struct _ParamSpecPanelPlaces ParamSpecPanelPlaces;

struct _PanelPlaces {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PanelPlacesPrivate * priv;
};

struct _PanelPlacesClass {
	GTypeClass parent_class;
	void (*finalize) (PanelPlaces *self);
};

struct _PanelPlacesPrivate {
	GString* json;
	void* jsObject;
	GVolumeMonitor* vol_monitor;
	GFile* bookmark_file;
	GFileMonitor* bookmark_monitor;
};

struct _ParamSpecPanelPlaces {
	GParamSpec parent_instance;
};


static gpointer panel_places_parent_class = NULL;
static void* panel_places_jsContext;
static void* panel_places_jsContext = NULL;

gpointer panel_places_ref (gpointer instance);
void panel_places_unref (gpointer instance);
GParamSpec* param_spec_panel_places (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_panel_places (GValue* value, gpointer v_object);
void value_take_panel_places (GValue* value, gpointer v_object);
gpointer value_get_panel_places (const GValue* value);
GType panel_places_get_type (void) G_GNUC_CONST;
#define PANEL_PLACES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_PLACES, PanelPlacesPrivate))
enum  {
	PANEL_PLACES_DUMMY_PROPERTY
};
void* panel_places_js_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception);
static void* _panel_places_js_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception);
PanelPlaces* panel_places_new (void);
PanelPlaces* panel_places_construct (GType object_type);
static void panel_places_init_contents (PanelPlaces* self);
static void __lambda66_ (PanelPlaces* self);
void panel_places_reset (PanelPlaces* self);
static void ___lambda66__g_volume_monitor_mount_added (GVolumeMonitor* _sender, GMount* mount, gpointer self);
static void __lambda67_ (PanelPlaces* self);
static void ___lambda67__g_volume_monitor_mount_changed (GVolumeMonitor* _sender, GMount* mount, gpointer self);
static void __lambda68_ (PanelPlaces* self);
static void ___lambda68__g_volume_monitor_mount_removed (GVolumeMonitor* _sender, GMount* mount, gpointer self);
static void __lambda69_ (PanelPlaces* self);
static void ___lambda69__g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self);
static void panel_places_setup_home (PanelPlaces* self);
static void panel_places_setup_special_dirs (PanelPlaces* self);
static void panel_places_setup_mounts (PanelPlaces* self);
static void panel_places_setup_network (PanelPlaces* self);
gchar* utils_get_icon_path (const gchar* name, gint size);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
void* panel_places_js_set_update_callback (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_places_js_set_update_callback_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void* panel_places_js_update (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_places_js_update_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
static gchar* panel_places_get_json (PanelPlaces* self);
void panel_places_setup_js_class (void* context);
static void panel_places_finalize (PanelPlaces* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

static const JSClassDefinition PANEL_PLACES_js_class = {0, kJSClassAttributeNone, "Places", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, _panel_places_js_constructor_js_core_object_call_as_constructor_callback, NULL, NULL};

static void* _panel_places_js_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_places_js_constructor (ctx, constructor, arguments, arguments_length1, exception);
	return result;
}


static void __lambda66_ (PanelPlaces* self) {
	panel_places_reset (self);
}


static void ___lambda66__g_volume_monitor_mount_added (GVolumeMonitor* _sender, GMount* mount, gpointer self) {
	__lambda66_ ((PanelPlaces*) self);
}


static void __lambda67_ (PanelPlaces* self) {
	panel_places_reset (self);
}


static void ___lambda67__g_volume_monitor_mount_changed (GVolumeMonitor* _sender, GMount* mount, gpointer self) {
	__lambda67_ ((PanelPlaces*) self);
}


static void __lambda68_ (PanelPlaces* self) {
	panel_places_reset (self);
}


static void ___lambda68__g_volume_monitor_mount_removed (GVolumeMonitor* _sender, GMount* mount, gpointer self) {
	__lambda68_ ((PanelPlaces*) self);
}


static void __lambda69_ (PanelPlaces* self) {
	panel_places_reset (self);
}


static void ___lambda69__g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self) {
	__lambda69_ ((PanelPlaces*) self);
}


PanelPlaces* panel_places_construct (GType object_type) {
	PanelPlaces* self = NULL;
	GString* _tmp0_ = NULL;
	GVolumeMonitor* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	GVolumeMonitor* _tmp13_ = NULL;
	GVolumeMonitor* _tmp14_ = NULL;
	GVolumeMonitor* _tmp15_ = NULL;
	GFileMonitor* _tmp16_ = NULL;
	GError * _inner_error_ = NULL;
	self = (PanelPlaces*) g_type_create_instance (object_type);
	_tmp0_ = g_string_new ("");
	_g_string_free0 (self->priv->json);
	self->priv->json = _tmp0_;
	_tmp1_ = g_volume_monitor_get ();
	_g_object_unref0 (self->priv->vol_monitor);
	self->priv->vol_monitor = _tmp1_;
	_tmp2_ = g_get_home_dir ();
	_tmp3_ = g_strconcat (_tmp2_, "/.gtk-bookmarks", NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_file_new_for_path (_tmp4_);
	_g_object_unref0 (self->priv->bookmark_file);
	self->priv->bookmark_file = _tmp5_;
	_g_free0 (_tmp4_);
	{
		GFileMonitor* _tmp6_ = NULL;
		GFile* _tmp7_ = NULL;
		GFileMonitor* _tmp8_ = NULL;
		GFileMonitor* _tmp9_ = NULL;
		_tmp7_ = self->priv->bookmark_file;
		_tmp8_ = g_file_monitor_file (_tmp7_, G_FILE_MONITOR_NONE, NULL, &_inner_error_);
		_tmp6_ = _tmp8_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch2_g_error;
		}
		_tmp9_ = _tmp6_;
		_tmp6_ = NULL;
		_g_object_unref0 (self->priv->bookmark_monitor);
		self->priv->bookmark_monitor = _tmp9_;
		_g_object_unref0 (_tmp6_);
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		FILE* _tmp10_ = NULL;
		GError* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp10_ = stdout;
		_tmp11_ = e;
		_tmp12_ = _tmp11_->message;
		fprintf (_tmp10_, "Can't monitor bookmark file: %s", _tmp12_);
		_g_error_free0 (e);
	}
	__finally2:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	panel_places_init_contents (self);
	_tmp13_ = self->priv->vol_monitor;
	g_signal_connect (_tmp13_, "mount-added", (GCallback) ___lambda66__g_volume_monitor_mount_added, self);
	_tmp14_ = self->priv->vol_monitor;
	g_signal_connect (_tmp14_, "mount-changed", (GCallback) ___lambda67__g_volume_monitor_mount_changed, self);
	_tmp15_ = self->priv->vol_monitor;
	g_signal_connect (_tmp15_, "mount-removed", (GCallback) ___lambda68__g_volume_monitor_mount_removed, self);
	_tmp16_ = self->priv->bookmark_monitor;
	g_signal_connect (_tmp16_, "changed", (GCallback) ___lambda69__g_file_monitor_changed, self);
	return self;
}


PanelPlaces* panel_places_new (void) {
	return panel_places_construct (TYPE_PANEL_PLACES);
}


void panel_places_reset (PanelPlaces* self) {
	GString* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	void* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->json;
	g_string_assign (_tmp0_, "");
	panel_places_init_contents (self);
	_tmp2_ = panel_places_jsContext;
	if (_tmp2_ != NULL) {
		void* _tmp3_ = NULL;
		_tmp3_ = self->priv->jsObject;
		_tmp1_ = _tmp3_ != NULL;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		void* s = NULL;
		void* _tmp4_ = NULL;
		void* v = NULL;
		void* _tmp5_ = NULL;
		void* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		void* _tmp9_ = NULL;
		_tmp4_ = JSStringCreateWithUTF8CString ("updateCallback");
		s = _tmp4_;
		_tmp5_ = self->priv->jsObject;
		_tmp6_ = panel_places_jsContext;
		_tmp7_ = s;
		_tmp8_ = JSObjectGetProperty (_tmp6_, _tmp5_, _tmp7_, NULL);
		v = _tmp8_;
		_tmp9_ = v;
		if (_tmp9_ != NULL) {
			void* _tmp10_ = NULL;
			void* _tmp11_ = NULL;
			void* _tmp12_ = NULL;
			void* _tmp13_ = NULL;
			void* _tmp14_ = NULL;
			void* _tmp15_ = NULL;
			void* _tmp16_ = NULL;
			_tmp10_ = v;
			_tmp11_ = panel_places_jsContext;
			_tmp12_ = JSValueToStringCopy (_tmp11_, _tmp10_, NULL);
			_JSStringRelease0 (s);
			s = _tmp12_;
			_tmp13_ = panel_places_jsContext;
			_tmp14_ = s;
			_tmp15_ = JSEvaluateScript (_tmp13_, _tmp14_, NULL, NULL, 0, NULL);
			_tmp16_ = _tmp15_;
			_0 (_tmp16_);
		}
		_0 (v);
		_JSStringRelease0 (s);
	}
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static void panel_places_init_contents (PanelPlaces* self) {
	GString* _tmp0_ = NULL;
	GString* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GString* _tmp3_ = NULL;
	gssize _tmp4_ = 0L;
	gchar _tmp5_ = '\0';
	GString* _tmp9_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->json;
	g_string_append (_tmp0_, "[");
	panel_places_setup_home (self);
	panel_places_setup_special_dirs (self);
	panel_places_setup_mounts (self);
	panel_places_setup_network (self);
	_tmp1_ = self->priv->json;
	_tmp2_ = _tmp1_->str;
	_tmp3_ = self->priv->json;
	_tmp4_ = _tmp3_->len;
	_tmp5_ = string_get (_tmp2_, (glong) (_tmp4_ - 1));
	if (_tmp5_ == ',') {
		GString* _tmp6_ = NULL;
		GString* _tmp7_ = NULL;
		gssize _tmp8_ = 0L;
		_tmp6_ = self->priv->json;
		_tmp7_ = self->priv->json;
		_tmp8_ = _tmp7_->len;
		g_string_erase (_tmp6_, _tmp8_ - 1, (gssize) 1);
	}
	_tmp9_ = self->priv->json;
	g_string_append (_tmp9_, "]");
}


static void panel_places_setup_home (PanelPlaces* self) {
	GFile* f = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	gchar* s = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	GString* _tmp9_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_get_home_dir ();
	_tmp1_ = g_file_new_for_path (_tmp0_);
	f = _tmp1_;
	_tmp2_ = utils_get_icon_path ("gtk-home", 24);
	_tmp3_ = _tmp2_;
	_tmp4_ = _ ("Home");
	_tmp5_ = g_file_get_uri (f);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strdup_printf ("{icon: '%s', name: '%s', uri: '%s'},", _tmp3_, _tmp4_, _tmp6_);
	_tmp8_ = _tmp7_;
	_g_free0 (_tmp6_);
	_g_free0 (_tmp3_);
	s = _tmp8_;
	_tmp9_ = self->priv->json;
	g_string_append (_tmp9_, s);
	_g_free0 (s);
	_g_object_unref0 (f);
}


static void panel_places_setup_special_dirs (PanelPlaces* self) {
	GString* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GFile* _tmp29_ = NULL;
	gboolean _tmp30_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->json;
	_tmp1_ = _ ("Bookmarks");
	_tmp2_ = g_strdup_printf ("{name: '%s', isHeader: true},", _tmp1_);
	_tmp3_ = _tmp2_;
	g_string_append (_tmp0_, _tmp3_);
	_g_free0 (_tmp3_);
	{
		gint i = 0;
		i = (gint) G_USER_DIRECTORY_DESKTOP;
		{
			gboolean _tmp4_ = FALSE;
			_tmp4_ = TRUE;
			while (TRUE) {
				gint _tmp6_ = 0;
				gchar* path = NULL;
				gint _tmp7_ = 0;
				const gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
				const gchar* _tmp10_ = NULL;
				gchar* icon = NULL;
				gchar* _tmp11_ = NULL;
				gint _tmp12_ = 0;
				GFile* f = NULL;
				const gchar* _tmp14_ = NULL;
				GFile* _tmp15_ = NULL;
				gchar* s = NULL;
				const gchar* _tmp16_ = NULL;
				gchar* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				const gchar* _tmp19_ = NULL;
				gchar* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				GFile* _tmp22_ = NULL;
				gchar* _tmp23_ = NULL;
				gchar* _tmp24_ = NULL;
				gchar* _tmp25_ = NULL;
				gchar* _tmp26_ = NULL;
				GString* _tmp27_ = NULL;
				const gchar* _tmp28_ = NULL;
				if (!_tmp4_) {
					gint _tmp5_ = 0;
					_tmp5_ = i;
					i = _tmp5_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp6_ = i;
				if (!(_tmp6_ < ((gint) G_USER_N_DIRECTORIES))) {
					break;
				}
				_tmp7_ = i;
				_tmp8_ = g_get_user_special_dir ((GUserDirectory) _tmp7_);
				_tmp9_ = g_strdup (_tmp8_);
				path = _tmp9_;
				_tmp10_ = path;
				if (_tmp10_ == NULL) {
					_g_free0 (path);
					continue;
				}
				_tmp11_ = g_strdup ("gtk-directory");
				icon = _tmp11_;
				_tmp12_ = i;
				if (_tmp12_ == ((gint) G_USER_DIRECTORY_DESKTOP)) {
					gchar* _tmp13_ = NULL;
					_tmp13_ = g_strdup ("desktop");
					_g_free0 (icon);
					icon = _tmp13_;
				}
				_tmp14_ = path;
				_tmp15_ = g_file_new_for_path (_tmp14_);
				f = _tmp15_;
				_tmp16_ = icon;
				_tmp17_ = utils_get_icon_path (_tmp16_, 24);
				_tmp18_ = _tmp17_;
				_tmp19_ = path;
				_tmp20_ = g_filename_display_basename (_tmp19_);
				_tmp21_ = _tmp20_;
				_tmp22_ = f;
				_tmp23_ = g_file_get_uri (_tmp22_);
				_tmp24_ = _tmp23_;
				_tmp25_ = g_strdup_printf ("{icon: '%s', name: '%s', uri: '%s'},", _tmp18_, _tmp21_, _tmp24_);
				_tmp26_ = _tmp25_;
				_g_free0 (_tmp24_);
				_g_free0 (_tmp21_);
				_g_free0 (_tmp18_);
				s = _tmp26_;
				_tmp27_ = self->priv->json;
				_tmp28_ = s;
				g_string_append (_tmp27_, _tmp28_);
				_g_free0 (s);
				_g_object_unref0 (f);
				_g_free0 (icon);
				_g_free0 (path);
			}
		}
	}
	_tmp29_ = self->priv->bookmark_file;
	_tmp30_ = g_file_query_exists (_tmp29_, NULL);
	if (_tmp30_) {
		{
			GFileInputStream* _tmp31_ = NULL;
			GFile* _tmp32_ = NULL;
			GFileInputStream* _tmp33_ = NULL;
			GDataInputStream* input = NULL;
			GDataInputStream* _tmp34_ = NULL;
			gchar* line = NULL;
			GDataInputStream* _tmp54_ = NULL;
			_tmp32_ = self->priv->bookmark_file;
			_tmp33_ = g_file_read (_tmp32_, NULL, &_inner_error_);
			_tmp31_ = _tmp33_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch3_g_error;
			}
			_tmp34_ = g_data_input_stream_new ((GInputStream*) _tmp31_);
			input = _tmp34_;
			while (TRUE) {
				gchar* _tmp35_ = NULL;
				GDataInputStream* _tmp36_ = NULL;
				gchar* _tmp37_ = NULL;
				gchar* _tmp38_ = NULL;
				const gchar* _tmp39_ = NULL;
				gchar** fields = NULL;
				const gchar* _tmp40_ = NULL;
				gchar** _tmp41_ = NULL;
				gchar** _tmp42_ = NULL;
				gint fields_length1 = 0;
				gint _fields_size_ = 0;
				gchar** _tmp43_ = NULL;
				gint _tmp43__length1 = 0;
				_tmp36_ = input;
				_tmp37_ = g_data_input_stream_read_line (_tmp36_, NULL, NULL, &_inner_error_);
				_tmp35_ = _tmp37_;
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_free0 (line);
					_g_object_unref0 (input);
					_g_object_unref0 (_tmp31_);
					goto __catch3_g_error;
				}
				_tmp38_ = _tmp35_;
				_tmp35_ = NULL;
				_g_free0 (line);
				line = _tmp38_;
				_tmp39_ = line;
				if (!(_tmp39_ != NULL)) {
					_g_free0 (_tmp35_);
					break;
				}
				_tmp40_ = line;
				_tmp42_ = _tmp41_ = g_strsplit (_tmp40_, " ", 0);
				fields = _tmp42_;
				fields_length1 = _vala_array_length (_tmp41_);
				_fields_size_ = fields_length1;
				_tmp43_ = fields;
				_tmp43__length1 = fields_length1;
				if (_tmp43__length1 == 2) {
					gchar* s = NULL;
					gchar* _tmp44_ = NULL;
					gchar* _tmp45_ = NULL;
					gchar** _tmp46_ = NULL;
					gint _tmp46__length1 = 0;
					const gchar* _tmp47_ = NULL;
					gchar** _tmp48_ = NULL;
					gint _tmp48__length1 = 0;
					const gchar* _tmp49_ = NULL;
					gchar* _tmp50_ = NULL;
					gchar* _tmp51_ = NULL;
					GString* _tmp52_ = NULL;
					const gchar* _tmp53_ = NULL;
					_tmp44_ = utils_get_icon_path ("gtk-directory", 24);
					_tmp45_ = _tmp44_;
					_tmp46_ = fields;
					_tmp46__length1 = fields_length1;
					_tmp47_ = _tmp46_[1];
					_tmp48_ = fields;
					_tmp48__length1 = fields_length1;
					_tmp49_ = _tmp48_[0];
					_tmp50_ = g_strdup_printf ("{icon: '%s', name: '%s', uri: '%s'},", _tmp45_, _tmp47_, _tmp49_);
					_tmp51_ = _tmp50_;
					_g_free0 (_tmp45_);
					s = _tmp51_;
					_tmp52_ = self->priv->json;
					_tmp53_ = s;
					g_string_append (_tmp52_, _tmp53_);
					_g_free0 (s);
				}
				fields = (_vala_array_free (fields, fields_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (_tmp35_);
			}
			_tmp54_ = input;
			g_input_stream_close ((GInputStream*) _tmp54_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_free0 (line);
				_g_object_unref0 (input);
				_g_object_unref0 (_tmp31_);
				goto __catch3_g_error;
			}
			_g_free0 (line);
			_g_object_unref0 (input);
			_g_object_unref0 (_tmp31_);
		}
		goto __finally3;
		__catch3_g_error:
		{
			GError* e = NULL;
			FILE* _tmp55_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp55_ = stdout;
			fprintf (_tmp55_, "Unable to read the bookmarks\n");
			_g_error_free0 (e);
		}
		__finally3:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


static void panel_places_setup_mounts (PanelPlaces* self) {
	gboolean first_entry = FALSE;
	GList* mounts = NULL;
	GVolumeMonitor* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	first_entry = FALSE;
	_tmp0_ = self->priv->vol_monitor;
	_tmp1_ = g_volume_monitor_get_mounts (_tmp0_);
	mounts = _tmp1_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gint _tmp4_ = 0;
				GList* _tmp5_ = NULL;
				guint _tmp6_ = 0U;
				GMount* mount = NULL;
				GList* _tmp7_ = NULL;
				gint _tmp8_ = 0;
				gconstpointer _tmp9_ = NULL;
				GMount* _tmp10_ = NULL;
				GMount* _tmp11_ = NULL;
				gboolean _tmp12_ = FALSE;
				gchar* s = NULL;
				gchar* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				GMount* _tmp19_ = NULL;
				gchar* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				GMount* _tmp22_ = NULL;
				GFile* _tmp23_ = NULL;
				GFile* _tmp24_ = NULL;
				gchar* _tmp25_ = NULL;
				gchar* _tmp26_ = NULL;
				gchar* _tmp27_ = NULL;
				gchar* _tmp28_ = NULL;
				GString* _tmp29_ = NULL;
				const gchar* _tmp30_ = NULL;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = mounts;
				_tmp6_ = g_list_length (_tmp5_);
				if (!(((guint) _tmp4_) < _tmp6_)) {
					break;
				}
				_tmp7_ = mounts;
				_tmp8_ = i;
				_tmp9_ = g_list_nth_data (_tmp7_, (guint) _tmp8_);
				_tmp10_ = _g_object_ref0 ((GMount*) _tmp9_);
				mount = _tmp10_;
				_tmp11_ = mount;
				if (_tmp11_ == NULL) {
					_g_object_unref0 (mount);
					continue;
				}
				_tmp12_ = first_entry;
				if (_tmp12_ == FALSE) {
					GString* _tmp13_ = NULL;
					const gchar* _tmp14_ = NULL;
					gchar* _tmp15_ = NULL;
					gchar* _tmp16_ = NULL;
					_tmp13_ = self->priv->json;
					_tmp14_ = _ ("Mounts");
					_tmp15_ = g_strdup_printf ("{name: '%s', isHeader: true},", _tmp14_);
					_tmp16_ = _tmp15_;
					g_string_append (_tmp13_, _tmp16_);
					_g_free0 (_tmp16_);
					first_entry = TRUE;
				}
				_tmp17_ = utils_get_icon_path ("drive-harddisk", 24);
				_tmp18_ = _tmp17_;
				_tmp19_ = mount;
				_tmp20_ = g_mount_get_name (_tmp19_);
				_tmp21_ = _tmp20_;
				_tmp22_ = mount;
				_tmp23_ = g_mount_get_root (_tmp22_);
				_tmp24_ = _tmp23_;
				_tmp25_ = g_file_get_uri (_tmp24_);
				_tmp26_ = _tmp25_;
				_tmp27_ = g_strdup_printf ("{icon: '%s', name: '%s', uri: '%s'},", _tmp18_, _tmp21_, _tmp26_);
				_tmp28_ = _tmp27_;
				_g_free0 (_tmp26_);
				_g_object_unref0 (_tmp24_);
				_g_free0 (_tmp21_);
				_g_free0 (_tmp18_);
				s = _tmp28_;
				_tmp29_ = self->priv->json;
				_tmp30_ = s;
				g_string_append (_tmp29_, _tmp30_);
				_g_free0 (s);
				_g_object_unref0 (mount);
			}
		}
	}
	__g_list_free__g_object_unref0_0 (mounts);
}


static void panel_places_setup_network (PanelPlaces* self) {
	GString* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* s = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	GString* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	GString* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->json;
	_tmp1_ = _ ("Networks");
	_tmp2_ = g_strdup_printf ("{name: '%s', isHeader: true},", _tmp1_);
	_tmp3_ = _tmp2_;
	g_string_append (_tmp0_, _tmp3_);
	_g_free0 (_tmp3_);
	_tmp4_ = utils_get_icon_path ("gtk-network", 24);
	_tmp5_ = _tmp4_;
	_tmp6_ = _ ("My network");
	_tmp7_ = g_strdup_printf ("{icon: '%s', name: '%s', uri: '%s'},", _tmp5_, _tmp6_, "network:///");
	_tmp8_ = _tmp7_;
	_g_free0 (_tmp5_);
	s = _tmp8_;
	_tmp9_ = self->priv->json;
	_tmp10_ = s;
	g_string_append (_tmp9_, _tmp10_);
	_tmp11_ = utils_get_icon_path ("gnome-fs-network", 24);
	_tmp12_ = _tmp11_;
	_tmp13_ = _ ("Connect to server...");
	_tmp14_ = g_strdup_printf ("{icon: '%s', name: '%s', command: '%s'},", _tmp12_, _tmp13_, "nautilus-connect-server");
	_g_free0 (s);
	s = _tmp14_;
	_g_free0 (_tmp12_);
	_tmp15_ = self->priv->json;
	_tmp16_ = s;
	g_string_append (_tmp15_, _tmp16_);
	_g_free0 (s);
}


static void* _panel_places_js_set_update_callback_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_places_js_set_update_callback (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _panel_places_js_update_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_places_js_update (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


void* panel_places_js_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void* c = NULL;
	void* _tmp0_ = NULL;
	void* o = NULL;
	void* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
	void* s = NULL;
	void* _tmp3_ = NULL;
	void* f = NULL;
	void* _tmp4_ = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	void* _tmp8_ = NULL;
	void* _tmp9_ = NULL;
	void* _tmp10_ = NULL;
	void* _tmp11_ = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	void* _tmp16_ = NULL;
	PanelPlaces* i = NULL;
	PanelPlaces* _tmp17_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (constructor != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = JSClassCreate (&PANEL_PLACES_js_class);
	c = _tmp0_;
	_tmp1_ = ctx;
	_tmp2_ = JSObjectMake (_tmp1_, c, NULL);
	o = _tmp2_;
	_tmp3_ = JSStringCreateWithUTF8CString ("updateCallback");
	s = _tmp3_;
	_tmp4_ = ctx;
	_tmp5_ = s;
	_tmp6_ = JSObjectMakeFunctionWithCallback (_tmp4_, _tmp5_, _panel_places_js_set_update_callback_js_core_object_call_as_function_callback);
	f = _tmp6_;
	_tmp7_ = ctx;
	_tmp8_ = s;
	_tmp9_ = f;
	JSObjectSetProperty (_tmp7_, o, _tmp8_, _tmp9_, 0, NULL);
	_tmp10_ = JSStringCreateWithUTF8CString ("update");
	_JSStringRelease0 (s);
	s = _tmp10_;
	_tmp11_ = ctx;
	_tmp12_ = s;
	_tmp13_ = JSObjectMakeFunctionWithCallback (_tmp11_, _tmp12_, _panel_places_js_update_js_core_object_call_as_function_callback);
	_0 (f);
	f = _tmp13_;
	_tmp14_ = ctx;
	_tmp15_ = s;
	_tmp16_ = f;
	JSObjectSetProperty (_tmp14_, o, _tmp15_, _tmp16_, 0, NULL);
	_tmp17_ = panel_places_new ();
	i = _tmp17_;
	JSObjectSetPrivate (o, i);
	i->priv->jsObject = o;
	result = o;
	_0 (f);
	_JSStringRelease0 (s);
	_JSClassRelease0 (c);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static gpointer _panel_places_ref0 (gpointer self) {
	return self ? panel_places_ref (self) : NULL;
}


void* panel_places_js_set_update_callback (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelPlaces* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelPlaces* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	PanelPlaces* _tmp4_ = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_places_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_PLACES) ? ((PanelPlaces*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp4_ = i;
	if (_tmp4_ != NULL) {
		void** _tmp5_ = NULL;
		gint _tmp5__length1 = 0;
		_tmp5_ = arguments;
		_tmp5__length1 = arguments_length1;
		_tmp3_ = _tmp5__length1 == 1;
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		void* s = NULL;
		void* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		void* _tmp9_ = NULL;
		void** _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		void* _tmp11_ = NULL;
		_tmp6_ = JSStringCreateWithUTF8CString ("updateCallback");
		s = _tmp6_;
		_tmp7_ = thisObject;
		_tmp8_ = ctx;
		_tmp9_ = s;
		_tmp10_ = arguments;
		_tmp10__length1 = arguments_length1;
		_tmp11_ = _tmp10_[0];
		JSObjectSetProperty (_tmp8_, _tmp7_, _tmp9_, _tmp11_, 0, NULL);
		_JSStringRelease0 (s);
	}
	_tmp12_ = ctx;
	_tmp13_ = JSValueMakeUndefined (_tmp12_);
	result = _tmp13_;
	_panel_places_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* panel_places_js_update (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelPlaces* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelPlaces* _tmp2_ = NULL;
	PanelPlaces* _tmp3_ = NULL;
	void* _tmp11_ = NULL;
	void* _tmp12_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_places_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_PLACES) ? ((PanelPlaces*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp3_ = i;
	if (_tmp3_ != NULL) {
		gchar* _result_ = NULL;
		PanelPlaces* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		void* s = NULL;
		const gchar* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		void* _tmp9_ = NULL;
		void* _tmp10_ = NULL;
		_tmp4_ = i;
		_tmp5_ = panel_places_get_json (_tmp4_);
		_result_ = _tmp5_;
		_tmp6_ = _result_;
		_tmp7_ = JSStringCreateWithUTF8CString (_tmp6_);
		s = _tmp7_;
		_tmp8_ = ctx;
		_tmp9_ = s;
		_tmp10_ = JSEvaluateScript (_tmp8_, _tmp9_, NULL, NULL, 0, NULL);
		result = _tmp10_;
		_JSStringRelease0 (s);
		_g_free0 (_result_);
		_panel_places_unref0 (i);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp11_ = ctx;
	_tmp12_ = JSValueMakeUndefined (_tmp11_);
	result = _tmp12_;
	_panel_places_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void panel_places_setup_js_class (void* context) {
	void* _tmp0_ = NULL;
	void* c = NULL;
	void* _tmp1_ = NULL;
	void* o = NULL;
	void* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* _tmp4_ = NULL;
	void* g = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* s = NULL;
	void* _tmp7_ = NULL;
	void* _tmp8_ = NULL;
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	panel_places_jsContext = _tmp0_;
	_tmp1_ = JSClassCreate (&PANEL_PLACES_js_class);
	c = _tmp1_;
	_tmp2_ = context;
	_tmp3_ = context;
	_tmp4_ = JSObjectMake (_tmp2_, c, _tmp3_);
	o = _tmp4_;
	_tmp5_ = context;
	_tmp6_ = JSContextGetGlobalObject (_tmp5_);
	g = _tmp6_;
	_tmp7_ = JSStringCreateWithUTF8CString ("Places");
	s = _tmp7_;
	_tmp8_ = context;
	JSObjectSetProperty (_tmp8_, g, s, o, kJSPropertyAttributeNone, NULL);
	_JSStringRelease0 (s);
	_0 (g);
	_0 (o);
	_JSClassRelease0 (c);
}


static gchar* panel_places_get_json (PanelPlaces* self) {
	gchar* result = NULL;
	GString* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->json;
	_tmp1_ = _tmp0_->str;
	_tmp2_ = g_strdup (_tmp1_);
	result = _tmp2_;
	return result;
}


static void value_panel_places_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_panel_places_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		panel_places_unref (value->data[0].v_pointer);
	}
}


static void value_panel_places_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = panel_places_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_panel_places_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_panel_places_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		PanelPlaces* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = panel_places_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_panel_places_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PanelPlaces** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = panel_places_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_panel_places (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecPanelPlaces* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_PANEL_PLACES), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_panel_places (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_PLACES), NULL);
	return value->data[0].v_pointer;
}


void value_set_panel_places (GValue* value, gpointer v_object) {
	PanelPlaces* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_PLACES));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PANEL_PLACES));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		panel_places_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		panel_places_unref (old);
	}
}


void value_take_panel_places (GValue* value, gpointer v_object) {
	PanelPlaces* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_PLACES));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PANEL_PLACES));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		panel_places_unref (old);
	}
}


static void panel_places_class_init (PanelPlacesClass * klass) {
	panel_places_parent_class = g_type_class_peek_parent (klass);
	((PanelPlacesClass *) klass)->finalize = panel_places_finalize;
	g_type_class_add_private (klass, sizeof (PanelPlacesPrivate));
	g_signal_new ("error", TYPE_PANEL_PLACES, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("launching", TYPE_PANEL_PLACES, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void panel_places_instance_init (PanelPlaces * self) {
	self->priv = PANEL_PLACES_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void panel_places_finalize (PanelPlaces* obj) {
	PanelPlaces * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_PLACES, PanelPlaces);
	g_signal_handlers_destroy (self);
	_g_string_free0 (self->priv->json);
	_g_object_unref0 (self->priv->vol_monitor);
	_g_object_unref0 (self->priv->bookmark_file);
	_g_object_unref0 (self->priv->bookmark_monitor);
}


GType panel_places_get_type (void) {
	static volatile gsize panel_places_type_id__volatile = 0;
	if (g_once_init_enter (&panel_places_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_panel_places_init, value_panel_places_free_value, value_panel_places_copy_value, value_panel_places_peek_pointer, "p", value_panel_places_collect_value, "p", value_panel_places_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PanelPlacesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_places_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelPlaces), 0, (GInstanceInitFunc) panel_places_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType panel_places_type_id;
		panel_places_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PanelPlaces", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&panel_places_type_id__volatile, panel_places_type_id);
	}
	return panel_places_type_id__volatile;
}


gpointer panel_places_ref (gpointer instance) {
	PanelPlaces* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void panel_places_unref (gpointer instance) {
	PanelPlaces* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PANEL_PLACES_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



