/* panel-scrollable-content.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-scrollable-content.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define TYPE_PANEL_SCROLLABLE_CONTENT (panel_scrollable_content_get_type ())
#define PANEL_SCROLLABLE_CONTENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_SCROLLABLE_CONTENT, PanelScrollableContent))
#define PANEL_SCROLLABLE_CONTENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_SCROLLABLE_CONTENT, PanelScrollableContentClass))
#define IS_PANEL_SCROLLABLE_CONTENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_SCROLLABLE_CONTENT))
#define IS_PANEL_SCROLLABLE_CONTENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_SCROLLABLE_CONTENT))
#define PANEL_SCROLLABLE_CONTENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_SCROLLABLE_CONTENT, PanelScrollableContentClass))

typedef struct _PanelScrollableContent PanelScrollableContent;
typedef struct _PanelScrollableContentClass PanelScrollableContentClass;
typedef struct _PanelScrollableContentPrivate PanelScrollableContentPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _PanelScrollableContent {
	GtkScrolledWindow parent_instance;
	PanelScrollableContentPrivate * priv;
};

struct _PanelScrollableContentClass {
	GtkScrolledWindowClass parent_class;
};

struct _PanelScrollableContentPrivate {
	GtkViewport* viewport;
	GtkWidget* widget;
};


static gpointer panel_scrollable_content_parent_class = NULL;

GType panel_scrollable_content_get_type (void) G_GNUC_CONST;
#define PANEL_SCROLLABLE_CONTENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_SCROLLABLE_CONTENT, PanelScrollableContentPrivate))
enum  {
	PANEL_SCROLLABLE_CONTENT_DUMMY_PROPERTY
};
PanelScrollableContent* panel_scrollable_content_new (void);
PanelScrollableContent* panel_scrollable_content_construct (GType object_type);
void panel_scrollable_content_set_widget (PanelScrollableContent* self, GtkWidget* w);
void panel_scrollable_content_set_scrollbar_policy (PanelScrollableContent* self, GtkPolicyType hpolicy, GtkPolicyType vpolicy);
static void panel_scrollable_content_finalize (GObject* obj);


PanelScrollableContent* panel_scrollable_content_construct (GType object_type) {
	PanelScrollableContent * self = NULL;
	self = (PanelScrollableContent*) g_object_new (object_type, NULL);
	return self;
}


PanelScrollableContent* panel_scrollable_content_new (void) {
	return panel_scrollable_content_construct (TYPE_PANEL_SCROLLABLE_CONTENT);
}


void panel_scrollable_content_set_widget (PanelScrollableContent* self, GtkWidget* w) {
	GtkWidget* _tmp0_ = NULL;
	GtkAdjustment* _tmp1_ = NULL;
	GtkAdjustment* _tmp2_ = NULL;
	GtkAdjustment* _tmp3_ = NULL;
	GtkAdjustment* _tmp4_ = NULL;
	GtkViewport* _tmp5_ = NULL;
	GtkViewport* _tmp6_ = NULL;
	GtkViewport* _tmp7_ = NULL;
	GtkWidget* _tmp8_ = NULL;
	GtkViewport* _tmp9_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (w != NULL);
	_tmp0_ = w;
	self->priv->widget = _tmp0_;
	_tmp1_ = gtk_scrolled_window_get_hadjustment ((GtkScrolledWindow*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = gtk_scrolled_window_get_vadjustment ((GtkScrolledWindow*) self);
	_tmp4_ = _tmp3_;
	_tmp5_ = (GtkViewport*) gtk_viewport_new (_tmp2_, _tmp4_);
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->priv->viewport);
	self->priv->viewport = _tmp5_;
	_tmp6_ = self->priv->viewport;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp6_);
	_tmp7_ = self->priv->viewport;
	_tmp8_ = w;
	gtk_container_add ((GtkContainer*) _tmp7_, _tmp8_);
	_tmp9_ = self->priv->viewport;
	gtk_widget_show ((GtkWidget*) _tmp9_);
	panel_scrollable_content_set_scrollbar_policy (self, GTK_POLICY_NEVER, GTK_POLICY_NEVER);
	gtk_widget_show_all ((GtkWidget*) self);
}


void panel_scrollable_content_set_scrollbar_policy (PanelScrollableContent* self, GtkPolicyType hpolicy, GtkPolicyType vpolicy) {
	GtkPolicyType _tmp0_ = 0;
	GtkPolicyType _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = hpolicy;
	_tmp1_ = vpolicy;
	gtk_scrolled_window_set_policy ((GtkScrolledWindow*) self, _tmp0_, _tmp1_);
}


static void panel_scrollable_content_class_init (PanelScrollableContentClass * klass) {
	panel_scrollable_content_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PanelScrollableContentPrivate));
	G_OBJECT_CLASS (klass)->finalize = panel_scrollable_content_finalize;
}


static void panel_scrollable_content_instance_init (PanelScrollableContent * self) {
	self->priv = PANEL_SCROLLABLE_CONTENT_GET_PRIVATE (self);
}


static void panel_scrollable_content_finalize (GObject* obj) {
	PanelScrollableContent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_SCROLLABLE_CONTENT, PanelScrollableContent);
	_g_object_unref0 (self->priv->viewport);
	G_OBJECT_CLASS (panel_scrollable_content_parent_class)->finalize (obj);
}


GType panel_scrollable_content_get_type (void) {
	static volatile gsize panel_scrollable_content_type_id__volatile = 0;
	if (g_once_init_enter (&panel_scrollable_content_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelScrollableContentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_scrollable_content_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelScrollableContent), 0, (GInstanceInitFunc) panel_scrollable_content_instance_init, NULL };
		GType panel_scrollable_content_type_id;
		panel_scrollable_content_type_id = g_type_register_static (GTK_TYPE_SCROLLED_WINDOW, "PanelScrollableContent", &g_define_type_info, 0);
		g_once_init_leave (&panel_scrollable_content_type_id__volatile, panel_scrollable_content_type_id);
	}
	return panel_scrollable_content_type_id__volatile;
}



