/* panel-desktop-data.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-desktop-data.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <JavaScriptCore/JavaScript.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gio/gdesktopappinfo.h>
#include <gobject/gvaluecollector.h>


#define TYPE_PANEL_DESKTOP_DATA (panel_desktop_data_get_type ())
#define PANEL_DESKTOP_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_DESKTOP_DATA, PanelDesktopData))
#define PANEL_DESKTOP_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_DESKTOP_DATA, PanelDesktopDataClass))
#define IS_PANEL_DESKTOP_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_DESKTOP_DATA))
#define IS_PANEL_DESKTOP_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_DESKTOP_DATA))
#define PANEL_DESKTOP_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_DESKTOP_DATA, PanelDesktopDataClass))

typedef struct _PanelDesktopData PanelDesktopData;
typedef struct _PanelDesktopDataClass PanelDesktopDataClass;
typedef struct _PanelDesktopDataPrivate PanelDesktopDataPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _JSStringRelease0(var) ((var == NULL) ? NULL : (var = (JSStringRelease (var), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_dir_close0(var) ((var == NULL) ? NULL : (var = (g_dir_close (var), NULL)))
#define _JSClassRelease0(var) ((var == NULL) ? NULL : (var = (JSClassRelease (var), NULL)))
#define _panel_desktop_data_unref0(var) ((var == NULL) ? NULL : (var = (panel_desktop_data_unref (var), NULL)))
typedef struct _ParamSpecPanelDesktopData ParamSpecPanelDesktopData;

struct _PanelDesktopData {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PanelDesktopDataPrivate * priv;
};

struct _PanelDesktopDataClass {
	GTypeClass parent_class;
	void (*finalize) (PanelDesktopData *self);
};

struct _PanelDesktopDataPrivate {
	GFileMonitor* desktop_monitor;
	GString* json;
	void* jsObject;
	guint scheduled;
	guint64 last_schedule;
	gchar* path;
};

struct _ParamSpecPanelDesktopData {
	GParamSpec parent_instance;
};


static gpointer panel_desktop_data_parent_class = NULL;
static void* panel_desktop_data_jsContext;
static void* panel_desktop_data_jsContext = NULL;

gpointer panel_desktop_data_ref (gpointer instance);
void panel_desktop_data_unref (gpointer instance);
GParamSpec* param_spec_panel_desktop_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_panel_desktop_data (GValue* value, gpointer v_object);
void value_take_panel_desktop_data (GValue* value, gpointer v_object);
gpointer value_get_panel_desktop_data (const GValue* value);
GType panel_desktop_data_get_type (void) G_GNUC_CONST;
#define PANEL_DESKTOP_DATA_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_DESKTOP_DATA, PanelDesktopDataPrivate))
enum  {
	PANEL_DESKTOP_DATA_DUMMY_PROPERTY
};
void* panel_desktop_data_js_remove_from_desktop (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_desktop_data_js_remove_from_desktop_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void* panel_desktop_data_js_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception);
static void* _panel_desktop_data_js_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception);
PanelDesktopData* panel_desktop_data_new (void);
PanelDesktopData* panel_desktop_data_construct (GType object_type);
static void panel_desktop_data_monitor (PanelDesktopData* self);
static void __lambda24_ (PanelDesktopData* self);
static void panel_desktop_data_schedule_for_kick_js (PanelDesktopData* self);
static void ___lambda24__panel_desktop_data_changed (PanelDesktopData* _sender, gpointer self);
static gboolean panel_desktop_data_kick_js (PanelDesktopData* self);
static gboolean _panel_desktop_data_kick_js_gsource_func (gpointer self);
static void ___lambda23_ (PanelDesktopData* self);
static void ____lambda23__g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self);
static void panel_desktop_data_update_tree (PanelDesktopData* self);
gchar* utils_get_icon_path (const gchar* name, gint size);
static void panel_desktop_data_populate (PanelDesktopData* self);
static void panel_desktop_data_remove_from_desktop (const gchar* filename);
void* panel_desktop_data_js_update (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_desktop_data_js_update_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void* panel_desktop_data_js_set_update_callback (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_desktop_data_js_set_update_callback_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void panel_desktop_data_setup_js_class (void* context);
static void panel_desktop_data_finalize (PanelDesktopData* obj);

static const JSStaticFunction PANEL_DESKTOP_DATA_js_funcs[2] = {{"removeFromDesktop", _panel_desktop_data_js_remove_from_desktop_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {NULL, NULL, 0}};
static const JSClassDefinition PANEL_DESKTOP_DATA_js_class = {0, kJSClassAttributeNone, "DesktopData", NULL, NULL, PANEL_DESKTOP_DATA_js_funcs, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, _panel_desktop_data_js_constructor_js_core_object_call_as_constructor_callback, NULL, NULL};

static void* _panel_desktop_data_js_remove_from_desktop_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_desktop_data_js_remove_from_desktop (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _panel_desktop_data_js_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_desktop_data_js_constructor (ctx, constructor, arguments, arguments_length1, exception);
	return result;
}


static void __lambda24_ (PanelDesktopData* self) {
	guint _tmp0_ = 0U;
	_tmp0_ = self->priv->scheduled;
	if (_tmp0_ > ((guint) 0)) {
		return;
	}
	panel_desktop_data_schedule_for_kick_js (self);
}


static void ___lambda24__panel_desktop_data_changed (PanelDesktopData* _sender, gpointer self) {
	__lambda24_ ((PanelDesktopData*) self);
}


PanelDesktopData* panel_desktop_data_construct (GType object_type) {
	PanelDesktopData* self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GString* _tmp2_ = NULL;
	self = (PanelDesktopData*) g_type_create_instance (object_type);
	_tmp0_ = g_get_user_special_dir (G_USER_DIRECTORY_DESKTOP);
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->path);
	self->priv->path = _tmp1_;
	_tmp2_ = g_string_new ("");
	_g_string_free0 (self->priv->json);
	self->priv->json = _tmp2_;
	panel_desktop_data_monitor (self);
	g_signal_connect (self, "changed", (GCallback) ___lambda24__panel_desktop_data_changed, self);
	return self;
}


PanelDesktopData* panel_desktop_data_new (void) {
	return panel_desktop_data_construct (TYPE_PANEL_DESKTOP_DATA);
}


static gboolean _panel_desktop_data_kick_js_gsource_func (gpointer self) {
	gboolean result;
	result = panel_desktop_data_kick_js ((PanelDesktopData*) self);
	return result;
}


static void panel_desktop_data_schedule_for_kick_js (PanelDesktopData* self) {
	GDateTime* d = NULL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	gint64 _tmp2_ = 0LL;
	guint64 _tmp3_ = 0ULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_date_time_new_now_local ();
	d = _tmp0_;
	_tmp1_ = d;
	_tmp2_ = g_date_time_to_unix (_tmp1_);
	_tmp3_ = self->priv->last_schedule;
	if ((_tmp2_ - _tmp3_) > ((guint64) 1)) {
		panel_desktop_data_kick_js (self);
	} else {
		guint _tmp4_ = 0U;
		_tmp4_ = self->priv->scheduled;
		if (_tmp4_ == ((guint) 0)) {
			guint _tmp5_ = 0U;
			_tmp5_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, _panel_desktop_data_kick_js_gsource_func, panel_desktop_data_ref (self), panel_desktop_data_unref);
			self->priv->scheduled = _tmp5_;
		}
	}
	_g_date_time_unref0 (d);
}


static gboolean panel_desktop_data_kick_js (PanelDesktopData* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	void* _tmp1_ = NULL;
	GDateTime* d = NULL;
	GDateTime* _tmp17_ = NULL;
	gint64 _tmp18_ = 0LL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp1_ = panel_desktop_data_jsContext;
	if (_tmp1_ != NULL) {
		void* _tmp2_ = NULL;
		_tmp2_ = self->priv->jsObject;
		_tmp0_ = _tmp2_ != NULL;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		void* s = NULL;
		void* _tmp3_ = NULL;
		void* v = NULL;
		void* _tmp4_ = NULL;
		void* _tmp5_ = NULL;
		void* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		_tmp3_ = JSStringCreateWithUTF8CString ("updateCallback");
		s = _tmp3_;
		_tmp4_ = self->priv->jsObject;
		_tmp5_ = panel_desktop_data_jsContext;
		_tmp6_ = s;
		_tmp7_ = JSObjectGetProperty (_tmp5_, _tmp4_, _tmp6_, NULL);
		v = _tmp7_;
		_tmp8_ = v;
		if (_tmp8_ != NULL) {
			void* _tmp9_ = NULL;
			void* _tmp10_ = NULL;
			void* _tmp11_ = NULL;
			gchar buffer[1024] = {0};
			void* _tmp12_ = NULL;
			void* _tmp13_ = NULL;
			void* _tmp14_ = NULL;
			void* _tmp15_ = NULL;
			void* _tmp16_ = NULL;
			_tmp9_ = v;
			_tmp10_ = panel_desktop_data_jsContext;
			_tmp11_ = JSValueToStringCopy (_tmp10_, _tmp9_, NULL);
			_JSStringRelease0 (s);
			s = _tmp11_;
			_tmp12_ = s;
			JSStringGetUTF8CString (_tmp12_, buffer, (gsize) 1024);
			_tmp13_ = panel_desktop_data_jsContext;
			_tmp14_ = s;
			_tmp15_ = JSEvaluateScript (_tmp13_, _tmp14_, NULL, NULL, 0, NULL);
			_tmp16_ = _tmp15_;
			_0 (_tmp16_);
			_JSStringRelease0 (s);
			s = NULL;
		}
		_0 (v);
		_JSStringRelease0 (s);
	}
	_tmp17_ = g_date_time_new_now_local ();
	d = _tmp17_;
	_tmp18_ = g_date_time_to_unix (d);
	self->priv->last_schedule = (guint64) _tmp18_;
	self->priv->scheduled = (guint) 0;
	result = FALSE;
	_g_date_time_unref0 (d);
	return result;
}


static void ___lambda23_ (PanelDesktopData* self) {
	g_signal_emit_by_name (self, "changed");
}


static void ____lambda23__g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self) {
	___lambda23_ ((PanelDesktopData*) self);
}


static void panel_desktop_data_monitor (PanelDesktopData* self) {
	GFile* desktop_dir = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->path;
	_tmp1_ = g_file_new_for_path (_tmp0_);
	desktop_dir = _tmp1_;
	{
		GFileMonitor* _tmp2_ = NULL;
		GFileMonitor* _tmp3_ = NULL;
		GFileMonitor* _tmp4_ = NULL;
		GFileMonitor* _tmp5_ = NULL;
		_tmp3_ = g_file_monitor (desktop_dir, G_FILE_MONITOR_NONE, NULL, &_inner_error_);
		_tmp2_ = _tmp3_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch29_g_error;
		}
		_tmp4_ = _tmp2_;
		_tmp2_ = NULL;
		_g_object_unref0 (self->priv->desktop_monitor);
		self->priv->desktop_monitor = _tmp4_;
		_tmp5_ = self->priv->desktop_monitor;
		g_signal_connect (_tmp5_, "changed", (GCallback) ____lambda23__g_file_monitor_changed, self);
		_g_object_unref0 (_tmp2_);
	}
	goto __finally29;
	__catch29_g_error:
	{
		GError* e = NULL;
		FILE* _tmp6_ = NULL;
		GError* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp6_ = stdout;
		_tmp7_ = e;
		_tmp8_ = _tmp7_->message;
		fprintf (_tmp6_, "Can't monitor desktop directory: %s\n", _tmp8_);
		_g_error_free0 (e);
	}
	__finally29:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (desktop_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (desktop_dir);
}


static void panel_desktop_data_update_tree (PanelDesktopData* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GDir* dir = NULL;
		const gchar* _tmp0_ = NULL;
		GDir* _tmp1_ = NULL;
		_tmp0_ = self->priv->path;
		_tmp1_ = g_dir_open (_tmp0_, (guint) 0, &_inner_error_);
		dir = _tmp1_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_FILE_ERROR) {
				goto __catch30_g_file_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		while (TRUE) {
			gchar* name = NULL;
			GDir* _tmp2_ = NULL;
			const gchar* _tmp3_ = NULL;
			gchar* _tmp4_ = NULL;
			const gchar* _tmp5_ = NULL;
			const gchar* _tmp6_ = NULL;
			gboolean _tmp7_ = FALSE;
			_tmp2_ = dir;
			_tmp3_ = g_dir_read_name (_tmp2_);
			_tmp4_ = g_strdup (_tmp3_);
			name = _tmp4_;
			_tmp5_ = name;
			if (_tmp5_ == NULL) {
				_g_free0 (name);
				break;
			}
			_tmp6_ = name;
			_tmp7_ = g_str_has_suffix (_tmp6_, ".desktop");
			if (_tmp7_) {
				GDesktopAppInfo* info = NULL;
				const gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
				gchar* _tmp10_ = NULL;
				const gchar* _tmp11_ = NULL;
				gchar* _tmp12_ = NULL;
				gchar* _tmp13_ = NULL;
				GDesktopAppInfo* _tmp14_ = NULL;
				GDesktopAppInfo* _tmp15_ = NULL;
				gchar* s = NULL;
				GDesktopAppInfo* _tmp16_ = NULL;
				GIcon* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				gchar* _tmp19_ = NULL;
				gchar* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				GDesktopAppInfo* _tmp22_ = NULL;
				const gchar* _tmp23_ = NULL;
				const gchar* _tmp24_ = NULL;
				gchar* _tmp25_ = NULL;
				gchar* _tmp26_ = NULL;
				GString* _tmp27_ = NULL;
				const gchar* _tmp28_ = NULL;
				_tmp8_ = self->priv->path;
				_tmp9_ = g_strconcat (_tmp8_, "/", NULL);
				_tmp10_ = _tmp9_;
				_tmp11_ = name;
				_tmp12_ = g_strconcat (_tmp10_, _tmp11_, NULL);
				_tmp13_ = _tmp12_;
				_tmp14_ = g_desktop_app_info_new_from_filename (_tmp13_);
				_tmp15_ = _tmp14_;
				_g_free0 (_tmp13_);
				_g_free0 (_tmp10_);
				info = _tmp15_;
				_tmp16_ = info;
				_tmp17_ = g_app_info_get_icon ((GAppInfo*) _tmp16_);
				_tmp18_ = g_icon_to_string (_tmp17_);
				_tmp19_ = _tmp18_;
				_tmp20_ = utils_get_icon_path (_tmp19_, 120);
				_tmp21_ = _tmp20_;
				_tmp22_ = info;
				_tmp23_ = g_app_info_get_name ((GAppInfo*) _tmp22_);
				_tmp24_ = name;
				_tmp25_ = g_strdup_printf ("{icon: '%s', name: '%s', desktop: '%s'},", _tmp21_, _tmp23_, _tmp24_);
				_tmp26_ = _tmp25_;
				_g_free0 (_tmp21_);
				_g_free0 (_tmp19_);
				s = _tmp26_;
				_tmp27_ = self->priv->json;
				_tmp28_ = s;
				g_string_append (_tmp27_, _tmp28_);
				_g_free0 (s);
				_g_object_unref0 (info);
			}
			_g_free0 (name);
		}
		_g_dir_close0 (dir);
	}
	goto __finally30;
	__catch30_g_file_error:
	{
		GError* e = NULL;
		FILE* _tmp29_ = NULL;
		GError* _tmp30_ = NULL;
		const gchar* _tmp31_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp29_ = stdout;
		_tmp30_ = e;
		_tmp31_ = _tmp30_->message;
		fprintf (_tmp29_, "Unable to open desktop directory: %s\n", _tmp31_);
		_g_error_free0 (e);
	}
	__finally30:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static void panel_desktop_data_populate (PanelDesktopData* self) {
	GString* _tmp0_ = NULL;
	GString* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GString* _tmp3_ = NULL;
	gssize _tmp4_ = 0L;
	gchar _tmp5_ = '\0';
	GString* _tmp9_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->json;
	g_string_assign (_tmp0_, "[");
	panel_desktop_data_update_tree (self);
	_tmp1_ = self->priv->json;
	_tmp2_ = _tmp1_->str;
	_tmp3_ = self->priv->json;
	_tmp4_ = _tmp3_->len;
	_tmp5_ = string_get (_tmp2_, (glong) (_tmp4_ - 1));
	if (_tmp5_ == ',') {
		GString* _tmp6_ = NULL;
		GString* _tmp7_ = NULL;
		gssize _tmp8_ = 0L;
		_tmp6_ = self->priv->json;
		_tmp7_ = self->priv->json;
		_tmp8_ = _tmp7_->len;
		g_string_erase (_tmp6_, _tmp8_ - 1, (gssize) 1);
	}
	_tmp9_ = self->priv->json;
	g_string_append (_tmp9_, "]");
}


static void panel_desktop_data_remove_from_desktop (const gchar* filename) {
	gchar* path = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GFile* file = NULL;
	const gchar* _tmp6_ = NULL;
	GFile* _tmp7_ = NULL;
	GFile* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (filename != NULL);
	_tmp0_ = g_get_user_special_dir (G_USER_DIRECTORY_DESKTOP);
	_tmp1_ = g_strconcat (_tmp0_, "/", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = filename;
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_g_free0 (_tmp2_);
	path = _tmp5_;
	_tmp6_ = path;
	_tmp7_ = g_file_new_for_path (_tmp6_);
	file = _tmp7_;
	_tmp8_ = file;
	_tmp9_ = g_file_query_exists (_tmp8_, NULL);
	if (_tmp9_) {
		{
			GFile* _tmp10_ = NULL;
			_tmp10_ = file;
			g_file_delete (_tmp10_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch31_g_error;
			}
		}
		goto __finally31;
		__catch31_g_error:
		{
			GError* e = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_g_error_free0 (e);
		}
		__finally31:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (file);
			_g_free0 (path);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_g_object_unref0 (file);
	_g_free0 (path);
}


static void* _panel_desktop_data_js_update_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_desktop_data_js_update (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _panel_desktop_data_js_set_update_callback_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_desktop_data_js_set_update_callback (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


void* panel_desktop_data_js_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void* c = NULL;
	void* _tmp0_ = NULL;
	void* o = NULL;
	void* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
	void* s = NULL;
	void* _tmp3_ = NULL;
	void* f = NULL;
	void* _tmp4_ = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	void* _tmp8_ = NULL;
	void* _tmp9_ = NULL;
	void* _tmp10_ = NULL;
	void* _tmp11_ = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	void* _tmp16_ = NULL;
	PanelDesktopData* i = NULL;
	PanelDesktopData* _tmp17_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (constructor != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = JSClassCreate (&PANEL_DESKTOP_DATA_js_class);
	c = _tmp0_;
	_tmp1_ = ctx;
	_tmp2_ = JSObjectMake (_tmp1_, c, NULL);
	o = _tmp2_;
	_tmp3_ = JSStringCreateWithUTF8CString ("update");
	s = _tmp3_;
	_tmp4_ = ctx;
	_tmp5_ = s;
	_tmp6_ = JSObjectMakeFunctionWithCallback (_tmp4_, _tmp5_, _panel_desktop_data_js_update_js_core_object_call_as_function_callback);
	f = _tmp6_;
	_tmp7_ = ctx;
	_tmp8_ = s;
	_tmp9_ = f;
	JSObjectSetProperty (_tmp7_, o, _tmp8_, _tmp9_, 0, NULL);
	_tmp10_ = JSStringCreateWithUTF8CString ("updateCallback");
	_JSStringRelease0 (s);
	s = _tmp10_;
	_tmp11_ = ctx;
	_tmp12_ = s;
	_tmp13_ = JSObjectMakeFunctionWithCallback (_tmp11_, _tmp12_, _panel_desktop_data_js_set_update_callback_js_core_object_call_as_function_callback);
	_0 (f);
	f = _tmp13_;
	_tmp14_ = ctx;
	_tmp15_ = s;
	_tmp16_ = f;
	JSObjectSetProperty (_tmp14_, o, _tmp15_, _tmp16_, 0, NULL);
	_tmp17_ = panel_desktop_data_new ();
	i = _tmp17_;
	JSObjectSetPrivate (o, i);
	i->priv->jsObject = o;
	result = o;
	_0 (f);
	_JSStringRelease0 (s);
	_JSClassRelease0 (c);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static gpointer _panel_desktop_data_ref0 (gpointer self) {
	return self ? panel_desktop_data_ref (self) : NULL;
}


void* panel_desktop_data_js_set_update_callback (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelDesktopData* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelDesktopData* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	PanelDesktopData* _tmp4_ = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_desktop_data_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_DESKTOP_DATA) ? ((PanelDesktopData*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp4_ = i;
	if (_tmp4_ != NULL) {
		void** _tmp5_ = NULL;
		gint _tmp5__length1 = 0;
		_tmp5_ = arguments;
		_tmp5__length1 = arguments_length1;
		_tmp3_ = _tmp5__length1 == 1;
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		void* s = NULL;
		void* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		void* _tmp9_ = NULL;
		void** _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		void* _tmp11_ = NULL;
		_tmp6_ = JSStringCreateWithUTF8CString ("updateCallback");
		s = _tmp6_;
		_tmp7_ = thisObject;
		_tmp8_ = ctx;
		_tmp9_ = s;
		_tmp10_ = arguments;
		_tmp10__length1 = arguments_length1;
		_tmp11_ = _tmp10_[0];
		JSObjectSetProperty (_tmp8_, _tmp7_, _tmp9_, _tmp11_, 0, NULL);
		_JSStringRelease0 (s);
	}
	_tmp12_ = ctx;
	_tmp13_ = JSValueMakeUndefined (_tmp12_);
	result = _tmp13_;
	_panel_desktop_data_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* panel_desktop_data_js_update (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelDesktopData* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelDesktopData* _tmp2_ = NULL;
	PanelDesktopData* _tmp3_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_desktop_data_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_DESKTOP_DATA) ? ((PanelDesktopData*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp3_ = i;
	if (_tmp3_ != NULL) {
		PanelDesktopData* _tmp4_ = NULL;
		void* s = NULL;
		PanelDesktopData* _tmp5_ = NULL;
		GString* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		void* r = NULL;
		void* _tmp9_ = NULL;
		void* _tmp10_ = NULL;
		void* _tmp11_ = NULL;
		PanelDesktopData* _tmp12_ = NULL;
		GString* _tmp13_ = NULL;
		_tmp4_ = i;
		panel_desktop_data_populate (_tmp4_);
		_tmp5_ = i;
		_tmp6_ = _tmp5_->priv->json;
		_tmp7_ = _tmp6_->str;
		_tmp8_ = JSStringCreateWithUTF8CString (_tmp7_);
		s = _tmp8_;
		_tmp9_ = ctx;
		_tmp10_ = s;
		_tmp11_ = JSEvaluateScript (_tmp9_, _tmp10_, NULL, NULL, 0, NULL);
		r = _tmp11_;
		_JSStringRelease0 (s);
		s = NULL;
		_tmp12_ = i;
		_tmp13_ = _tmp12_->priv->json;
		g_string_assign (_tmp13_, "");
		result = r;
		_JSStringRelease0 (s);
		_panel_desktop_data_unref0 (i);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp14_ = ctx;
	_tmp15_ = JSValueMakeUndefined (_tmp14_);
	result = _tmp15_;
	_panel_desktop_data_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* panel_desktop_data_js_remove_from_desktop (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 == 1) {
		void* s = NULL;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* _tmp2_ = NULL;
		void* _tmp3_ = NULL;
		void* _tmp4_ = NULL;
		gchar buffer[1024] = {0};
		void* _tmp5_ = NULL;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		_tmp2_ = _tmp1_[0];
		_tmp3_ = ctx;
		_tmp4_ = JSValueToStringCopy (_tmp3_, _tmp2_, NULL);
		s = _tmp4_;
		_tmp5_ = s;
		JSStringGetUTF8CString (_tmp5_, buffer, (gsize) 1024);
		panel_desktop_data_remove_from_desktop ((const gchar*) buffer);
		_JSStringRelease0 (s);
	}
	_tmp6_ = ctx;
	_tmp7_ = JSValueMakeUndefined (_tmp6_);
	result = _tmp7_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void panel_desktop_data_setup_js_class (void* context) {
	void* _tmp0_ = NULL;
	void* c = NULL;
	void* _tmp1_ = NULL;
	void* o = NULL;
	void* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* _tmp4_ = NULL;
	void* g = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* s = NULL;
	void* _tmp7_ = NULL;
	void* _tmp8_ = NULL;
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	panel_desktop_data_jsContext = _tmp0_;
	_tmp1_ = JSClassCreate (&PANEL_DESKTOP_DATA_js_class);
	c = _tmp1_;
	_tmp2_ = context;
	_tmp3_ = context;
	_tmp4_ = JSObjectMake (_tmp2_, c, _tmp3_);
	o = _tmp4_;
	_tmp5_ = context;
	_tmp6_ = JSContextGetGlobalObject (_tmp5_);
	g = _tmp6_;
	_tmp7_ = JSStringCreateWithUTF8CString ("DesktopData");
	s = _tmp7_;
	_tmp8_ = context;
	JSObjectSetProperty (_tmp8_, g, s, o, kJSPropertyAttributeNone, NULL);
	_JSStringRelease0 (s);
	_0 (g);
	_0 (o);
	_JSClassRelease0 (c);
}


static void value_panel_desktop_data_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_panel_desktop_data_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		panel_desktop_data_unref (value->data[0].v_pointer);
	}
}


static void value_panel_desktop_data_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = panel_desktop_data_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_panel_desktop_data_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_panel_desktop_data_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		PanelDesktopData* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = panel_desktop_data_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_panel_desktop_data_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PanelDesktopData** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = panel_desktop_data_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_panel_desktop_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecPanelDesktopData* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_PANEL_DESKTOP_DATA), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_panel_desktop_data (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_DESKTOP_DATA), NULL);
	return value->data[0].v_pointer;
}


void value_set_panel_desktop_data (GValue* value, gpointer v_object) {
	PanelDesktopData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_DESKTOP_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PANEL_DESKTOP_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		panel_desktop_data_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		panel_desktop_data_unref (old);
	}
}


void value_take_panel_desktop_data (GValue* value, gpointer v_object) {
	PanelDesktopData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_DESKTOP_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PANEL_DESKTOP_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		panel_desktop_data_unref (old);
	}
}


static void panel_desktop_data_class_init (PanelDesktopDataClass * klass) {
	panel_desktop_data_parent_class = g_type_class_peek_parent (klass);
	((PanelDesktopDataClass *) klass)->finalize = panel_desktop_data_finalize;
	g_type_class_add_private (klass, sizeof (PanelDesktopDataPrivate));
	g_signal_new ("changed", TYPE_PANEL_DESKTOP_DATA, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void panel_desktop_data_instance_init (PanelDesktopData * self) {
	self->priv = PANEL_DESKTOP_DATA_GET_PRIVATE (self);
	self->priv->desktop_monitor = NULL;
	self->priv->scheduled = (guint) 0;
	self->priv->last_schedule = (guint64) 0;
	self->ref_count = 1;
}


static void panel_desktop_data_finalize (PanelDesktopData* obj) {
	PanelDesktopData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_DESKTOP_DATA, PanelDesktopData);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->desktop_monitor);
	_g_string_free0 (self->priv->json);
	_g_free0 (self->priv->path);
}


GType panel_desktop_data_get_type (void) {
	static volatile gsize panel_desktop_data_type_id__volatile = 0;
	if (g_once_init_enter (&panel_desktop_data_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_panel_desktop_data_init, value_panel_desktop_data_free_value, value_panel_desktop_data_copy_value, value_panel_desktop_data_peek_pointer, "p", value_panel_desktop_data_collect_value, "p", value_panel_desktop_data_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PanelDesktopDataClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_desktop_data_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelDesktopData), 0, (GInstanceInitFunc) panel_desktop_data_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType panel_desktop_data_type_id;
		panel_desktop_data_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PanelDesktopData", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&panel_desktop_data_type_id__volatile, panel_desktop_data_type_id);
	}
	return panel_desktop_data_type_id__volatile;
}


gpointer panel_desktop_data_ref (gpointer instance) {
	PanelDesktopData* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void panel_desktop_data_unref (gpointer instance) {
	PanelDesktopData* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PANEL_DESKTOP_DATA_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



