/* panel-user.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-user.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <JavaScriptCore/JavaScript.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define TYPE_XDG_ACCOUNTS (xdg_accounts_get_type ())
#define XDG_ACCOUNTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XDG_ACCOUNTS, XdgAccounts))
#define IS_XDG_ACCOUNTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XDG_ACCOUNTS))
#define XDG_ACCOUNTS_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_XDG_ACCOUNTS, XdgAccountsIface))

typedef struct _XdgAccounts XdgAccounts;
typedef struct _XdgAccountsIface XdgAccountsIface;

#define TYPE_XDG_ACCOUNTS_PROXY (xdg_accounts_proxy_get_type ())
typedef GDBusProxy XdgAccountsProxy;
typedef GDBusProxyClass XdgAccountsProxyClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_XDG_ACCOUNTS_USER (xdg_accounts_user_get_type ())
#define XDG_ACCOUNTS_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XDG_ACCOUNTS_USER, XdgAccountsUser))
#define IS_XDG_ACCOUNTS_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XDG_ACCOUNTS_USER))
#define XDG_ACCOUNTS_USER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_XDG_ACCOUNTS_USER, XdgAccountsUserIface))

typedef struct _XdgAccountsUser XdgAccountsUser;
typedef struct _XdgAccountsUserIface XdgAccountsUserIface;

#define TYPE_XDG_ACCOUNTS_USER_PROXY (xdg_accounts_user_proxy_get_type ())
typedef GDBusProxy XdgAccountsUserProxy;
typedef GDBusProxyClass XdgAccountsUserProxyClass;

#define TYPE_PANEL_USER (panel_user_get_type ())
#define PANEL_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_USER, PanelUser))
#define PANEL_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_USER, PanelUserClass))
#define IS_PANEL_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_USER))
#define IS_PANEL_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_USER))
#define PANEL_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_USER, PanelUserClass))

typedef struct _PanelUser PanelUser;
typedef struct _PanelUserClass PanelUserClass;
typedef struct _PanelUserPrivate PanelUserPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _JSStringRelease0(var) ((var == NULL) ? NULL : (var = (JSStringRelease (var), NULL)))
#define _JSClassRelease0(var) ((var == NULL) ? NULL : (var = (JSClassRelease (var), NULL)))
#define _panel_user_unref0(var) ((var == NULL) ? NULL : (var = (panel_user_unref (var), NULL)))
typedef struct _ParamSpecPanelUser ParamSpecPanelUser;

struct _XdgAccountsIface {
	GTypeInterface parent_iface;
	void (*find_user_by_name) (XdgAccounts* self, const gchar* user, char** path, GError** error);
};

struct _XdgAccountsUserIface {
	GTypeInterface parent_iface;
	gchar* (*get_user_name) (XdgAccountsUser* self);
	gchar* (*get_real_name) (XdgAccountsUser* self);
	gchar* (*get_icon_file) (XdgAccountsUser* self);
};

struct _PanelUser {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PanelUserPrivate * priv;
};

struct _PanelUserClass {
	GTypeClass parent_class;
	void (*finalize) (PanelUser *self);
};

struct _PanelUserPrivate {
	XdgAccountsUser* user;
	char* user_path;
};

struct _ParamSpecPanelUser {
	GParamSpec parent_instance;
};


static gpointer panel_user_parent_class = NULL;

GType xdg_accounts_proxy_get_type (void) G_GNUC_CONST;
guint xdg_accounts_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType xdg_accounts_get_type (void) G_GNUC_CONST;
void xdg_accounts_find_user_by_name (XdgAccounts* self, const gchar* user, char** path, GError** error);
static void xdg_accounts_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void xdg_accounts_proxy_find_user_by_name (XdgAccounts* self, const gchar* user, char** path, GError** error);
static void xdg_accounts_proxy_xdg_accounts_interface_init (XdgAccountsIface* iface);
static void _dbus_xdg_accounts_find_user_by_name (XdgAccounts* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void xdg_accounts_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* xdg_accounts_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean xdg_accounts_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _xdg_accounts_unregister_object (gpointer user_data);
GType xdg_accounts_user_get_type (void) G_GNUC_CONST;
GType xdg_accounts_user_proxy_get_type (void) G_GNUC_CONST;
guint xdg_accounts_user_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
gchar* xdg_accounts_user_get_user_name (XdgAccountsUser* self);
gchar* xdg_accounts_user_get_real_name (XdgAccountsUser* self);
gchar* xdg_accounts_user_get_icon_file (XdgAccountsUser* self);
static void xdg_accounts_user_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static gchar* xdg_accounts_user_dbus_proxy_get_user_name (XdgAccountsUser* self);
static gchar* xdg_accounts_user_dbus_proxy_get_real_name (XdgAccountsUser* self);
static gchar* xdg_accounts_user_dbus_proxy_get_icon_file (XdgAccountsUser* self);
static void xdg_accounts_user_proxy_xdg_accounts_user_interface_init (XdgAccountsUserIface* iface);
static void xdg_accounts_user_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* xdg_accounts_user_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static GVariant* _dbus_xdg_accounts_user_get_user_name (XdgAccountsUser* self);
static GVariant* _dbus_xdg_accounts_user_get_real_name (XdgAccountsUser* self);
static GVariant* _dbus_xdg_accounts_user_get_icon_file (XdgAccountsUser* self);
static gboolean xdg_accounts_user_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _xdg_accounts_user_unregister_object (gpointer user_data);
gpointer panel_user_ref (gpointer instance);
void panel_user_unref (gpointer instance);
GParamSpec* param_spec_panel_user (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_panel_user (GValue* value, gpointer v_object);
void value_take_panel_user (GValue* value, gpointer v_object);
gpointer value_get_panel_user (const GValue* value);
GType panel_user_get_type (void) G_GNUC_CONST;
#define PANEL_USER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_USER, PanelUserPrivate))
enum  {
	PANEL_USER_DUMMY_PROPERTY
};
void* panel_user_js_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception);
static void* _panel_user_js_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception);
PanelUser* panel_user_new (void);
PanelUser* panel_user_construct (GType object_type);
static void panel_user_update (PanelUser* self);
void* panel_user_js_get_real_name (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_user_js_get_real_name_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void* panel_user_js_get_host_name (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_user_js_get_host_name_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void* panel_user_js_get_icon_file (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_user_js_get_icon_file_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
gchar* panel_user_get_real_name (PanelUser* self);
gchar* panel_user_get_icon_file (PanelUser* self);
void panel_user_setup_js_class (void* context);
gchar* utils_get_icon_path (const gchar* name, gint size);
gchar* panel_user_get_host_name (PanelUser* self);
static void panel_user_finalize (PanelUser* obj);

static const GDBusArgInfo _xdg_accounts_dbus_arg_info_find_user_by_name_user = {-1, "user", "s"};
static const GDBusArgInfo _xdg_accounts_dbus_arg_info_find_user_by_name_path = {-1, "path", "o"};
static const GDBusArgInfo * const _xdg_accounts_dbus_arg_info_find_user_by_name_in[] = {&_xdg_accounts_dbus_arg_info_find_user_by_name_user, NULL};
static const GDBusArgInfo * const _xdg_accounts_dbus_arg_info_find_user_by_name_out[] = {&_xdg_accounts_dbus_arg_info_find_user_by_name_path, NULL};
static const GDBusMethodInfo _xdg_accounts_dbus_method_info_find_user_by_name = {-1, "FindUserByName", (GDBusArgInfo **) (&_xdg_accounts_dbus_arg_info_find_user_by_name_in), (GDBusArgInfo **) (&_xdg_accounts_dbus_arg_info_find_user_by_name_out)};
static const GDBusMethodInfo * const _xdg_accounts_dbus_method_info[] = {&_xdg_accounts_dbus_method_info_find_user_by_name, NULL};
static const GDBusSignalInfo * const _xdg_accounts_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _xdg_accounts_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _xdg_accounts_dbus_interface_info = {-1, "org.freedesktop.Accounts", (GDBusMethodInfo **) (&_xdg_accounts_dbus_method_info), (GDBusSignalInfo **) (&_xdg_accounts_dbus_signal_info), (GDBusPropertyInfo **) (&_xdg_accounts_dbus_property_info)};
static const GDBusInterfaceVTable _xdg_accounts_dbus_interface_vtable = {xdg_accounts_dbus_interface_method_call, xdg_accounts_dbus_interface_get_property, xdg_accounts_dbus_interface_set_property};
static const GDBusMethodInfo * const _xdg_accounts_user_dbus_method_info[] = {NULL};
static const GDBusSignalInfo * const _xdg_accounts_user_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo _xdg_accounts_user_dbus_property_info_user_name = {-1, "UserName", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _xdg_accounts_user_dbus_property_info_real_name = {-1, "RealName", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _xdg_accounts_user_dbus_property_info_icon_file = {-1, "IconFile", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo * const _xdg_accounts_user_dbus_property_info[] = {&_xdg_accounts_user_dbus_property_info_user_name, &_xdg_accounts_user_dbus_property_info_real_name, &_xdg_accounts_user_dbus_property_info_icon_file, NULL};
static const GDBusInterfaceInfo _xdg_accounts_user_dbus_interface_info = {-1, "org.freedesktop.Accounts.User", (GDBusMethodInfo **) (&_xdg_accounts_user_dbus_method_info), (GDBusSignalInfo **) (&_xdg_accounts_user_dbus_signal_info), (GDBusPropertyInfo **) (&_xdg_accounts_user_dbus_property_info)};
static const GDBusInterfaceVTable _xdg_accounts_user_dbus_interface_vtable = {xdg_accounts_user_dbus_interface_method_call, xdg_accounts_user_dbus_interface_get_property, xdg_accounts_user_dbus_interface_set_property};
static const JSClassDefinition PANEL_USER_js_class = {0, kJSClassAttributeNone, "UserAccount", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, _panel_user_js_constructor_js_core_object_call_as_constructor_callback, NULL, NULL};

void xdg_accounts_find_user_by_name (XdgAccounts* self, const gchar* user, char** path, GError** error) {
	g_return_if_fail (self != NULL);
	XDG_ACCOUNTS_GET_INTERFACE (self)->find_user_by_name (self, user, path, error);
}


static void xdg_accounts_base_init (XdgAccountsIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType xdg_accounts_get_type (void) {
	static volatile gsize xdg_accounts_type_id__volatile = 0;
	if (g_once_init_enter (&xdg_accounts_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (XdgAccountsIface), (GBaseInitFunc) xdg_accounts_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType xdg_accounts_type_id;
		xdg_accounts_type_id = g_type_register_static (G_TYPE_INTERFACE, "XdgAccounts", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (xdg_accounts_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (xdg_accounts_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) xdg_accounts_proxy_get_type);
		g_type_set_qdata (xdg_accounts_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freedesktop.Accounts");
		g_type_set_qdata (xdg_accounts_type_id, g_quark_from_static_string ("vala-dbus-interface-info"), (void*) (&_xdg_accounts_dbus_interface_info));
		g_type_set_qdata (xdg_accounts_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) xdg_accounts_register_object);
		g_once_init_leave (&xdg_accounts_type_id__volatile, xdg_accounts_type_id);
	}
	return xdg_accounts_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (XdgAccountsProxy, xdg_accounts_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_XDG_ACCOUNTS, xdg_accounts_proxy_xdg_accounts_interface_init) )
static void xdg_accounts_proxy_class_init (XdgAccountsProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = xdg_accounts_proxy_g_signal;
}


static void xdg_accounts_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void xdg_accounts_proxy_init (XdgAccountsProxy* self) {
}


static void xdg_accounts_proxy_find_user_by_name (XdgAccounts* self, const gchar* user, char** path, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	char* _vala_path;
	GVariant* _tmp9_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freedesktop.Accounts", "FindUserByName");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (user));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp9_ = g_variant_iter_next_value (&_reply_iter);
	_vala_path = g_variant_dup_string (_tmp9_, NULL);
	g_variant_unref (_tmp9_);
	*path = _vala_path;
	g_object_unref (_reply_message);
}


static void xdg_accounts_proxy_xdg_accounts_interface_init (XdgAccountsIface* iface) {
	iface->find_user_by_name = xdg_accounts_proxy_find_user_by_name;
}


static void _dbus_xdg_accounts_find_user_by_name (XdgAccounts* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* user = NULL;
	GVariant* _tmp10_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	char* path = NULL;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_tmp10_ = g_variant_iter_next_value (&_arguments_iter);
	user = g_variant_dup_string (_tmp10_, NULL);
	g_variant_unref (_tmp10_);
	xdg_accounts_find_user_by_name (self, user, &path, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_object_path (path));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (user);
	_g_free0 (path);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void xdg_accounts_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "FindUserByName") == 0) {
		_dbus_xdg_accounts_find_user_by_name (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* xdg_accounts_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean xdg_accounts_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint xdg_accounts_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_xdg_accounts_dbus_interface_info), &_xdg_accounts_dbus_interface_vtable, data, _xdg_accounts_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _xdg_accounts_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


gchar* xdg_accounts_user_get_user_name (XdgAccountsUser* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return XDG_ACCOUNTS_USER_GET_INTERFACE (self)->get_user_name (self);
}


gchar* xdg_accounts_user_get_real_name (XdgAccountsUser* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return XDG_ACCOUNTS_USER_GET_INTERFACE (self)->get_real_name (self);
}


gchar* xdg_accounts_user_get_icon_file (XdgAccountsUser* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return XDG_ACCOUNTS_USER_GET_INTERFACE (self)->get_icon_file (self);
}


static void xdg_accounts_user_base_init (XdgAccountsUserIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType xdg_accounts_user_get_type (void) {
	static volatile gsize xdg_accounts_user_type_id__volatile = 0;
	if (g_once_init_enter (&xdg_accounts_user_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (XdgAccountsUserIface), (GBaseInitFunc) xdg_accounts_user_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType xdg_accounts_user_type_id;
		xdg_accounts_user_type_id = g_type_register_static (G_TYPE_INTERFACE, "XdgAccountsUser", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (xdg_accounts_user_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (xdg_accounts_user_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) xdg_accounts_user_proxy_get_type);
		g_type_set_qdata (xdg_accounts_user_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freedesktop.Accounts.User");
		g_type_set_qdata (xdg_accounts_user_type_id, g_quark_from_static_string ("vala-dbus-interface-info"), (void*) (&_xdg_accounts_user_dbus_interface_info));
		g_type_set_qdata (xdg_accounts_user_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) xdg_accounts_user_register_object);
		g_once_init_leave (&xdg_accounts_user_type_id__volatile, xdg_accounts_user_type_id);
	}
	return xdg_accounts_user_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (XdgAccountsUserProxy, xdg_accounts_user_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_XDG_ACCOUNTS_USER, xdg_accounts_user_proxy_xdg_accounts_user_interface_init) )
static void xdg_accounts_user_proxy_class_init (XdgAccountsUserProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = xdg_accounts_user_proxy_g_signal;
}


static void xdg_accounts_user_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void xdg_accounts_user_proxy_init (XdgAccountsUserProxy* self) {
}


static gchar* xdg_accounts_user_dbus_proxy_get_user_name (XdgAccountsUser* self) {
	GVariant *_inner_reply;
	gchar* _result;
	_inner_reply = g_dbus_proxy_get_cached_property ((GDBusProxy *) self, "UserName");
	if (!_inner_reply) {
		GVariant *_arguments;
		GVariant *_reply;
		GVariantBuilder _arguments_builder;
		g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
		g_variant_builder_add_value (&_arguments_builder, g_variant_new_string ("org.freedesktop.Accounts.User"));
		g_variant_builder_add_value (&_arguments_builder, g_variant_new_string ("UserName"));
		_arguments = g_variant_builder_end (&_arguments_builder);
		_reply = g_dbus_proxy_call_sync ((GDBusProxy *) self, "org.freedesktop.DBus.Properties.Get", _arguments, G_DBUS_CALL_FLAGS_NONE, -1, NULL, NULL);
		if (!_reply) {
			return NULL;
		}
		g_variant_get (_reply, "(v)", &_inner_reply);
		g_variant_unref (_reply);
	}
	_result = g_variant_dup_string (_inner_reply, NULL);
	g_variant_unref (_inner_reply);
	return _result;
}


static gchar* xdg_accounts_user_dbus_proxy_get_real_name (XdgAccountsUser* self) {
	GVariant *_inner_reply;
	gchar* _result;
	_inner_reply = g_dbus_proxy_get_cached_property ((GDBusProxy *) self, "RealName");
	if (!_inner_reply) {
		GVariant *_arguments;
		GVariant *_reply;
		GVariantBuilder _arguments_builder;
		g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
		g_variant_builder_add_value (&_arguments_builder, g_variant_new_string ("org.freedesktop.Accounts.User"));
		g_variant_builder_add_value (&_arguments_builder, g_variant_new_string ("RealName"));
		_arguments = g_variant_builder_end (&_arguments_builder);
		_reply = g_dbus_proxy_call_sync ((GDBusProxy *) self, "org.freedesktop.DBus.Properties.Get", _arguments, G_DBUS_CALL_FLAGS_NONE, -1, NULL, NULL);
		if (!_reply) {
			return NULL;
		}
		g_variant_get (_reply, "(v)", &_inner_reply);
		g_variant_unref (_reply);
	}
	_result = g_variant_dup_string (_inner_reply, NULL);
	g_variant_unref (_inner_reply);
	return _result;
}


static gchar* xdg_accounts_user_dbus_proxy_get_icon_file (XdgAccountsUser* self) {
	GVariant *_inner_reply;
	gchar* _result;
	_inner_reply = g_dbus_proxy_get_cached_property ((GDBusProxy *) self, "IconFile");
	if (!_inner_reply) {
		GVariant *_arguments;
		GVariant *_reply;
		GVariantBuilder _arguments_builder;
		g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
		g_variant_builder_add_value (&_arguments_builder, g_variant_new_string ("org.freedesktop.Accounts.User"));
		g_variant_builder_add_value (&_arguments_builder, g_variant_new_string ("IconFile"));
		_arguments = g_variant_builder_end (&_arguments_builder);
		_reply = g_dbus_proxy_call_sync ((GDBusProxy *) self, "org.freedesktop.DBus.Properties.Get", _arguments, G_DBUS_CALL_FLAGS_NONE, -1, NULL, NULL);
		if (!_reply) {
			return NULL;
		}
		g_variant_get (_reply, "(v)", &_inner_reply);
		g_variant_unref (_reply);
	}
	_result = g_variant_dup_string (_inner_reply, NULL);
	g_variant_unref (_inner_reply);
	return _result;
}


static void xdg_accounts_user_proxy_xdg_accounts_user_interface_init (XdgAccountsUserIface* iface) {
	iface->get_user_name = xdg_accounts_user_dbus_proxy_get_user_name;
	iface->get_real_name = xdg_accounts_user_dbus_proxy_get_real_name;
	iface->get_icon_file = xdg_accounts_user_dbus_proxy_get_icon_file;
}


static void xdg_accounts_user_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	g_object_unref (invocation);
}


static GVariant* _dbus_xdg_accounts_user_get_user_name (XdgAccountsUser* self) {
	gchar* result;
	GVariant* _reply;
	result = xdg_accounts_user_get_user_name (self);
	_reply = g_variant_new_string (result);
	_g_free0 (result);
	return _reply;
}


static GVariant* _dbus_xdg_accounts_user_get_real_name (XdgAccountsUser* self) {
	gchar* result;
	GVariant* _reply;
	result = xdg_accounts_user_get_real_name (self);
	_reply = g_variant_new_string (result);
	_g_free0 (result);
	return _reply;
}


static GVariant* _dbus_xdg_accounts_user_get_icon_file (XdgAccountsUser* self) {
	gchar* result;
	GVariant* _reply;
	result = xdg_accounts_user_get_icon_file (self);
	_reply = g_variant_new_string (result);
	_g_free0 (result);
	return _reply;
}


static GVariant* xdg_accounts_user_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "UserName") == 0) {
		return _dbus_xdg_accounts_user_get_user_name (object);
	} else if (strcmp (property_name, "RealName") == 0) {
		return _dbus_xdg_accounts_user_get_real_name (object);
	} else if (strcmp (property_name, "IconFile") == 0) {
		return _dbus_xdg_accounts_user_get_icon_file (object);
	}
	return NULL;
}


static gboolean xdg_accounts_user_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint xdg_accounts_user_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_xdg_accounts_user_dbus_interface_info), &_xdg_accounts_user_dbus_interface_vtable, data, _xdg_accounts_user_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _xdg_accounts_user_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


static void* _panel_user_js_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_user_js_constructor (ctx, constructor, arguments, arguments_length1, exception);
	return result;
}


PanelUser* panel_user_construct (GType object_type) {
	PanelUser* self = NULL;
	XdgAccounts* session = NULL;
	GError * _inner_error_ = NULL;
	self = (PanelUser*) g_type_create_instance (object_type);
	session = NULL;
	{
		XdgAccounts* _tmp0_ = NULL;
		XdgAccounts* _tmp1_ = NULL;
		XdgAccounts* _tmp2_ = NULL;
		XdgAccounts* _tmp3_ = NULL;
		_tmp1_ = g_initable_new (TYPE_XDG_ACCOUNTS_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "org.freedesktop.Accounts", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", "/org/freedesktop/Accounts", "g-interface-name", "org.freedesktop.Accounts", "g-interface-info", g_type_get_qdata (TYPE_XDG_ACCOUNTS, g_quark_from_static_string ("vala-dbus-interface-info")), NULL);
		_tmp0_ = (XdgAccounts*) _tmp1_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch26_g_error;
		}
		_tmp2_ = _tmp0_;
		_tmp0_ = NULL;
		_g_object_unref0 (session);
		session = _tmp2_;
		_tmp3_ = session;
		if (_tmp3_ != NULL) {
			XdgAccounts* _tmp4_ = NULL;
			const gchar* _tmp5_ = NULL;
			char* _tmp6_ = NULL;
			_tmp4_ = session;
			_tmp5_ = g_get_user_name ();
			xdg_accounts_find_user_by_name (_tmp4_, _tmp5_, &_tmp6_, &_inner_error_);
			_g_free0 (self->priv->user_path);
			self->priv->user_path = _tmp6_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_object_unref0 (_tmp0_);
				goto __catch26_g_error;
			}
			panel_user_update (self);
		}
		_g_object_unref0 (_tmp0_);
	}
	goto __finally26;
	__catch26_g_error:
	{
		GError* e = NULL;
		FILE* _tmp7_ = NULL;
		GError* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp7_ = stderr;
		_tmp8_ = e;
		_tmp9_ = _tmp8_->message;
		_tmp10_ = g_strconcat ("Unable to connect to account manager: ", _tmp9_, NULL);
		_tmp11_ = _tmp10_;
		_tmp12_ = g_strconcat (_tmp11_, "\n", NULL);
		_tmp13_ = _tmp12_;
		fprintf (_tmp7_, "%s", _tmp13_);
		_g_free0 (_tmp13_);
		_g_free0 (_tmp11_);
		_g_error_free0 (e);
	}
	__finally26:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (session);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_g_object_unref0 (session);
	return self;
}


PanelUser* panel_user_new (void) {
	return panel_user_construct (TYPE_PANEL_USER);
}


static void panel_user_update (PanelUser* self) {
	const char* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->user_path;
	if (_tmp0_ == NULL) {
		return;
	}
	{
		XdgAccountsUser* _tmp1_ = NULL;
		const char* _tmp2_ = NULL;
		XdgAccountsUser* _tmp3_ = NULL;
		XdgAccountsUser* _tmp4_ = NULL;
		_tmp2_ = self->priv->user_path;
		_tmp3_ = g_initable_new (TYPE_XDG_ACCOUNTS_USER_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "org.freedesktop.Accounts", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", (const gchar*) _tmp2_, "g-interface-name", "org.freedesktop.Accounts.User", "g-interface-info", g_type_get_qdata (TYPE_XDG_ACCOUNTS_USER, g_quark_from_static_string ("vala-dbus-interface-info")), NULL);
		_tmp1_ = (XdgAccountsUser*) _tmp3_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch27_g_error;
		}
		_tmp4_ = _tmp1_;
		_tmp1_ = NULL;
		_g_object_unref0 (self->priv->user);
		self->priv->user = _tmp4_;
		_g_object_unref0 (_tmp1_);
	}
	goto __finally27;
	__catch27_g_error:
	{
		GError* e = NULL;
		FILE* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = stderr;
		_tmp6_ = e;
		_tmp7_ = _tmp6_->message;
		fprintf (_tmp5_, "Unable to connect to user account manager: %s\n", _tmp7_);
		_g_error_free0 (e);
	}
	__finally27:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void* _panel_user_js_get_real_name_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_user_js_get_real_name (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _panel_user_js_get_host_name_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_user_js_get_host_name (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _panel_user_js_get_icon_file_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_user_js_get_icon_file (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


void* panel_user_js_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void* c = NULL;
	void* _tmp0_ = NULL;
	void* o = NULL;
	void* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
	PanelUser* i = NULL;
	PanelUser* _tmp3_ = NULL;
	void* s = NULL;
	void* _tmp4_ = NULL;
	void* f = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	void* _tmp8_ = NULL;
	void* _tmp9_ = NULL;
	void* _tmp10_ = NULL;
	void* _tmp11_ = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	void* _tmp16_ = NULL;
	void* _tmp17_ = NULL;
	void* _tmp18_ = NULL;
	void* _tmp19_ = NULL;
	void* _tmp20_ = NULL;
	void* _tmp21_ = NULL;
	void* _tmp22_ = NULL;
	void* _tmp23_ = NULL;
	void* _tmp24_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (constructor != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = JSClassCreate (&PANEL_USER_js_class);
	c = _tmp0_;
	_tmp1_ = ctx;
	_tmp2_ = JSObjectMake (_tmp1_, c, NULL);
	o = _tmp2_;
	_tmp3_ = panel_user_new ();
	i = _tmp3_;
	_tmp4_ = JSStringCreateWithUTF8CString ("getRealName");
	s = _tmp4_;
	_tmp5_ = ctx;
	_tmp6_ = s;
	_tmp7_ = JSObjectMakeFunctionWithCallback (_tmp5_, _tmp6_, _panel_user_js_get_real_name_js_core_object_call_as_function_callback);
	f = _tmp7_;
	_tmp8_ = ctx;
	_tmp9_ = s;
	_tmp10_ = f;
	JSObjectSetProperty (_tmp8_, o, _tmp9_, _tmp10_, 0, NULL);
	_tmp11_ = JSStringCreateWithUTF8CString ("getHostName");
	_JSStringRelease0 (s);
	s = _tmp11_;
	_tmp12_ = ctx;
	_tmp13_ = s;
	_tmp14_ = JSObjectMakeFunctionWithCallback (_tmp12_, _tmp13_, _panel_user_js_get_host_name_js_core_object_call_as_function_callback);
	_0 (f);
	f = _tmp14_;
	_tmp15_ = ctx;
	_tmp16_ = s;
	_tmp17_ = f;
	JSObjectSetProperty (_tmp15_, o, _tmp16_, _tmp17_, 0, NULL);
	_tmp18_ = JSStringCreateWithUTF8CString ("getIconFile");
	_JSStringRelease0 (s);
	s = _tmp18_;
	_tmp19_ = ctx;
	_tmp20_ = s;
	_tmp21_ = JSObjectMakeFunctionWithCallback (_tmp19_, _tmp20_, _panel_user_js_get_icon_file_js_core_object_call_as_function_callback);
	_0 (f);
	f = _tmp21_;
	_tmp22_ = ctx;
	_tmp23_ = s;
	_tmp24_ = f;
	JSObjectSetProperty (_tmp22_, o, _tmp23_, _tmp24_, 0, NULL);
	JSObjectSetPrivate (o, i);
	result = o;
	_0 (f);
	_JSStringRelease0 (s);
	_JSClassRelease0 (c);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static gpointer _panel_user_ref0 (gpointer self) {
	return self ? panel_user_ref (self) : NULL;
}


void* panel_user_js_get_real_name (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelUser* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelUser* _tmp2_ = NULL;
	PanelUser* _tmp3_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_user_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_USER) ? ((PanelUser*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp3_ = i;
	if (_tmp3_ != NULL) {
		PanelUser* _tmp4_ = NULL;
		void* s = NULL;
		PanelUser* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		void* _tmp9_ = NULL;
		void* _tmp10_ = NULL;
		void* _tmp11_ = NULL;
		void* _tmp12_ = NULL;
		void* _tmp13_ = NULL;
		_tmp4_ = i;
		panel_user_update (_tmp4_);
		_tmp5_ = i;
		_tmp6_ = panel_user_get_real_name (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = _tmp7_;
		_tmp9_ = JSStringCreateWithUTF8CString (_tmp8_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		s = _tmp10_;
		_tmp11_ = ctx;
		_tmp12_ = s;
		_tmp13_ = JSValueMakeString (_tmp11_, _tmp12_);
		result = _tmp13_;
		_JSStringRelease0 (s);
		_panel_user_unref0 (i);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp14_ = ctx;
	_tmp15_ = JSValueMakeUndefined (_tmp14_);
	result = _tmp15_;
	_panel_user_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* panel_user_js_get_host_name (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelUser* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelUser* _tmp2_ = NULL;
	PanelUser* _tmp3_ = NULL;
	void* _tmp9_ = NULL;
	void* _tmp10_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_user_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_USER) ? ((PanelUser*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp3_ = i;
	if (_tmp3_ != NULL) {
		void* s = NULL;
		const gchar* _tmp4_ = NULL;
		void* _tmp5_ = NULL;
		void* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		_tmp4_ = g_get_host_name ();
		_tmp5_ = JSStringCreateWithUTF8CString (_tmp4_);
		s = _tmp5_;
		_tmp6_ = ctx;
		_tmp7_ = s;
		_tmp8_ = JSValueMakeString (_tmp6_, _tmp7_);
		result = _tmp8_;
		_JSStringRelease0 (s);
		_panel_user_unref0 (i);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp9_ = ctx;
	_tmp10_ = JSValueMakeUndefined (_tmp9_);
	result = _tmp10_;
	_panel_user_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* panel_user_js_get_icon_file (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelUser* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelUser* _tmp2_ = NULL;
	PanelUser* _tmp3_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_user_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_USER) ? ((PanelUser*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp3_ = i;
	if (_tmp3_ != NULL) {
		PanelUser* _tmp4_ = NULL;
		void* s = NULL;
		PanelUser* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		void* _tmp9_ = NULL;
		void* _tmp10_ = NULL;
		void* _tmp11_ = NULL;
		void* _tmp12_ = NULL;
		void* _tmp13_ = NULL;
		_tmp4_ = i;
		panel_user_update (_tmp4_);
		_tmp5_ = i;
		_tmp6_ = panel_user_get_icon_file (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = _tmp7_;
		_tmp9_ = JSStringCreateWithUTF8CString (_tmp8_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		s = _tmp10_;
		_tmp11_ = ctx;
		_tmp12_ = s;
		_tmp13_ = JSValueMakeString (_tmp11_, _tmp12_);
		result = _tmp13_;
		_JSStringRelease0 (s);
		_panel_user_unref0 (i);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp14_ = ctx;
	_tmp15_ = JSValueMakeUndefined (_tmp14_);
	result = _tmp15_;
	_panel_user_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void panel_user_setup_js_class (void* context) {
	void* c = NULL;
	void* _tmp0_ = NULL;
	void* o = NULL;
	void* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* g = NULL;
	void* _tmp4_ = NULL;
	void* _tmp5_ = NULL;
	void* s = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	g_return_if_fail (context != NULL);
	_tmp0_ = JSClassCreate (&PANEL_USER_js_class);
	c = _tmp0_;
	_tmp1_ = context;
	_tmp2_ = context;
	_tmp3_ = JSObjectMake (_tmp1_, c, _tmp2_);
	o = _tmp3_;
	_tmp4_ = context;
	_tmp5_ = JSContextGetGlobalObject (_tmp4_);
	g = _tmp5_;
	_tmp6_ = JSStringCreateWithUTF8CString ("UserAccount");
	s = _tmp6_;
	_tmp7_ = context;
	JSObjectSetProperty (_tmp7_, g, s, o, kJSPropertyAttributeNone, NULL);
	_JSStringRelease0 (s);
	_0 (g);
	_0 (o);
	_JSClassRelease0 (c);
}


gchar* panel_user_get_icon_file (PanelUser* self) {
	gchar* result;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	XdgAccountsUser* _tmp2_ = NULL;
	GFile* f = NULL;
	XdgAccountsUser* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	GFile* _tmp16_ = NULL;
	GFile* _tmp17_ = NULL;
	GFile* _tmp18_ = NULL;
	gboolean _tmp19_ = FALSE;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp2_ = self->priv->user;
	if (_tmp2_ == NULL) {
		_tmp1_ = TRUE;
	} else {
		XdgAccountsUser* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp3_ = self->priv->user;
		_tmp4_ = xdg_accounts_user_get_icon_file (_tmp3_);
		_tmp5_ = _tmp4_;
		_tmp6_ = _tmp5_;
		_tmp1_ = _tmp6_ == NULL;
		_g_free0 (_tmp6_);
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		XdgAccountsUser* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		_tmp7_ = self->priv->user;
		_tmp8_ = xdg_accounts_user_get_icon_file (_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = _tmp9_;
		_tmp0_ = g_strcmp0 (_tmp10_, "") == 0;
		_g_free0 (_tmp10_);
	}
	if (_tmp0_) {
		gchar* _tmp11_ = NULL;
		_tmp11_ = utils_get_icon_path ("avatar-default", 24);
		result = _tmp11_;
		return result;
	}
	_tmp12_ = self->priv->user;
	_tmp13_ = xdg_accounts_user_get_icon_file (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = _tmp14_;
	_tmp16_ = g_file_new_for_path (_tmp15_);
	_tmp17_ = _tmp16_;
	_g_free0 (_tmp15_);
	f = _tmp17_;
	_tmp18_ = f;
	_tmp19_ = g_file_query_exists (_tmp18_, NULL);
	if (_tmp19_) {
		XdgAccountsUser* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		_tmp20_ = self->priv->user;
		_tmp21_ = xdg_accounts_user_get_icon_file (_tmp20_);
		_tmp22_ = _tmp21_;
		result = _tmp22_;
		_g_object_unref0 (f);
		return result;
	} else {
		gchar* _tmp23_ = NULL;
		_tmp23_ = utils_get_icon_path ("avatar-default", 24);
		result = _tmp23_;
		_g_object_unref0 (f);
		return result;
	}
	_g_object_unref0 (f);
}


gchar* panel_user_get_real_name (PanelUser* self) {
	gchar* result;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	XdgAccountsUser* _tmp2_ = NULL;
	XdgAccountsUser* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp2_ = self->priv->user;
	if (_tmp2_ == NULL) {
		_tmp1_ = TRUE;
	} else {
		XdgAccountsUser* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp3_ = self->priv->user;
		_tmp4_ = xdg_accounts_user_get_real_name (_tmp3_);
		_tmp5_ = _tmp4_;
		_tmp6_ = _tmp5_;
		_tmp1_ = _tmp6_ == NULL;
		_g_free0 (_tmp6_);
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		XdgAccountsUser* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		_tmp7_ = self->priv->user;
		_tmp8_ = xdg_accounts_user_get_real_name (_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = _tmp9_;
		_tmp0_ = g_strcmp0 (_tmp10_, "") == 0;
		_g_free0 (_tmp10_);
	}
	if (_tmp0_) {
		const gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		_tmp11_ = g_get_user_name ();
		_tmp12_ = g_strdup (_tmp11_);
		result = _tmp12_;
		return result;
	}
	_tmp13_ = self->priv->user;
	_tmp14_ = xdg_accounts_user_get_real_name (_tmp13_);
	_tmp15_ = _tmp14_;
	result = _tmp15_;
	return result;
}


gchar* panel_user_get_host_name (PanelUser* self) {
	gchar* result;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_get_host_name ();
	_tmp1_ = g_strdup (_tmp0_);
	result = _tmp1_;
	return result;
}


static void value_panel_user_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_panel_user_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		panel_user_unref (value->data[0].v_pointer);
	}
}


static void value_panel_user_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = panel_user_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_panel_user_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_panel_user_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		PanelUser* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = panel_user_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_panel_user_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PanelUser** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = panel_user_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_panel_user (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecPanelUser* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_PANEL_USER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_panel_user (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_USER), NULL);
	return value->data[0].v_pointer;
}


void value_set_panel_user (GValue* value, gpointer v_object) {
	PanelUser* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_USER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PANEL_USER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		panel_user_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		panel_user_unref (old);
	}
}


void value_take_panel_user (GValue* value, gpointer v_object) {
	PanelUser* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_USER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PANEL_USER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		panel_user_unref (old);
	}
}


static void panel_user_class_init (PanelUserClass * klass) {
	panel_user_parent_class = g_type_class_peek_parent (klass);
	((PanelUserClass *) klass)->finalize = panel_user_finalize;
	g_type_class_add_private (klass, sizeof (PanelUserPrivate));
}


static void panel_user_instance_init (PanelUser * self) {
	self->priv = PANEL_USER_GET_PRIVATE (self);
	self->priv->user = NULL;
	self->priv->user_path = NULL;
	self->ref_count = 1;
}


static void panel_user_finalize (PanelUser* obj) {
	PanelUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_USER, PanelUser);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->user);
	_g_free0 (self->priv->user_path);
}


GType panel_user_get_type (void) {
	static volatile gsize panel_user_type_id__volatile = 0;
	if (g_once_init_enter (&panel_user_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_panel_user_init, value_panel_user_free_value, value_panel_user_copy_value, value_panel_user_peek_pointer, "p", value_panel_user_collect_value, "p", value_panel_user_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PanelUserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_user_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelUser), 0, (GInstanceInitFunc) panel_user_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType panel_user_type_id;
		panel_user_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PanelUser", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&panel_user_type_id__volatile, panel_user_type_id);
	}
	return panel_user_type_id__volatile;
}


gpointer panel_user_ref (gpointer instance) {
	PanelUser* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void panel_user_unref (gpointer instance) {
	PanelUser* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PANEL_USER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



