/* panel-animated-adjustment.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-animated-adjustment.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>


#define TYPE_PANEL_ANIMATED_ADJUSTMENT (panel_animated_adjustment_get_type ())
#define PANEL_ANIMATED_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_ANIMATED_ADJUSTMENT, PanelAnimatedAdjustment))
#define PANEL_ANIMATED_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_ANIMATED_ADJUSTMENT, PanelAnimatedAdjustmentClass))
#define IS_PANEL_ANIMATED_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_ANIMATED_ADJUSTMENT))
#define IS_PANEL_ANIMATED_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_ANIMATED_ADJUSTMENT))
#define PANEL_ANIMATED_ADJUSTMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_ANIMATED_ADJUSTMENT, PanelAnimatedAdjustmentClass))

typedef struct _PanelAnimatedAdjustment PanelAnimatedAdjustment;
typedef struct _PanelAnimatedAdjustmentClass PanelAnimatedAdjustmentClass;
typedef struct _PanelAnimatedAdjustmentPrivate PanelAnimatedAdjustmentPrivate;

struct _PanelAnimatedAdjustment {
	GtkAdjustment parent_instance;
	PanelAnimatedAdjustmentPrivate * priv;
};

struct _PanelAnimatedAdjustmentClass {
	GtkAdjustmentClass parent_class;
};

struct _PanelAnimatedAdjustmentPrivate {
	gdouble direction;
	gdouble target;
	gdouble target_delta;
	gdouble interpolated;
	gdouble duration;
	gdouble time;
	gdouble start_value;
};


static gpointer panel_animated_adjustment_parent_class = NULL;

GType panel_animated_adjustment_get_type (void) G_GNUC_CONST;
#define PANEL_ANIMATED_ADJUSTMENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_ANIMATED_ADJUSTMENT, PanelAnimatedAdjustmentPrivate))
enum  {
	PANEL_ANIMATED_ADJUSTMENT_DUMMY_PROPERTY
};
PanelAnimatedAdjustment* panel_animated_adjustment_new (gdouble value, gdouble lower, gdouble upper, gdouble step_increment, gdouble page_increment, gdouble page_size);
PanelAnimatedAdjustment* panel_animated_adjustment_construct (GType object_type, gdouble value, gdouble lower, gdouble upper, gdouble step_increment, gdouble page_increment, gdouble page_size);
void panel_animated_adjustment_set_duration (PanelAnimatedAdjustment* self, gint duration);
void panel_animated_adjustment_set_target (PanelAnimatedAdjustment* self, gdouble target);
void panel_animated_adjustment_start (PanelAnimatedAdjustment* self);
static gboolean panel_animated_adjustment_tween (PanelAnimatedAdjustment* self);
static gboolean _panel_animated_adjustment_tween_gsource_func (gpointer self);
gdouble panel_animated_adjustment_ease (PanelAnimatedAdjustment* self, gdouble t, gdouble b, gdouble c, gdouble d);
static void panel_animated_adjustment_finalize (GObject* obj);


PanelAnimatedAdjustment* panel_animated_adjustment_construct (GType object_type, gdouble value, gdouble lower, gdouble upper, gdouble step_increment, gdouble page_increment, gdouble page_size) {
	PanelAnimatedAdjustment * self = NULL;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
	self = (PanelAnimatedAdjustment*) g_object_new (object_type, NULL);
	_tmp0_ = value;
	gtk_adjustment_set_value ((GtkAdjustment*) self, _tmp0_);
	_tmp1_ = lower;
	gtk_adjustment_set_lower ((GtkAdjustment*) self, _tmp1_);
	_tmp2_ = upper;
	gtk_adjustment_set_upper ((GtkAdjustment*) self, _tmp2_);
	_tmp3_ = step_increment;
	gtk_adjustment_set_step_increment ((GtkAdjustment*) self, _tmp3_);
	_tmp4_ = page_increment;
	gtk_adjustment_set_page_increment ((GtkAdjustment*) self, _tmp4_);
	_tmp5_ = page_size;
	gtk_adjustment_set_page_size ((GtkAdjustment*) self, _tmp5_);
	return self;
}


PanelAnimatedAdjustment* panel_animated_adjustment_new (gdouble value, gdouble lower, gdouble upper, gdouble step_increment, gdouble page_increment, gdouble page_size) {
	return panel_animated_adjustment_construct (TYPE_PANEL_ANIMATED_ADJUSTMENT, value, lower, upper, step_increment, page_increment, page_size);
}


void panel_animated_adjustment_set_duration (PanelAnimatedAdjustment* self, gint duration) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = duration;
	self->priv->duration = (gdouble) _tmp0_;
}


void panel_animated_adjustment_set_target (PanelAnimatedAdjustment* self, gdouble target) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = target;
	self->priv->target = _tmp0_;
}


static gboolean _panel_animated_adjustment_tween_gsource_func (gpointer self) {
	gboolean result;
	result = panel_animated_adjustment_tween ((PanelAnimatedAdjustment*) self);
	return result;
}


void panel_animated_adjustment_start (PanelAnimatedAdjustment* self) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gint delta = 0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gint _tmp5_ = 0;
	g_return_if_fail (self != NULL);
	self->priv->time = (gdouble) 0;
	_tmp0_ = gtk_adjustment_get_value ((GtkAdjustment*) self);
	self->priv->start_value = _tmp0_;
	_tmp1_ = self->priv->target;
	_tmp2_ = self->priv->start_value;
	if (_tmp1_ > _tmp2_) {
		self->priv->direction = (gdouble) 1;
	} else {
		self->priv->direction = (gdouble) (-1);
	}
	_tmp3_ = self->priv->target;
	_tmp4_ = gtk_adjustment_get_value ((GtkAdjustment*) self);
	delta = (gint) (_tmp3_ - _tmp4_);
	_tmp5_ = abs (delta);
	self->priv->target_delta = (gdouble) _tmp5_;
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 16, _panel_animated_adjustment_tween_gsource_func, g_object_ref (self), g_object_unref);
}


gdouble panel_animated_adjustment_ease (PanelAnimatedAdjustment* self, gdouble t, gdouble b, gdouble c, gdouble d) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp8_ = 0.0;
	gdouble _tmp9_ = 0.0;
	gdouble _tmp10_ = 0.0;
	gdouble _tmp11_ = 0.0;
	gdouble _tmp12_ = 0.0;
	gdouble _tmp13_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = t;
	_tmp1_ = d;
	t = _tmp0_ / (_tmp1_ / 2);
	_tmp2_ = t;
	if (_tmp2_ < ((gdouble) 1)) {
		gdouble _tmp3_ = 0.0;
		gdouble _tmp4_ = 0.0;
		gdouble _tmp5_ = 0.0;
		gdouble _tmp6_ = 0.0;
		gdouble _tmp7_ = 0.0;
		_tmp3_ = c;
		_tmp4_ = t;
		_tmp5_ = t;
		_tmp6_ = t;
		_tmp7_ = b;
		result = ((((_tmp3_ / 2) * _tmp4_) * _tmp5_) * _tmp6_) + _tmp7_;
		return result;
	}
	_tmp8_ = c;
	_tmp9_ = t;
	t = _tmp9_ - 2;
	_tmp10_ = t;
	_tmp11_ = t;
	_tmp12_ = t;
	_tmp13_ = b;
	result = ((_tmp8_ / 2) * (((_tmp10_ * _tmp11_) * _tmp12_) + 2)) + _tmp13_;
	return result;
}


static gboolean panel_animated_adjustment_tween (PanelAnimatedAdjustment* self) {
	gboolean result = FALSE;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	gdouble _tmp8_ = 0.0;
	gdouble _tmp9_ = 0.0;
	gdouble _tmp17_ = 0.0;
	gdouble _tmp18_ = 0.0;
	gdouble _tmp19_ = 0.0;
	gdouble _tmp20_ = 0.0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->time;
	_tmp1_ = self->priv->start_value;
	_tmp2_ = self->priv->direction;
	_tmp3_ = self->priv->target_delta;
	_tmp4_ = self->priv->duration;
	_tmp5_ = panel_animated_adjustment_ease (self, _tmp0_, _tmp1_, _tmp2_ * _tmp3_, _tmp4_);
	self->priv->interpolated = _tmp5_;
	_tmp8_ = self->priv->interpolated;
	_tmp9_ = self->priv->target;
	if (_tmp8_ > _tmp9_) {
		gdouble _tmp10_ = 0.0;
		_tmp10_ = self->priv->direction;
		_tmp7_ = _tmp10_ == ((gdouble) 1);
	} else {
		_tmp7_ = FALSE;
	}
	if (_tmp7_) {
		_tmp6_ = TRUE;
	} else {
		gboolean _tmp11_ = FALSE;
		gdouble _tmp12_ = 0.0;
		gdouble _tmp13_ = 0.0;
		_tmp12_ = self->priv->interpolated;
		_tmp13_ = self->priv->target;
		if (_tmp12_ < _tmp13_) {
			gdouble _tmp14_ = 0.0;
			_tmp14_ = self->priv->direction;
			_tmp11_ = _tmp14_ == ((gdouble) (-1));
		} else {
			_tmp11_ = FALSE;
		}
		_tmp6_ = _tmp11_;
	}
	if (_tmp6_) {
		gdouble _tmp15_ = 0.0;
		gdouble _tmp16_ = 0.0;
		_tmp15_ = self->priv->target;
		self->priv->interpolated = _tmp15_;
		_tmp16_ = self->priv->interpolated;
		gtk_adjustment_set_value ((GtkAdjustment*) self, _tmp16_);
		g_signal_emit_by_name (self, "finished");
		result = FALSE;
		return result;
	}
	_tmp17_ = self->priv->time;
	_tmp18_ = self->priv->duration;
	if (_tmp17_ > _tmp18_) {
		self->priv->time = (gdouble) 0;
		g_signal_emit_by_name (self, "finished");
		result = FALSE;
		return result;
	}
	_tmp19_ = self->priv->time;
	self->priv->time = _tmp19_ + 16;
	_tmp20_ = self->priv->interpolated;
	gtk_adjustment_set_value ((GtkAdjustment*) self, _tmp20_);
	result = TRUE;
	return result;
}


static void panel_animated_adjustment_class_init (PanelAnimatedAdjustmentClass * klass) {
	panel_animated_adjustment_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PanelAnimatedAdjustmentPrivate));
	G_OBJECT_CLASS (klass)->finalize = panel_animated_adjustment_finalize;
	g_signal_new ("finished", TYPE_PANEL_ANIMATED_ADJUSTMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void panel_animated_adjustment_instance_init (PanelAnimatedAdjustment * self) {
	self->priv = PANEL_ANIMATED_ADJUSTMENT_GET_PRIVATE (self);
	self->priv->direction = (gdouble) 1;
	self->priv->target = (gdouble) 0;
	self->priv->target_delta = (gdouble) 0;
	self->priv->interpolated = (gdouble) 0;
	self->priv->duration = (gdouble) 200;
	self->priv->time = (gdouble) 0;
	self->priv->start_value = (gdouble) 0;
}


static void panel_animated_adjustment_finalize (GObject* obj) {
	PanelAnimatedAdjustment * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_ANIMATED_ADJUSTMENT, PanelAnimatedAdjustment);
	G_OBJECT_CLASS (panel_animated_adjustment_parent_class)->finalize (obj);
}


GType panel_animated_adjustment_get_type (void) {
	static volatile gsize panel_animated_adjustment_type_id__volatile = 0;
	if (g_once_init_enter (&panel_animated_adjustment_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelAnimatedAdjustmentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_animated_adjustment_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelAnimatedAdjustment), 0, (GInstanceInitFunc) panel_animated_adjustment_instance_init, NULL };
		GType panel_animated_adjustment_type_id;
		panel_animated_adjustment_type_id = g_type_register_static (GTK_TYPE_ADJUSTMENT, "PanelAnimatedAdjustment", &g_define_type_info, 0);
		g_once_init_leave (&panel_animated_adjustment_type_id__volatile, panel_animated_adjustment_type_id);
	}
	return panel_animated_adjustment_type_id__volatile;
}



