/* panel-desktop-html.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-desktop-html.vala, do not modify */

/*panel-desktop-html.vala*/

#include <glib.h>
#include <glib-object.h>
#include <webkit/webkit.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <config.h>
#include <JavaScriptCore/JavaScript.h>
#include <stdio.h>


#define TYPE_PANEL_DESKTOP_HTML (panel_desktop_html_get_type ())
#define PANEL_DESKTOP_HTML(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_DESKTOP_HTML, PanelDesktopHTML))
#define PANEL_DESKTOP_HTML_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_DESKTOP_HTML, PanelDesktopHTMLClass))
#define IS_PANEL_DESKTOP_HTML(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_DESKTOP_HTML))
#define IS_PANEL_DESKTOP_HTML_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_DESKTOP_HTML))
#define PANEL_DESKTOP_HTML_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_DESKTOP_HTML, PanelDesktopHTMLClass))

typedef struct _PanelDesktopHTML PanelDesktopHTML;
typedef struct _PanelDesktopHTMLClass PanelDesktopHTMLClass;
typedef struct _PanelDesktopHTMLPrivate PanelDesktopHTMLPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _JSStringRelease0(var) ((var == NULL) ? NULL : (var = (JSStringRelease (var), NULL)))

struct _PanelDesktopHTML {
	WebKitWebView parent_instance;
	PanelDesktopHTMLPrivate * priv;
};

struct _PanelDesktopHTMLClass {
	WebKitWebViewClass parent_class;
};

struct _PanelDesktopHTMLPrivate {
	GSettings* gsettings;
};


static gpointer panel_desktop_html_parent_class = NULL;

GType panel_desktop_html_get_type (void) G_GNUC_CONST;
#define PANEL_DESKTOP_HTML_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_DESKTOP_HTML, PanelDesktopHTMLPrivate))
enum  {
	PANEL_DESKTOP_HTML_DUMMY_PROPERTY
};
static gchar* panel_desktop_html_translate_uri (PanelDesktopHTML* self, const gchar* old);
PanelDesktopHTML* panel_desktop_html_new (void);
PanelDesktopHTML* panel_desktop_html_construct (GType object_type);
static void __lambda20_ (PanelDesktopHTML* self);
static gboolean panel_desktop_html_setBackground (PanelDesktopHTML* self);
static void ___lambda20__g_settings_changed (GSettings* _sender, const gchar* key, gpointer self);
static void __lambda21_ (PanelDesktopHTML* self, WebKitWebFrame* frame, WebKitWebResource* resource, WebKitNetworkRequest* request, WebKitNetworkResponse* response);
static void ___lambda21__webkit_web_view_resource_request_starting (WebKitWebView* _sender, WebKitWebFrame* p0, WebKitWebResource* p1, WebKitNetworkRequest* p2, WebKitNetworkResponse* p3, gpointer self);
static void __lambda22_ (PanelDesktopHTML* self, WebKitWebFrame* frame, void* context);
void panel_desktop_data_setup_js_class (void* context);
void utils_setup_js_class (void* context);
static void ___lambda22__webkit_web_view_window_object_cleared (WebKitWebView* _sender, WebKitWebFrame* frame, void* context, void* window_object, gpointer self);
static gboolean _panel_desktop_html_setBackground_gsource_func (gpointer self);
void panel_desktop_html_updateSize (PanelDesktopHTML* self);
static void panel_desktop_html_finalize (GObject* obj);


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch28_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = regex;
		_tmp7_ = replacement;
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) (-1), 0, _tmp7_, 0, &_inner_error_);
		_tmp5_ = _tmp8_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch28_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp5_;
		_tmp5_ = NULL;
		result = _tmp9_;
		_g_free0 (_tmp5_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally28;
	__catch28_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally28:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gchar* panel_desktop_html_translate_uri (PanelDesktopHTML* self, const gchar* old) {
	gchar* result = NULL;
	gchar* uri = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	_tmp0_ = old;
	_tmp1_ = string_replace (_tmp0_, "http://system", "file://" SYSTEM_PATH "/");
	uri = _tmp1_;
	result = uri;
	return result;
}


static void __lambda20_ (PanelDesktopHTML* self) {
	panel_desktop_html_setBackground (self);
}


static void ___lambda20__g_settings_changed (GSettings* _sender, const gchar* key, gpointer self) {
	__lambda20_ ((PanelDesktopHTML*) self);
}


static void __lambda21_ (PanelDesktopHTML* self, WebKitWebFrame* frame, WebKitWebResource* resource, WebKitNetworkRequest* request, WebKitNetworkResponse* response) {
	gchar* uri = NULL;
	WebKitWebResource* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	WebKitNetworkRequest* _tmp4_ = NULL;
	g_return_if_fail (frame != NULL);
	g_return_if_fail (resource != NULL);
	g_return_if_fail (request != NULL);
	_tmp0_ = resource;
	_tmp1_ = webkit_web_resource_get_uri (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = panel_desktop_html_translate_uri (self, _tmp2_);
	uri = _tmp3_;
	_tmp4_ = request;
	webkit_network_request_set_uri (_tmp4_, uri);
	_g_free0 (uri);
}


static void ___lambda21__webkit_web_view_resource_request_starting (WebKitWebView* _sender, WebKitWebFrame* p0, WebKitWebResource* p1, WebKitNetworkRequest* p2, WebKitNetworkResponse* p3, gpointer self) {
	__lambda21_ ((PanelDesktopHTML*) self, p0, p1, p2, p3);
}


static void __lambda22_ (PanelDesktopHTML* self, WebKitWebFrame* frame, void* context) {
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	g_return_if_fail (frame != NULL);
	_tmp0_ = context;
	panel_desktop_data_setup_js_class ((void*) _tmp0_);
	_tmp1_ = context;
	utils_setup_js_class ((void*) _tmp1_);
	panel_desktop_html_setBackground (self);
}


static void ___lambda22__webkit_web_view_window_object_cleared (WebKitWebView* _sender, WebKitWebFrame* frame, void* context, void* window_object, gpointer self) {
	__lambda22_ ((PanelDesktopHTML*) self, frame, context);
}


PanelDesktopHTML* panel_desktop_html_construct (GType object_type) {
	PanelDesktopHTML * self = NULL;
	GSettings* _tmp0_ = NULL;
	GSettings* _tmp1_ = NULL;
	WebKitWebSettings* settings = NULL;
	WebKitWebSettings* _tmp2_ = NULL;
	WebKitWebSettings* _tmp3_ = NULL;
	WebKitWebSettings* _tmp4_ = NULL;
	WebKitWebSettings* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	WebKitWebSettings* _tmp8_ = NULL;
	self = (PanelDesktopHTML*) g_object_new (object_type, NULL);
	webkit_web_view_set_transparent ((WebKitWebView*) self, TRUE);
	_tmp0_ = g_settings_new ("org.gnome.desktop.background");
	_g_object_unref0 (self->priv->gsettings);
	self->priv->gsettings = _tmp0_;
	_tmp1_ = self->priv->gsettings;
	g_signal_connect_object (_tmp1_, "changed::picture-uri", (GCallback) ___lambda20__g_settings_changed, self, 0);
	_tmp2_ = webkit_web_settings_new ();
	settings = _tmp2_;
	_tmp3_ = settings;
	g_object_set (_tmp3_, "enable-file-access-from-file-uris", TRUE, NULL);
	_tmp4_ = settings;
	g_object_set (_tmp4_, "enable-universal-access-from-file-uris", TRUE, NULL);
	_tmp5_ = settings;
	g_object_set (_tmp5_, "javascript-can-open-windows-automatically", TRUE, NULL);
	_tmp6_ = g_getenv ("MANOKWARI_DEBUG");
	if (_tmp6_ == NULL) {
		WebKitWebSettings* _tmp7_ = NULL;
		_tmp7_ = settings;
		g_object_set (_tmp7_, "enable-default-context-menu", FALSE, NULL);
	}
	_tmp8_ = settings;
	webkit_web_view_set_settings ((WebKitWebView*) self, _tmp8_);
	g_signal_connect_object ((WebKitWebView*) self, "resource-request-starting", (GCallback) ___lambda21__webkit_web_view_resource_request_starting, self, 0);
	g_signal_connect_object ((WebKitWebView*) self, "window-object-cleared", (GCallback) ___lambda22__webkit_web_view_window_object_cleared, self, 0);
	webkit_web_view_load_uri ((WebKitWebView*) self, "http://system/desktop.html");
	_g_object_unref0 (settings);
	return self;
}


PanelDesktopHTML* panel_desktop_html_new (void) {
	return panel_desktop_html_construct (TYPE_PANEL_DESKTOP_HTML);
}


static gboolean _panel_desktop_html_setBackground_gsource_func (gpointer self) {
	gboolean result;
	result = panel_desktop_html_setBackground ((PanelDesktopHTML*) self);
	return result;
}


static gboolean panel_desktop_html_setBackground (PanelDesktopHTML* self) {
	gboolean result = FALSE;
	gchar* uri = NULL;
	GSettings* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	void* context = NULL;
	WebKitWebFrame* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* s = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	void* _tmp9_ = NULL;
	void* _tmp10_ = NULL;
	void* r = NULL;
	void* _tmp11_ = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	gboolean _tmp16_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->gsettings;
	_tmp1_ = g_settings_get_string (_tmp0_, "picture-uri");
	uri = _tmp1_;
	_tmp2_ = webkit_web_view_get_focused_frame ((WebKitWebView*) self);
	_tmp3_ = webkit_web_frame_get_global_context (_tmp2_);
	context = _tmp3_;
	_tmp4_ = uri;
	_tmp5_ = g_strconcat ("desktop.setBackground('", _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strconcat (_tmp6_, "')", NULL);
	_tmp8_ = _tmp7_;
	_tmp9_ = JSStringCreateWithUTF8CString (_tmp8_);
	_tmp10_ = _tmp9_;
	_g_free0 (_tmp8_);
	_g_free0 (_tmp6_);
	s = _tmp10_;
	_tmp11_ = context;
	_tmp12_ = s;
	_tmp13_ = JSEvaluateScript (_tmp11_, _tmp12_, NULL, NULL, 0, NULL);
	r = _tmp13_;
	_tmp14_ = r;
	_tmp15_ = context;
	_tmp16_ = JSValueIsBoolean (_tmp15_, _tmp14_);
	if (!_tmp16_) {
		g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, _panel_desktop_html_setBackground_gsource_func, g_object_ref (self), g_object_unref);
	}
	result = FALSE;
	_0 (r);
	_JSStringRelease0 (s);
	_g_free0 (uri);
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void panel_desktop_html_updateSize (PanelDesktopHTML* self) {
	WebKitViewportAttributes* attributes = NULL;
	WebKitViewportAttributes* _tmp0_ = NULL;
	WebKitViewportAttributes* _tmp1_ = NULL;
	FILE* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = webkit_web_view_get_viewport_attributes ((WebKitWebView*) self);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	attributes = _tmp1_;
	_tmp2_ = stderr;
	fprintf (_tmp2_, "iii -->\n");
	webkit_viewport_attributes_recompute (attributes);
	_g_object_unref0 (attributes);
}


static void panel_desktop_html_class_init (PanelDesktopHTMLClass * klass) {
	panel_desktop_html_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PanelDesktopHTMLPrivate));
	G_OBJECT_CLASS (klass)->finalize = panel_desktop_html_finalize;
}


static void panel_desktop_html_instance_init (PanelDesktopHTML * self) {
	self->priv = PANEL_DESKTOP_HTML_GET_PRIVATE (self);
	self->priv->gsettings = NULL;
}


static void panel_desktop_html_finalize (GObject* obj) {
	PanelDesktopHTML * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_DESKTOP_HTML, PanelDesktopHTML);
	_g_object_unref0 (self->priv->gsettings);
	G_OBJECT_CLASS (panel_desktop_html_parent_class)->finalize (obj);
}


GType panel_desktop_html_get_type (void) {
	static volatile gsize panel_desktop_html_type_id__volatile = 0;
	if (g_once_init_enter (&panel_desktop_html_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelDesktopHTMLClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_desktop_html_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelDesktopHTML), 0, (GInstanceInitFunc) panel_desktop_html_instance_init, NULL };
		GType panel_desktop_html_type_id;
		panel_desktop_html_type_id = g_type_register_static (WEBKIT_TYPE_WEB_VIEW, "PanelDesktopHTML", &g_define_type_info, 0);
		g_once_init_leave (&panel_desktop_html_type_id__volatile, panel_desktop_html_type_id);
	}
	return panel_desktop_html_type_id__volatile;
}



