/* panel-screen.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-screen.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



void panel_screen_get_primary_monitor_geometry (GdkRectangle* result);
void panel_screen_move_window (GtkWindow* window, GdkGravity gravity);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void panel_screen_get_primary_monitor_geometry (GdkRectangle* result) {
	GdkRectangle r = {0};
	GdkRectangle _tmp0_ = {0};
	GdkScreen* screen = NULL;
	GdkScreen* _tmp1_ = NULL;
	GdkScreen* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GdkRectangle _tmp4_ = {0};
	_tmp0_.x = 0;
	_tmp0_.y = 0;
	r = _tmp0_;
	_tmp1_ = gdk_screen_get_default ();
	_tmp2_ = _g_object_ref0 (_tmp1_);
	screen = _tmp2_;
	_tmp3_ = gdk_screen_get_primary_monitor (screen);
	gdk_screen_get_monitor_geometry (screen, _tmp3_, &_tmp4_);
	r = _tmp4_;
	*result = r;
	_g_object_unref0 (screen);
	return;
}


void panel_screen_move_window (GtkWindow* window, GdkGravity gravity) {
	gint x = 0;
	gint y = 0;
	GtkRequisition min = {0};
	GtkRequisition _tmp0_ = {0};
	GtkRequisition natural = {0};
	GtkRequisition _tmp1_ = {0};
	GdkRectangle monitor = {0};
	GdkRectangle _tmp2_ = {0};
	GtkWindow* _tmp3_ = NULL;
	GtkRequisition _tmp4_ = {0};
	GtkRequisition _tmp5_ = {0};
	GdkGravity _tmp6_ = 0;
	gint _tmp57_ = 0;
	GdkRectangle _tmp58_ = {0};
	gint _tmp59_ = 0;
	gint _tmp60_ = 0;
	GdkRectangle _tmp61_ = {0};
	gint _tmp62_ = 0;
	GtkWindow* _tmp63_ = NULL;
	gint _tmp64_ = 0;
	gint _tmp65_ = 0;
	g_return_if_fail (window != NULL);
	_tmp0_.width = 0;
	_tmp0_.height = 0;
	min = _tmp0_;
	_tmp1_.width = 0;
	_tmp1_.height = 0;
	natural = _tmp1_;
	panel_screen_get_primary_monitor_geometry (&_tmp2_);
	monitor = _tmp2_;
	_tmp3_ = window;
	gtk_widget_get_preferred_size ((GtkWidget*) _tmp3_, &_tmp4_, &_tmp5_);
	min = _tmp4_;
	natural = _tmp5_;
	_tmp6_ = gravity;
	switch (_tmp6_) {
		case GDK_GRAVITY_NORTH_WEST:
		{
			gint _tmp7_ = 0;
			y = 0;
			_tmp7_ = y;
			x = _tmp7_;
			break;
		}
		case GDK_GRAVITY_NORTH:
		{
			GdkRectangle _tmp8_ = {0};
			gint _tmp9_ = 0;
			GtkRequisition _tmp10_ = {0};
			gint _tmp11_ = 0;
			y = 0;
			_tmp8_ = monitor;
			_tmp9_ = _tmp8_.width;
			_tmp10_ = min;
			_tmp11_ = _tmp10_.width;
			x = (_tmp9_ / 2) - (_tmp11_ / 2);
			break;
		}
		case GDK_GRAVITY_NORTH_EAST:
		{
			GdkRectangle _tmp12_ = {0};
			gint _tmp13_ = 0;
			GtkRequisition _tmp14_ = {0};
			gint _tmp15_ = 0;
			y = 0;
			_tmp12_ = monitor;
			_tmp13_ = _tmp12_.width;
			_tmp14_ = min;
			_tmp15_ = _tmp14_.width;
			x = _tmp13_ - _tmp15_;
			break;
		}
		case GDK_GRAVITY_WEST:
		{
			GdkRectangle _tmp16_ = {0};
			gint _tmp17_ = 0;
			GtkRequisition _tmp18_ = {0};
			gint _tmp19_ = 0;
			x = 0;
			_tmp16_ = monitor;
			_tmp17_ = _tmp16_.height;
			_tmp18_ = min;
			_tmp19_ = _tmp18_.height;
			y = (_tmp17_ / 2) - (_tmp19_ / 2);
			break;
		}
		case GDK_GRAVITY_CENTER:
		{
			GdkRectangle _tmp20_ = {0};
			gint _tmp21_ = 0;
			GtkRequisition _tmp22_ = {0};
			gint _tmp23_ = 0;
			GdkRectangle _tmp24_ = {0};
			gint _tmp25_ = 0;
			GtkRequisition _tmp26_ = {0};
			gint _tmp27_ = 0;
			_tmp20_ = monitor;
			_tmp21_ = _tmp20_.width;
			_tmp22_ = min;
			_tmp23_ = _tmp22_.width;
			x = (_tmp21_ / 2) - (_tmp23_ / 2);
			_tmp24_ = monitor;
			_tmp25_ = _tmp24_.height;
			_tmp26_ = min;
			_tmp27_ = _tmp26_.height;
			y = (_tmp25_ / 2) - (_tmp27_ / 2);
			break;
		}
		case GDK_GRAVITY_EAST:
		{
			GdkRectangle _tmp28_ = {0};
			gint _tmp29_ = 0;
			GtkRequisition _tmp30_ = {0};
			gint _tmp31_ = 0;
			GdkRectangle _tmp32_ = {0};
			gint _tmp33_ = 0;
			GtkRequisition _tmp34_ = {0};
			gint _tmp35_ = 0;
			_tmp28_ = monitor;
			_tmp29_ = _tmp28_.width;
			_tmp30_ = min;
			_tmp31_ = _tmp30_.width;
			x = _tmp29_ - _tmp31_;
			_tmp32_ = monitor;
			_tmp33_ = _tmp32_.height;
			_tmp34_ = min;
			_tmp35_ = _tmp34_.height;
			y = (_tmp33_ / 2) - (_tmp35_ / 2);
			break;
		}
		case GDK_GRAVITY_SOUTH_WEST:
		{
			GdkRectangle _tmp36_ = {0};
			gint _tmp37_ = 0;
			GtkRequisition _tmp38_ = {0};
			gint _tmp39_ = 0;
			x = 0;
			_tmp36_ = monitor;
			_tmp37_ = _tmp36_.height;
			_tmp38_ = min;
			_tmp39_ = _tmp38_.height;
			y = _tmp37_ - _tmp39_;
			break;
		}
		case GDK_GRAVITY_SOUTH:
		{
			GdkRectangle _tmp40_ = {0};
			gint _tmp41_ = 0;
			GtkRequisition _tmp42_ = {0};
			gint _tmp43_ = 0;
			GdkRectangle _tmp44_ = {0};
			gint _tmp45_ = 0;
			GtkRequisition _tmp46_ = {0};
			gint _tmp47_ = 0;
			_tmp40_ = monitor;
			_tmp41_ = _tmp40_.width;
			_tmp42_ = min;
			_tmp43_ = _tmp42_.width;
			x = (_tmp41_ / 2) - (_tmp43_ / 2);
			_tmp44_ = monitor;
			_tmp45_ = _tmp44_.height;
			_tmp46_ = min;
			_tmp47_ = _tmp46_.height;
			y = _tmp45_ - _tmp47_;
			break;
		}
		case GDK_GRAVITY_SOUTH_EAST:
		{
			GdkRectangle _tmp48_ = {0};
			gint _tmp49_ = 0;
			GtkRequisition _tmp50_ = {0};
			gint _tmp51_ = 0;
			GdkRectangle _tmp52_ = {0};
			gint _tmp53_ = 0;
			GtkRequisition _tmp54_ = {0};
			gint _tmp55_ = 0;
			_tmp48_ = monitor;
			_tmp49_ = _tmp48_.width;
			_tmp50_ = min;
			_tmp51_ = _tmp50_.width;
			x = _tmp49_ - _tmp51_;
			_tmp52_ = monitor;
			_tmp53_ = _tmp52_.height;
			_tmp54_ = min;
			_tmp55_ = _tmp54_.height;
			y = _tmp53_ - _tmp55_;
			break;
		}
		default:
		case GDK_GRAVITY_STATIC:
		{
			gint _tmp56_ = 0;
			y = 0;
			_tmp56_ = y;
			x = _tmp56_;
			break;
		}
	}
	_tmp57_ = x;
	_tmp58_ = monitor;
	_tmp59_ = _tmp58_.x;
	x = _tmp57_ + _tmp59_;
	_tmp60_ = y;
	_tmp61_ = monitor;
	_tmp62_ = _tmp61_.y;
	y = _tmp60_ + _tmp62_;
	_tmp63_ = window;
	_tmp64_ = x;
	_tmp65_ = y;
	gtk_window_move (_tmp63_, _tmp64_, _tmp65_);
}



