/* panel-desktop.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-desktop.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <webkit/webkit.h>
#include <gdk/gdk.h>
#include <string.h>
#include <stdio.h>


#define TYPE_PANEL_ABSTRACT_WINDOW (panel_abstract_window_get_type ())
#define PANEL_ABSTRACT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_ABSTRACT_WINDOW, PanelAbstractWindow))
#define PANEL_ABSTRACT_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_ABSTRACT_WINDOW, PanelAbstractWindowClass))
#define IS_PANEL_ABSTRACT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_ABSTRACT_WINDOW))
#define IS_PANEL_ABSTRACT_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_ABSTRACT_WINDOW))
#define PANEL_ABSTRACT_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_ABSTRACT_WINDOW, PanelAbstractWindowClass))

typedef struct _PanelAbstractWindow PanelAbstractWindow;
typedef struct _PanelAbstractWindowClass PanelAbstractWindowClass;
typedef struct _PanelAbstractWindowPrivate PanelAbstractWindowPrivate;

#define TYPE_PANEL_DESKTOP (panel_desktop_get_type ())
#define PANEL_DESKTOP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_DESKTOP, PanelDesktop))
#define PANEL_DESKTOP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_DESKTOP, PanelDesktopClass))
#define IS_PANEL_DESKTOP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_DESKTOP))
#define IS_PANEL_DESKTOP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_DESKTOP))
#define PANEL_DESKTOP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_DESKTOP, PanelDesktopClass))

typedef struct _PanelDesktop PanelDesktop;
typedef struct _PanelDesktopClass PanelDesktopClass;
typedef struct _PanelDesktopPrivate PanelDesktopPrivate;

#define TYPE_PANEL_DESKTOP_HTML (panel_desktop_html_get_type ())
#define PANEL_DESKTOP_HTML(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_DESKTOP_HTML, PanelDesktopHTML))
#define PANEL_DESKTOP_HTML_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_DESKTOP_HTML, PanelDesktopHTMLClass))
#define IS_PANEL_DESKTOP_HTML(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_DESKTOP_HTML))
#define IS_PANEL_DESKTOP_HTML_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_DESKTOP_HTML))
#define PANEL_DESKTOP_HTML_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_DESKTOP_HTML, PanelDesktopHTMLClass))

typedef struct _PanelDesktopHTML PanelDesktopHTML;
typedef struct _PanelDesktopHTMLClass PanelDesktopHTMLClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _PanelAbstractWindow {
	GtkWindow parent_instance;
	PanelAbstractWindowPrivate * priv;
};

struct _PanelAbstractWindowClass {
	GtkWindowClass parent_class;
};

struct _PanelDesktop {
	PanelAbstractWindow parent_instance;
	PanelDesktopPrivate * priv;
};

struct _PanelDesktopClass {
	PanelAbstractWindowClass parent_class;
};

struct _PanelDesktopPrivate {
	PanelDesktopHTML* desktop;
};


static gpointer panel_desktop_parent_class = NULL;

GType panel_abstract_window_get_type (void) G_GNUC_CONST;
GType panel_desktop_get_type (void) G_GNUC_CONST;
GType panel_desktop_html_get_type (void) G_GNUC_CONST;
#define PANEL_DESKTOP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_DESKTOP, PanelDesktopPrivate))
enum  {
	PANEL_DESKTOP_DUMMY_PROPERTY
};
PanelDesktop* panel_desktop_new (void);
PanelDesktop* panel_desktop_construct (GType object_type);
PanelAbstractWindow* panel_abstract_window_new (void);
PanelAbstractWindow* panel_abstract_window_construct (GType object_type);
PanelDesktopHTML* panel_desktop_html_new (void);
PanelDesktopHTML* panel_desktop_html_construct (GType object_type);
static gboolean __lambda28_ (PanelDesktop* self);
static gboolean ___lambda28__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void __lambda29_ (PanelDesktop* self);
static void panel_desktop_resize_geometry (PanelDesktop* self);
static void ___lambda29__gdk_screen_size_changed (GdkScreen* _sender, gpointer self);
static void __lambda30_ (PanelDesktop* self);
static void ___lambda30__gdk_screen_monitors_changed (GdkScreen* _sender, gpointer self);
void panel_screen_move_window (GtkWindow* window, GdkGravity gravity);
void panel_desktop_html_updateSize (PanelDesktopHTML* self);
static void panel_desktop_real_get_preferred_width (GtkWidget* base, gint* min, gint* max);
void panel_screen_get_primary_monitor_geometry (GdkRectangle* result);
static void panel_desktop_real_get_preferred_height (GtkWidget* base, gint* min, gint* max);
static void panel_desktop_finalize (GObject* obj);


static gboolean __lambda28_ (PanelDesktop* self) {
	gboolean result = FALSE;
	g_signal_emit_by_name (self, "desktop-clicked");
	result = FALSE;
	return result;
}


static gboolean ___lambda28__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda28_ ((PanelDesktop*) self);
	return result;
}


static void __lambda29_ (PanelDesktop* self) {
	panel_desktop_resize_geometry (self);
}


static void ___lambda29__gdk_screen_size_changed (GdkScreen* _sender, gpointer self) {
	__lambda29_ ((PanelDesktop*) self);
}


static void __lambda30_ (PanelDesktop* self) {
	panel_desktop_resize_geometry (self);
}


static void ___lambda30__gdk_screen_monitors_changed (GdkScreen* _sender, gpointer self) {
	__lambda30_ ((PanelDesktop*) self);
}


PanelDesktop* panel_desktop_construct (GType object_type) {
	PanelDesktop * self = NULL;
	GdkScreen* _tmp0_ = NULL;
	GdkScreen* _tmp1_ = NULL;
	GdkVisual* _tmp2_ = NULL;
	GdkRGBA c = {0};
	GdkRGBA _tmp3_ = {0};
	PanelDesktopHTML* _tmp4_ = NULL;
	PanelDesktopHTML* _tmp5_ = NULL;
	PanelDesktopHTML* _tmp6_ = NULL;
	PanelDesktopHTML* _tmp7_ = NULL;
	GdkScreen* _tmp8_ = NULL;
	GdkScreen* _tmp9_ = NULL;
	GdkScreen* _tmp10_ = NULL;
	GdkScreen* _tmp11_ = NULL;
	self = (PanelDesktop*) panel_abstract_window_construct (object_type);
	_tmp0_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = gdk_screen_get_rgba_visual (_tmp1_);
	gtk_widget_set_visual ((GtkWidget*) self, _tmp2_);
	memset (&c, 0, sizeof (GdkRGBA));
	c.red = 0.0;
	c.blue = 0.0;
	c.green = 0.0;
	c.alpha = 0.0;
	_tmp3_ = c;
	gtk_widget_override_background_color ((GtkWidget*) self, GTK_STATE_FLAG_NORMAL, &_tmp3_);
	gtk_widget_set_app_paintable ((GtkWidget*) self, TRUE);
	_tmp4_ = panel_desktop_html_new ();
	g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->priv->desktop);
	self->priv->desktop = _tmp4_;
	_tmp5_ = self->priv->desktop;
	gtk_widget_show ((GtkWidget*) _tmp5_);
	gtk_window_set_type_hint ((GtkWindow*) self, GDK_WINDOW_TYPE_HINT_DESKTOP);
	_tmp6_ = self->priv->desktop;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp6_);
	gtk_widget_queue_resize ((GtkWidget*) self);
	gtk_window_move ((GtkWindow*) self, 0, 0);
	gtk_widget_show_all ((GtkWidget*) self);
	_tmp7_ = self->priv->desktop;
	g_signal_connect_object ((GtkWidget*) _tmp7_, "button-press-event", (GCallback) ___lambda28__gtk_widget_button_press_event, self, 0);
	_tmp8_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp9_ = _tmp8_;
	g_signal_connect_object (_tmp9_, "size-changed", (GCallback) ___lambda29__gdk_screen_size_changed, self, 0);
	_tmp10_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp11_ = _tmp10_;
	g_signal_connect_object (_tmp11_, "monitors-changed", (GCallback) ___lambda30__gdk_screen_monitors_changed, self, 0);
	return self;
}


PanelDesktop* panel_desktop_new (void) {
	return panel_desktop_construct (TYPE_PANEL_DESKTOP);
}


static void panel_desktop_resize_geometry (PanelDesktop* self) {
	PanelDesktopHTML* _tmp0_ = NULL;
	FILE* _tmp1_ = NULL;
	GdkScreen* _tmp2_ = NULL;
	GdkScreen* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	GdkScreen* _tmp5_ = NULL;
	GdkScreen* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	g_return_if_fail (self != NULL);
	panel_screen_move_window ((GtkWindow*) self, GDK_GRAVITY_NORTH_EAST);
	gtk_widget_queue_resize ((GtkWidget*) self);
	_tmp0_ = self->priv->desktop;
	panel_desktop_html_updateSize (_tmp0_);
	_tmp1_ = stderr;
	_tmp2_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp3_ = _tmp2_;
	_tmp4_ = gdk_screen_width ();
	_tmp5_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp6_ = _tmp5_;
	_tmp7_ = gdk_screen_height ();
	fprintf (_tmp1_, "iii %d %d <--\n", _tmp4_, _tmp7_);
}


static void panel_desktop_real_get_preferred_width (GtkWidget* base, gint* min, gint* max) {
	PanelDesktop * self;
	gint _vala_min = 0;
	gint _vala_max = 0;
	gint r = 0;
	GdkRectangle _tmp0_ = {0};
	gint _tmp1_ = 0;
	self = (PanelDesktop*) base;
	panel_screen_get_primary_monitor_geometry (&_tmp0_);
	_tmp1_ = _tmp0_.width;
	r = _tmp1_;
	_vala_max = r;
	_vala_min = _vala_max;
	if (min) {
		*min = _vala_min;
	}
	if (max) {
		*max = _vala_max;
	}
}


static void panel_desktop_real_get_preferred_height (GtkWidget* base, gint* min, gint* max) {
	PanelDesktop * self;
	gint _vala_min = 0;
	gint _vala_max = 0;
	gint r = 0;
	GdkRectangle _tmp0_ = {0};
	gint _tmp1_ = 0;
	self = (PanelDesktop*) base;
	panel_screen_get_primary_monitor_geometry (&_tmp0_);
	_tmp1_ = _tmp0_.height;
	r = _tmp1_;
	_vala_max = r;
	_vala_min = _vala_max;
	if (min) {
		*min = _vala_min;
	}
	if (max) {
		*max = _vala_max;
	}
}


static void panel_desktop_class_init (PanelDesktopClass * klass) {
	panel_desktop_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PanelDesktopPrivate));
	((GtkWidgetClass *) klass)->get_preferred_width = panel_desktop_real_get_preferred_width;
	((GtkWidgetClass *) klass)->get_preferred_height = panel_desktop_real_get_preferred_height;
	G_OBJECT_CLASS (klass)->finalize = panel_desktop_finalize;
	g_signal_new ("desktop_clicked", TYPE_PANEL_DESKTOP, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void panel_desktop_instance_init (PanelDesktop * self) {
	self->priv = PANEL_DESKTOP_GET_PRIVATE (self);
}


static void panel_desktop_finalize (GObject* obj) {
	PanelDesktop * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_DESKTOP, PanelDesktop);
	_g_object_unref0 (self->priv->desktop);
	G_OBJECT_CLASS (panel_desktop_parent_class)->finalize (obj);
}


GType panel_desktop_get_type (void) {
	static volatile gsize panel_desktop_type_id__volatile = 0;
	if (g_once_init_enter (&panel_desktop_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelDesktopClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_desktop_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelDesktop), 0, (GInstanceInitFunc) panel_desktop_instance_init, NULL };
		GType panel_desktop_type_id;
		panel_desktop_type_id = g_type_register_static (TYPE_PANEL_ABSTRACT_WINDOW, "PanelDesktop", &g_define_type_info, 0);
		g_once_init_leave (&panel_desktop_type_id__volatile, panel_desktop_type_id);
	}
	return panel_desktop_type_id__volatile;
}



