/* panel-item.c generated by valac 0.26.1, the Vala compiler
 * generated from panel-item.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <gio/gdesktopappinfo.h>
#include <gio/gio.h>
#include <cairo.h>
#include <float.h>
#include <math.h>


#define TYPE_PANEL_EXPANDER_ITEM (panel_expander_item_get_type ())
#define PANEL_EXPANDER_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_EXPANDER_ITEM, PanelExpanderItem))
#define PANEL_EXPANDER_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_EXPANDER_ITEM, PanelExpanderItemClass))
#define IS_PANEL_EXPANDER_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_EXPANDER_ITEM))
#define IS_PANEL_EXPANDER_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_EXPANDER_ITEM))
#define PANEL_EXPANDER_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_EXPANDER_ITEM, PanelExpanderItemClass))

typedef struct _PanelExpanderItem PanelExpanderItem;
typedef struct _PanelExpanderItemClass PanelExpanderItemClass;
typedef struct _PanelExpanderItemPrivate PanelExpanderItemPrivate;

#define TYPE_PANEL_ITEM (panel_item_get_type ())
#define PANEL_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_ITEM, PanelItem))
#define PANEL_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_ITEM, PanelItemClass))
#define IS_PANEL_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_ITEM))
#define IS_PANEL_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_ITEM))
#define PANEL_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_ITEM, PanelItemClass))

typedef struct _PanelItem PanelItem;
typedef struct _PanelItemClass PanelItemClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _PanelItemPrivate PanelItemPrivate;

struct _PanelExpanderItem {
	GtkExpander parent_instance;
	PanelExpanderItemPrivate * priv;
};

struct _PanelExpanderItemClass {
	GtkExpanderClass parent_class;
};

struct _PanelExpanderItemPrivate {
	PanelItem* item;
};

struct _PanelItem {
	GtkBox parent_instance;
	PanelItemPrivate * priv;
};

struct _PanelItemClass {
	GtkBoxClass parent_class;
};

struct _PanelItemPrivate {
	GtkHBox* box;
	GDesktopAppInfo* info;
	GtkEventBox* event_box;
	GtkLabel* label;
	GtkImage* image;
	GtkSettings* settings;
	gint MARGIN;
	gboolean pressed;
};


static gpointer panel_expander_item_parent_class = NULL;
static gpointer panel_item_parent_class = NULL;

GType panel_expander_item_get_type (void) G_GNUC_CONST;
GType panel_item_get_type (void) G_GNUC_CONST;
#define PANEL_EXPANDER_ITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_EXPANDER_ITEM, PanelExpanderItemPrivate))
enum  {
	PANEL_EXPANDER_ITEM_DUMMY_PROPERTY
};
PanelExpanderItem* panel_expander_item_new (const gchar* title, const gchar* icon);
PanelExpanderItem* panel_expander_item_construct (GType object_type, const gchar* title, const gchar* icon);
PanelItem* panel_item_new_with_label (const gchar* title);
PanelItem* panel_item_construct_with_label (GType object_type, const gchar* title);
void panel_item_set_image (PanelItem* self, const gchar* image_name);
static void panel_expander_item_finalize (GObject* obj);
#define PANEL_ITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_ITEM, PanelItemPrivate))
enum  {
	PANEL_ITEM_DUMMY_PROPERTY
};
PanelItem* panel_item_new (void);
PanelItem* panel_item_construct (GType object_type);
static void panel_item_init (PanelItem* self);
void panel_item_set_text (PanelItem* self, const gchar* title);
void panel_item_load_app_info (PanelItem* self, const gchar* filename);
static gboolean __lambda4_ (PanelItem* self, GdkEventButton* event);
static gboolean ___lambda4__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean __lambda5_ (PanelItem* self, GdkEventButton* event);
static gboolean ___lambda5__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean __lambda6_ (PanelItem* self, GdkEventCrossing* event);
static gboolean ___lambda6__gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self);
static gboolean __lambda7_ (PanelItem* self);
static gboolean ___lambda7__gtk_widget_leave_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self);
static void __lambda8_ (PanelItem* self);
static void ___lambda8__gtk_widget_realize (GtkWidget* _sender, gpointer self);
void panel_item_set_image_from_icon (PanelItem* self, GIcon* icon);
void panel_item_append_filler (PanelItem* self, gint width);
static gboolean panel_item_real_draw (GtkWidget* base, cairo_t* cr);
static void panel_item_finalize (GObject* obj);


PanelExpanderItem* panel_expander_item_construct (GType object_type, const gchar* title, const gchar* icon) {
	PanelExpanderItem * self = NULL;
	const gchar* _tmp0_ = NULL;
	PanelItem* _tmp1_ = NULL;
	PanelItem* _tmp2_ = NULL;
	PanelItem* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	PanelItem* _tmp5_ = NULL;
	g_return_val_if_fail (title != NULL, NULL);
	g_return_val_if_fail (icon != NULL, NULL);
	self = (PanelExpanderItem*) g_object_new (object_type, NULL);
	gtk_widget_add_events ((GtkWidget*) self, (gint) ((((((GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK) | GDK_ENTER_NOTIFY_MASK) | GDK_LEAVE_NOTIFY_MASK) | GDK_KEY_PRESS_MASK) | GDK_KEY_RELEASE_MASK) | GDK_POINTER_MOTION_MASK));
	_tmp0_ = title;
	_tmp1_ = panel_item_new_with_label (_tmp0_);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->item);
	self->priv->item = _tmp1_;
	_tmp2_ = self->priv->item;
	gtk_widget_show ((GtkWidget*) _tmp2_);
	_tmp3_ = self->priv->item;
	_tmp4_ = icon;
	panel_item_set_image (_tmp3_, _tmp4_);
	_tmp5_ = self->priv->item;
	gtk_expander_set_label_widget ((GtkExpander*) self, (GtkWidget*) _tmp5_);
	return self;
}


PanelExpanderItem* panel_expander_item_new (const gchar* title, const gchar* icon) {
	return panel_expander_item_construct (TYPE_PANEL_EXPANDER_ITEM, title, icon);
}


static void panel_expander_item_class_init (PanelExpanderItemClass * klass) {
	panel_expander_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PanelExpanderItemPrivate));
	G_OBJECT_CLASS (klass)->finalize = panel_expander_item_finalize;
}


static void panel_expander_item_instance_init (PanelExpanderItem * self) {
	self->priv = PANEL_EXPANDER_ITEM_GET_PRIVATE (self);
}


static void panel_expander_item_finalize (GObject* obj) {
	PanelExpanderItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_EXPANDER_ITEM, PanelExpanderItem);
	_g_object_unref0 (self->priv->item);
	G_OBJECT_CLASS (panel_expander_item_parent_class)->finalize (obj);
}


GType panel_expander_item_get_type (void) {
	static volatile gsize panel_expander_item_type_id__volatile = 0;
	if (g_once_init_enter (&panel_expander_item_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelExpanderItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_expander_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelExpanderItem), 0, (GInstanceInitFunc) panel_expander_item_instance_init, NULL };
		GType panel_expander_item_type_id;
		panel_expander_item_type_id = g_type_register_static (GTK_TYPE_EXPANDER, "PanelExpanderItem", &g_define_type_info, 0);
		g_once_init_leave (&panel_expander_item_type_id__volatile, panel_expander_item_type_id);
	}
	return panel_expander_item_type_id__volatile;
}


PanelItem* panel_item_construct (GType object_type) {
	PanelItem * self = NULL;
	self = (PanelItem*) g_object_new (object_type, NULL);
	panel_item_init (self);
	return self;
}


PanelItem* panel_item_new (void) {
	return panel_item_construct (TYPE_PANEL_ITEM);
}


PanelItem* panel_item_construct_with_label (GType object_type, const gchar* title) {
	PanelItem * self = NULL;
	GtkLabel* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (title != NULL, NULL);
	self = (PanelItem*) g_object_new (object_type, NULL);
	panel_item_init (self);
	_tmp0_ = self->priv->label;
	_tmp1_ = title;
	gtk_label_set_text (_tmp0_, _tmp1_);
	return self;
}


PanelItem* panel_item_new_with_label (const gchar* title) {
	return panel_item_construct_with_label (TYPE_PANEL_ITEM, title);
}


void panel_item_set_text (PanelItem* self, const gchar* title) {
	GtkLabel* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (title != NULL);
	_tmp0_ = self->priv->label;
	_tmp1_ = title;
	gtk_label_set_text (_tmp0_, _tmp1_);
}


void panel_item_load_app_info (PanelItem* self, const gchar* filename) {
	const gchar* _tmp0_ = NULL;
	GDesktopAppInfo* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	_tmp0_ = filename;
	_tmp1_ = g_desktop_app_info_new_from_filename (_tmp0_);
	_g_object_unref0 (self->priv->info);
	self->priv->info = _tmp1_;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean __lambda4_ (PanelItem* self, GdkEventButton* event) {
	gboolean result = FALSE;
	g_return_val_if_fail (event != NULL, FALSE);
	self->priv->pressed = TRUE;
	result = TRUE;
	return result;
}


static gboolean ___lambda4__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda4_ ((PanelItem*) self, event);
	return result;
}


static gboolean __lambda5_ (PanelItem* self, GdkEventButton* event) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GdkEventButton _tmp2_ = {0};
	guint _tmp3_ = 0U;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->pressed;
	if (_tmp0_ == FALSE) {
		result = TRUE;
		return result;
	}
	self->priv->pressed = FALSE;
	_tmp2_ = *event;
	_tmp3_ = _tmp2_.button;
	if (_tmp3_ == ((guint) 1)) {
		GdkEventButton _tmp4_ = {0};
		GdkEventType _tmp5_ = 0;
		_tmp4_ = *event;
		_tmp5_ = _tmp4_.type;
		_tmp1_ = _tmp5_ == GDK_BUTTON_RELEASE;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		g_signal_emit_by_name (self, "activate");
	} else {
		gboolean _tmp6_ = FALSE;
		GdkEventButton _tmp7_ = {0};
		guint _tmp8_ = 0U;
		_tmp7_ = *event;
		_tmp8_ = _tmp7_.button;
		if (_tmp8_ == ((guint) 3)) {
			GdkEventButton _tmp9_ = {0};
			GdkEventType _tmp10_ = 0;
			_tmp9_ = *event;
			_tmp10_ = _tmp9_.type;
			_tmp6_ = _tmp10_ == GDK_BUTTON_RELEASE;
		} else {
			_tmp6_ = FALSE;
		}
		if (_tmp6_) {
			GdkEventButton _tmp11_ = {0};
			_tmp11_ = *event;
			g_signal_emit_by_name (self, "right-clicked", &_tmp11_);
		}
	}
	result = TRUE;
	return result;
}


static gboolean ___lambda5__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda5_ ((PanelItem*) self, event);
	return result;
}


static gboolean __lambda6_ (PanelItem* self, GdkEventCrossing* event) {
	gboolean result = FALSE;
	g_return_val_if_fail (event != NULL, FALSE);
	gtk_widget_set_state ((GtkWidget*) self, GTK_STATE_PRELIGHT);
	result = TRUE;
	return result;
}


static gboolean ___lambda6__gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self) {
	gboolean result;
	result = __lambda6_ ((PanelItem*) self, event);
	return result;
}


static gboolean __lambda7_ (PanelItem* self) {
	gboolean result = FALSE;
	gtk_widget_set_state ((GtkWidget*) self, GTK_STATE_NORMAL);
	result = TRUE;
	return result;
}


static gboolean ___lambda7__gtk_widget_leave_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self) {
	gboolean result;
	result = __lambda7_ ((PanelItem*) self);
	return result;
}


static void __lambda8_ (PanelItem* self) {
	GtkEventBox* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	GtkImage* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	_tmp0_ = self->priv->event_box;
	_tmp1_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	_tmp2_ = gtk_widget_get_allocated_width (_tmp1_);
	_tmp3_ = self->priv->MARGIN;
	_tmp4_ = self->priv->image;
	_tmp5_ = gtk_widget_get_allocated_width ((GtkWidget*) _tmp4_);
	_tmp6_ = self->priv->MARGIN;
	gtk_widget_set_size_request ((GtkWidget*) _tmp0_, _tmp2_ - (_tmp3_ * 2), _tmp5_ + _tmp6_);
}


static void ___lambda8__gtk_widget_realize (GtkWidget* _sender, gpointer self) {
	__lambda8_ ((PanelItem*) self);
}


static void panel_item_init (PanelItem* self) {
	GtkSettings* _tmp0_ = NULL;
	GtkSettings* _tmp1_ = NULL;
	GtkHBox* _tmp2_ = NULL;
	GtkEventBox* _tmp3_ = NULL;
	GtkEventBox* _tmp4_ = NULL;
	GtkEventBox* _tmp5_ = NULL;
	GtkEventBox* _tmp6_ = NULL;
	GtkHBox* _tmp7_ = NULL;
	GtkEventBox* _tmp8_ = NULL;
	GtkEventBox* _tmp9_ = NULL;
	GtkLabel* _tmp10_ = NULL;
	GtkImage* _tmp11_ = NULL;
	GtkLabel* _tmp12_ = NULL;
	GtkLabel* _tmp13_ = NULL;
	GtkImage* _tmp14_ = NULL;
	GtkHBox* _tmp15_ = NULL;
	GtkHBox* _tmp16_ = NULL;
	GtkImage* _tmp17_ = NULL;
	GtkHBox* _tmp18_ = NULL;
	GtkLabel* _tmp19_ = NULL;
	GtkEventBox* _tmp20_ = NULL;
	GtkEventBox* _tmp21_ = NULL;
	GtkEventBox* _tmp22_ = NULL;
	GtkEventBox* _tmp23_ = NULL;
	GtkEventBox* _tmp24_ = NULL;
	GtkEventBox* _tmp25_ = NULL;
	g_return_if_fail (self != NULL);
	self->priv->pressed = FALSE;
	_tmp0_ = gtk_settings_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->settings);
	self->priv->settings = _tmp1_;
	_tmp2_ = (GtkHBox*) gtk_hbox_new (FALSE, 0);
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->box);
	self->priv->box = _tmp2_;
	_tmp3_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->event_box);
	self->priv->event_box = _tmp3_;
	_tmp4_ = self->priv->event_box;
	gtk_widget_show ((GtkWidget*) _tmp4_);
	_tmp5_ = self->priv->event_box;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp5_);
	_tmp6_ = self->priv->event_box;
	_tmp7_ = self->priv->box;
	gtk_container_add ((GtkContainer*) _tmp6_, (GtkWidget*) _tmp7_);
	_tmp8_ = self->priv->event_box;
	gtk_event_box_set_above_child (_tmp8_, TRUE);
	_tmp9_ = self->priv->event_box;
	gtk_event_box_set_visible_window (_tmp9_, FALSE);
	_g_object_unref0 (self->priv->info);
	self->priv->info = NULL;
	_tmp10_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp10_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp10_;
	_tmp11_ = (GtkImage*) gtk_image_new_from_stock (GTK_STOCK_MISSING_IMAGE, GTK_ICON_SIZE_LARGE_TOOLBAR);
	g_object_ref_sink (_tmp11_);
	_g_object_unref0 (self->priv->image);
	self->priv->image = _tmp11_;
	_tmp12_ = self->priv->label;
	gtk_widget_show ((GtkWidget*) _tmp12_);
	_tmp13_ = self->priv->label;
	gtk_label_set_justify (_tmp13_, GTK_JUSTIFY_LEFT);
	_tmp14_ = self->priv->image;
	gtk_widget_show ((GtkWidget*) _tmp14_);
	_tmp15_ = self->priv->box;
	gtk_widget_show ((GtkWidget*) _tmp15_);
	_tmp16_ = self->priv->box;
	_tmp17_ = self->priv->image;
	gtk_box_pack_start ((GtkBox*) _tmp16_, (GtkWidget*) _tmp17_, FALSE, FALSE, (guint) 10);
	_tmp18_ = self->priv->box;
	_tmp19_ = self->priv->label;
	gtk_box_pack_start ((GtkBox*) _tmp18_, (GtkWidget*) _tmp19_, FALSE, TRUE, (guint) 0);
	gtk_widget_show ((GtkWidget*) self);
	_tmp20_ = self->priv->event_box;
	gtk_widget_add_events ((GtkWidget*) _tmp20_, (gint) (((((((GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK) | GDK_STRUCTURE_MASK) | GDK_ENTER_NOTIFY_MASK) | GDK_LEAVE_NOTIFY_MASK) | GDK_KEY_PRESS_MASK) | GDK_KEY_RELEASE_MASK) | GDK_POINTER_MOTION_MASK));
	_tmp21_ = self->priv->event_box;
	g_signal_connect_object ((GtkWidget*) _tmp21_, "button-press-event", (GCallback) ___lambda4__gtk_widget_button_press_event, self, 0);
	_tmp22_ = self->priv->event_box;
	g_signal_connect_object ((GtkWidget*) _tmp22_, "button-release-event", (GCallback) ___lambda5__gtk_widget_button_release_event, self, 0);
	_tmp23_ = self->priv->event_box;
	g_signal_connect_object ((GtkWidget*) _tmp23_, "enter-notify-event", (GCallback) ___lambda6__gtk_widget_enter_notify_event, self, 0);
	_tmp24_ = self->priv->event_box;
	g_signal_connect_object ((GtkWidget*) _tmp24_, "leave-notify-event", (GCallback) ___lambda7__gtk_widget_leave_notify_event, self, 0);
	_tmp25_ = self->priv->event_box;
	g_signal_connect_object ((GtkWidget*) _tmp25_, "realize", (GCallback) ___lambda8__gtk_widget_realize, self, 0);
}


void panel_item_set_image (PanelItem* self, const gchar* image_name) {
	const gchar* _tmp0_ = NULL;
	GtkImage* _tmp7_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (image_name != NULL);
	_tmp0_ = image_name;
	if (g_strcmp0 (_tmp0_, "") != 0) {
		GtkImage* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		GtkSettings* _tmp3_ = NULL;
		gboolean _tmp4_ = FALSE;
		gboolean _tmp5_ = FALSE;
		_tmp1_ = self->priv->image;
		_tmp2_ = image_name;
		gtk_image_set_from_icon_name (_tmp1_, _tmp2_, GTK_ICON_SIZE_LARGE_TOOLBAR);
		_tmp3_ = self->priv->settings;
		g_object_get (_tmp3_, "gtk-menu-images", &_tmp4_, NULL);
		_tmp5_ = _tmp4_;
		if (_tmp5_) {
			GtkImage* _tmp6_ = NULL;
			_tmp6_ = self->priv->image;
			gtk_widget_show ((GtkWidget*) _tmp6_);
		}
		return;
	}
	_tmp7_ = self->priv->image;
	gtk_image_clear (_tmp7_);
}


void panel_item_set_image_from_icon (PanelItem* self, GIcon* icon) {
	GtkImage* _tmp0_ = NULL;
	GIcon* _tmp1_ = NULL;
	GtkSettings* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (icon != NULL);
	_tmp0_ = self->priv->image;
	_tmp1_ = icon;
	gtk_image_set_from_gicon (_tmp0_, _tmp1_, GTK_ICON_SIZE_LARGE_TOOLBAR);
	_tmp2_ = self->priv->settings;
	g_object_get (_tmp2_, "gtk-menu-images", &_tmp3_, NULL);
	_tmp4_ = _tmp3_;
	if (_tmp4_) {
		GtkImage* _tmp5_ = NULL;
		_tmp5_ = self->priv->image;
		gtk_widget_show ((GtkWidget*) _tmp5_);
	}
}


void panel_item_append_filler (PanelItem* self, gint width) {
	GtkDrawingArea* filler = NULL;
	GtkDrawingArea* _tmp0_ = NULL;
	GtkHBox* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GtkHBox* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkDrawingArea*) gtk_drawing_area_new ();
	g_object_ref_sink (_tmp0_);
	filler = _tmp0_;
	gtk_widget_show ((GtkWidget*) filler);
	_tmp1_ = self->priv->box;
	_tmp2_ = width;
	gtk_box_pack_start ((GtkBox*) _tmp1_, (GtkWidget*) filler, FALSE, FALSE, (guint) _tmp2_);
	_tmp3_ = self->priv->box;
	gtk_box_reorder_child ((GtkBox*) _tmp3_, (GtkWidget*) filler, 0);
	_g_object_unref0 (filler);
}


static gboolean panel_item_real_draw (GtkWidget* base, cairo_t* cr) {
	PanelItem * self;
	gboolean result = FALSE;
	GtkStyleContext* style = NULL;
	GtkStyleContext* _tmp0_ = NULL;
	GtkStyleContext* _tmp1_ = NULL;
	GtkStateFlags _tmp2_ = 0;
	cairo_t* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	GtkEventBox* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	cairo_t* _tmp8_ = NULL;
	self = (PanelItem*) base;
	g_return_val_if_fail (cr != NULL, FALSE);
	_tmp0_ = gtk_widget_get_style_context ((GtkWidget*) self);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	style = _tmp1_;
	_tmp2_ = gtk_widget_get_state_flags ((GtkWidget*) self);
	gtk_style_context_set_state (style, _tmp2_);
	_tmp3_ = cr;
	_tmp4_ = self->priv->MARGIN;
	_tmp5_ = self->priv->event_box;
	_tmp6_ = gtk_widget_get_allocated_width ((GtkWidget*) _tmp5_);
	_tmp7_ = gtk_widget_get_allocated_height ((GtkWidget*) self);
	gtk_render_background (style, _tmp3_, (gdouble) _tmp4_, (gdouble) 0, (gdouble) _tmp6_, (gdouble) _tmp7_);
	_tmp8_ = cr;
	GTK_WIDGET_CLASS (panel_item_parent_class)->draw ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_BOX, GtkBox), _tmp8_);
	result = TRUE;
	_g_object_unref0 (style);
	return result;
}


static void panel_item_class_init (PanelItemClass * klass) {
	panel_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PanelItemPrivate));
	((GtkWidgetClass *) klass)->draw = panel_item_real_draw;
	G_OBJECT_CLASS (klass)->finalize = panel_item_finalize;
	g_signal_new ("activate", TYPE_PANEL_ITEM, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("right_clicked", TYPE_PANEL_ITEM, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__POINTER, G_TYPE_NONE, 1, G_TYPE_POINTER);
}


static void panel_item_instance_init (PanelItem * self) {
	self->priv = PANEL_ITEM_GET_PRIVATE (self);
	self->priv->MARGIN = 6;
}


static void panel_item_finalize (GObject* obj) {
	PanelItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_ITEM, PanelItem);
	_g_object_unref0 (self->priv->box);
	_g_object_unref0 (self->priv->info);
	_g_object_unref0 (self->priv->event_box);
	_g_object_unref0 (self->priv->label);
	_g_object_unref0 (self->priv->image);
	_g_object_unref0 (self->priv->settings);
	G_OBJECT_CLASS (panel_item_parent_class)->finalize (obj);
}


GType panel_item_get_type (void) {
	static volatile gsize panel_item_type_id__volatile = 0;
	if (g_once_init_enter (&panel_item_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PanelItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelItem), 0, (GInstanceInitFunc) panel_item_instance_init, NULL };
		GType panel_item_type_id;
		panel_item_type_id = g_type_register_static (GTK_TYPE_BOX, "PanelItem", &g_define_type_info, 0);
		g_once_init_leave (&panel_item_type_id__volatile, panel_item_type_id);
	}
	return panel_item_type_id__volatile;
}



