/* utils.c generated by valac 0.26.1, the Vala compiler
 * generated from utils.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <JavaScriptCore/JavaScript.h>
#include <gio/gdesktopappinfo.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>
#include <time.h>

#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block5Data Block5Data;
#define _JSStringRelease0(var) ((var == NULL) ? NULL : (var = (JSStringRelease (var), NULL)))
typedef struct _Block6Data Block6Data;
typedef struct _Block7Data Block7Data;
#define _JSClassRelease0(var) ((var == NULL) ? NULL : (var = (JSClassRelease (var), NULL)))
#define _gtk_icon_info_free0(var) ((var == NULL) ? NULL : (var = (gtk_icon_info_free (var), NULL)))

struct _Block5Data {
	int _ref_count_;
	GtkMessageDialog* dialog;
};

struct _Block6Data {
	int _ref_count_;
	GtkMessageDialog* dialog;
};

struct _Block7Data {
	int _ref_count_;
	GtkMessageDialog* dialog;
};



gboolean utils_launch_search (void);
gboolean utils_launch_profile (void);
gboolean utils_lock_screen (void);
gboolean utils_print_screen (void);
void utils_grab (GtkWindow* w);
void utils_ungrab (GtkWindow* w);
void* utils_js_run_desktop (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static Block5Data* block5_data_ref (Block5Data* _data5_);
static void block5_data_unref (void * _userdata_);
static void ____lambda25_ (Block5Data* _data5_);
static void _____lambda25__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
void* utils_js_open_uri (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static Block6Data* block6_data_ref (Block6Data* _data6_);
static void block6_data_unref (void * _userdata_);
static void ____lambda26_ (Block6Data* _data6_);
static void _____lambda26__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
void* utils_js_run_command (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static Block7Data* block7_data_ref (Block7Data* _data7_);
static void block7_data_unref (void * _userdata_);
static void ____lambda27_ (Block7Data* _data7_);
static void _____lambda27__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
void* utils_js_translate (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* utils_js_get_icon_path (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
gchar* utils_get_icon_path (const gchar* name, gint size);
void* utils_js_get_time (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* utils_js_get_date (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _utils_js_run_desktop_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
static void* _utils_js_open_uri_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
static void* _utils_js_run_command_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
static void* _utils_js_translate_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
static void* _utils_js_get_icon_path_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
static void* _utils_js_get_time_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
static void* _utils_js_get_date_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void utils_setup_js_class (void* context);

const JSStaticFunction UTILS_js_funcs[8] = {{"run_desktop", _utils_js_run_desktop_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {"open_uri", _utils_js_open_uri_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {"run_command", _utils_js_run_command_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {"translate", _utils_js_translate_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {"getIconPath", _utils_js_get_icon_path_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {"getTime", _utils_js_get_time_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {"getDate", _utils_js_get_date_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {NULL, NULL, 0}};
const JSClassDefinition UTILS_js_class = {0, kJSClassAttributeNone, "Utils", NULL, NULL, UTILS_js_funcs, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};

gboolean utils_launch_search (void) {
	gboolean result = FALSE;
	GError * _inner_error_ = NULL;
	{
		g_spawn_command_line_async ("synapse", &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch4_g_error;
		}
		result = TRUE;
		return result;
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		result = FALSE;
		_g_error_free0 (e);
		return result;
	}
	__finally4:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return FALSE;
}


gboolean utils_launch_profile (void) {
	gboolean result = FALSE;
	GError * _inner_error_ = NULL;
	{
		g_spawn_command_line_async ("gnome-about-me", &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch5_g_error;
		}
		result = TRUE;
		return result;
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		result = FALSE;
		_g_error_free0 (e);
		return result;
	}
	__finally5:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return FALSE;
}


gboolean utils_lock_screen (void) {
	gboolean result = FALSE;
	GError * _inner_error_ = NULL;
	{
		g_spawn_command_line_async ("gnome-screensaver-command -l", &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch6_g_error;
		}
		result = TRUE;
		return result;
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		result = FALSE;
		_g_error_free0 (e);
		return result;
	}
	__finally6:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return FALSE;
}


gboolean utils_print_screen (void) {
	gboolean result = FALSE;
	GError * _inner_error_ = NULL;
	{
		g_spawn_command_line_async ("gnome-screenshot", &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch7_g_error;
		}
		result = TRUE;
		return result;
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		result = FALSE;
		_g_error_free0 (e);
		return result;
	}
	__finally7:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return FALSE;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void utils_grab (GtkWindow* w) {
	GdkDevice* device = NULL;
	GdkDevice* _tmp0_ = NULL;
	GdkDevice* _tmp1_ = NULL;
	GdkDevice* _tmp2_ = NULL;
	GdkDevice* keyboard = NULL;
	GdkDevice* _tmp15_ = NULL;
	GdkDevice* _tmp16_ = NULL;
	GdkDevice* pointer = NULL;
	GdkDevice* _tmp17_ = NULL;
	GdkDevice* _tmp18_ = NULL;
	GdkDevice* _tmp19_ = NULL;
	GdkInputSource _tmp20_ = 0;
	GdkGrabStatus status = 0;
	GdkDevice* _tmp27_ = NULL;
	GtkWindow* _tmp28_ = NULL;
	GdkWindow* _tmp29_ = NULL;
	GdkGrabStatus _tmp30_ = 0;
	GdkDevice* _tmp31_ = NULL;
	GtkWindow* _tmp32_ = NULL;
	GdkWindow* _tmp33_ = NULL;
	GdkGrabStatus _tmp34_ = 0;
	g_return_if_fail (w != NULL);
	_tmp0_ = gtk_get_current_event_device ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	device = _tmp1_;
	_tmp2_ = device;
	if (_tmp2_ == NULL) {
		GdkDisplay* display = NULL;
		GtkWindow* _tmp3_ = NULL;
		GdkDisplay* _tmp4_ = NULL;
		GdkDisplay* _tmp5_ = NULL;
		GdkDeviceManager* manager = NULL;
		GdkDisplay* _tmp6_ = NULL;
		GdkDeviceManager* _tmp7_ = NULL;
		GdkDeviceManager* _tmp8_ = NULL;
		GList* devices = NULL;
		GdkDeviceManager* _tmp9_ = NULL;
		GList* _tmp10_ = NULL;
		GList* _tmp11_ = NULL;
		GList* _tmp12_ = NULL;
		gconstpointer _tmp13_ = NULL;
		GdkDevice* _tmp14_ = NULL;
		_tmp3_ = w;
		_tmp4_ = gtk_widget_get_display ((GtkWidget*) _tmp3_);
		_tmp5_ = _g_object_ref0 (_tmp4_);
		display = _tmp5_;
		_tmp6_ = display;
		_tmp7_ = gdk_display_get_device_manager (_tmp6_);
		_tmp8_ = _g_object_ref0 (_tmp7_);
		manager = _tmp8_;
		_tmp9_ = manager;
		_tmp10_ = gdk_device_manager_list_devices (_tmp9_, GDK_DEVICE_TYPE_MASTER);
		_tmp11_ = g_list_copy (_tmp10_);
		devices = _tmp11_;
		_tmp12_ = devices;
		_tmp13_ = _tmp12_->data;
		_tmp14_ = _g_object_ref0 ((GdkDevice*) _tmp13_);
		_g_object_unref0 (device);
		device = _tmp14_;
		_g_list_free0 (devices);
		_g_object_unref0 (manager);
		_g_object_unref0 (display);
	}
	_tmp15_ = device;
	_tmp16_ = _g_object_ref0 (_tmp15_);
	keyboard = _tmp16_;
	_tmp17_ = device;
	_tmp18_ = _g_object_ref0 (_tmp17_);
	pointer = _tmp18_;
	_tmp19_ = device;
	_tmp20_ = gdk_device_get_source (_tmp19_);
	if (_tmp20_ == GDK_SOURCE_KEYBOARD) {
		GdkDevice* _tmp21_ = NULL;
		GdkDevice* _tmp22_ = NULL;
		GdkDevice* _tmp23_ = NULL;
		_tmp21_ = device;
		_tmp22_ = gdk_device_get_associated_device (_tmp21_);
		_tmp23_ = _g_object_ref0 (_tmp22_);
		_g_object_unref0 (pointer);
		pointer = _tmp23_;
	} else {
		GdkDevice* _tmp24_ = NULL;
		GdkDevice* _tmp25_ = NULL;
		GdkDevice* _tmp26_ = NULL;
		_tmp24_ = device;
		_tmp25_ = gdk_device_get_associated_device (_tmp24_);
		_tmp26_ = _g_object_ref0 (_tmp25_);
		_g_object_unref0 (keyboard);
		keyboard = _tmp26_;
	}
	_tmp27_ = keyboard;
	_tmp28_ = w;
	_tmp29_ = gtk_widget_get_window ((GtkWidget*) _tmp28_);
	_tmp30_ = gdk_device_grab (_tmp27_, _tmp29_, GDK_OWNERSHIP_WINDOW, TRUE, GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK, NULL, (guint32) GDK_CURRENT_TIME);
	status = _tmp30_;
	_tmp31_ = pointer;
	_tmp32_ = w;
	_tmp33_ = gtk_widget_get_window ((GtkWidget*) _tmp32_);
	_tmp34_ = gdk_device_grab (_tmp31_, _tmp33_, GDK_OWNERSHIP_WINDOW, TRUE, GDK_BUTTON_PRESS_MASK, NULL, (guint32) GDK_CURRENT_TIME);
	status = _tmp34_;
	_g_object_unref0 (pointer);
	_g_object_unref0 (keyboard);
	_g_object_unref0 (device);
}


void utils_ungrab (GtkWindow* w) {
	GdkDevice* device = NULL;
	GdkDevice* _tmp0_ = NULL;
	GdkDevice* _tmp1_ = NULL;
	GdkDevice* secondary = NULL;
	GdkDevice* _tmp2_ = NULL;
	GdkDevice* _tmp3_ = NULL;
	g_return_if_fail (w != NULL);
	_tmp0_ = gtk_get_current_event_device ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	device = _tmp1_;
	_tmp2_ = gdk_device_get_associated_device (device);
	_tmp3_ = _g_object_ref0 (_tmp2_);
	secondary = _tmp3_;
	gdk_device_ungrab (device, (guint32) GDK_CURRENT_TIME);
	gdk_device_ungrab (secondary, (guint32) GDK_CURRENT_TIME);
	_g_object_unref0 (secondary);
	_g_object_unref0 (device);
}


static Block5Data* block5_data_ref (Block5Data* _data5_) {
	g_atomic_int_inc (&_data5_->_ref_count_);
	return _data5_;
}


static void block5_data_unref (void * _userdata_) {
	Block5Data* _data5_;
	_data5_ = (Block5Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data5_->_ref_count_)) {
		_g_object_unref0 (_data5_->dialog);
		g_slice_free (Block5Data, _data5_);
	}
}


static void ____lambda25_ (Block5Data* _data5_) {
	GtkMessageDialog* _tmp0_ = NULL;
	_tmp0_ = _data5_->dialog;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
}


static void _____lambda25__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	____lambda25_ (self);
}


void* utils_js_run_desktop (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp42_ = NULL;
	void* _tmp43_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 > 0) {
		gboolean from_desktop = FALSE;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* s = NULL;
		void** _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		void* _tmp8_ = NULL;
		void* _tmp9_ = NULL;
		void* _tmp10_ = NULL;
		gchar* buffer = NULL;
		void* _tmp11_ = NULL;
		gsize _tmp12_ = 0UL;
		gchar* _tmp13_ = NULL;
		gint buffer_length1 = 0;
		gint _buffer_size_ = 0;
		void* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		gint _tmp15__length1 = 0;
		gchar* _tmp16_ = NULL;
		gint _tmp16__length1 = 0;
		gchar* path = NULL;
		gchar* _tmp17_ = NULL;
		gint _tmp17__length1 = 0;
		gchar _tmp18_ = '\0';
		GDesktopAppInfo* info = NULL;
		const gchar* _tmp29_ = NULL;
		GDesktopAppInfo* _tmp30_ = NULL;
		from_desktop = FALSE;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		if (_tmp1__length1 > 1) {
			gboolean _from_desktop = FALSE;
			void** _tmp2_ = NULL;
			gint _tmp2__length1 = 0;
			void* _tmp3_ = NULL;
			void* _tmp4_ = NULL;
			gboolean _tmp5_ = FALSE;
			gboolean _tmp6_ = FALSE;
			_tmp2_ = arguments;
			_tmp2__length1 = arguments_length1;
			_tmp3_ = _tmp2_[1];
			_tmp4_ = ctx;
			_tmp5_ = JSValueToBoolean (_tmp4_, _tmp3_);
			_from_desktop = _tmp5_;
			_tmp6_ = _from_desktop;
			from_desktop = _tmp6_;
		}
		_tmp7_ = arguments;
		_tmp7__length1 = arguments_length1;
		_tmp8_ = _tmp7_[0];
		_tmp9_ = ctx;
		_tmp10_ = JSValueToStringCopy (_tmp9_, _tmp8_, NULL);
		s = _tmp10_;
		_tmp11_ = s;
		_tmp12_ = JSStringGetLength (_tmp11_);
		_tmp13_ = g_new0 (gchar, _tmp12_ + 1);
		buffer = _tmp13_;
		buffer_length1 = _tmp12_ + 1;
		_buffer_size_ = buffer_length1;
		_tmp14_ = s;
		_tmp15_ = buffer;
		_tmp15__length1 = buffer_length1;
		_tmp16_ = buffer;
		_tmp16__length1 = buffer_length1;
		JSStringGetUTF8CString (_tmp14_, _tmp15_, (gsize) _tmp16__length1);
		path = NULL;
		_tmp17_ = buffer;
		_tmp17__length1 = buffer_length1;
		_tmp18_ = _tmp17_[0];
		if (_tmp18_ != '/') {
			gboolean _tmp19_ = FALSE;
			_tmp19_ = from_desktop;
			if (_tmp19_) {
				const gchar* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				gchar* _tmp22_ = NULL;
				gchar* _tmp23_ = NULL;
				gint _tmp23__length1 = 0;
				gchar* _tmp24_ = NULL;
				_tmp20_ = g_get_user_special_dir (G_USER_DIRECTORY_DESKTOP);
				_tmp21_ = g_strconcat (_tmp20_, "/", NULL);
				_tmp22_ = _tmp21_;
				_tmp23_ = buffer;
				_tmp23__length1 = buffer_length1;
				_tmp24_ = g_strconcat (_tmp22_, (const gchar*) _tmp23_, NULL);
				_g_free0 (path);
				path = _tmp24_;
				_g_free0 (_tmp22_);
			} else {
				gchar* _tmp25_ = NULL;
				gint _tmp25__length1 = 0;
				gchar* _tmp26_ = NULL;
				_tmp25_ = buffer;
				_tmp25__length1 = buffer_length1;
				_tmp26_ = g_strconcat ("/usr/share/applications/", (const gchar*) _tmp25_, NULL);
				_g_free0 (path);
				path = _tmp26_;
			}
		} else {
			gchar* _tmp27_ = NULL;
			gint _tmp27__length1 = 0;
			gchar* _tmp28_ = NULL;
			_tmp27_ = buffer;
			_tmp27__length1 = buffer_length1;
			_tmp28_ = g_strdup ((const gchar*) _tmp27_);
			_g_free0 (path);
			path = _tmp28_;
		}
		_tmp29_ = path;
		_tmp30_ = g_desktop_app_info_new_from_filename (_tmp29_);
		info = _tmp30_;
		{
			GDesktopAppInfo* _tmp31_ = NULL;
			GdkDisplay* _tmp32_ = NULL;
			GdkAppLaunchContext* _tmp33_ = NULL;
			_tmp31_ = info;
			_tmp32_ = gdk_display_get_default ();
			_tmp33_ = gdk_display_get_app_launch_context (_tmp32_);
			g_app_info_launch ((GAppInfo*) _tmp31_, NULL, (GAppLaunchContext*) _tmp33_, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch8_g_error;
			}
		}
		goto __finally8;
		__catch8_g_error:
		{
			GError* e = NULL;
			Block5Data* _data5_;
			const gchar* _tmp34_ = NULL;
			GDesktopAppInfo* _tmp35_ = NULL;
			const gchar* _tmp36_ = NULL;
			GError* _tmp37_ = NULL;
			const gchar* _tmp38_ = NULL;
			GtkMessageDialog* _tmp39_ = NULL;
			GtkMessageDialog* _tmp40_ = NULL;
			GtkMessageDialog* _tmp41_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_data5_ = g_slice_new0 (Block5Data);
			_data5_->_ref_count_ = 1;
			_tmp34_ = _ ("Error opening menu item %s: %s");
			_tmp35_ = info;
			_tmp36_ = g_app_info_get_display_name ((GAppInfo*) _tmp35_);
			_tmp37_ = e;
			_tmp38_ = _tmp37_->message;
			_tmp39_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_DESTROY_WITH_PARENT, GTK_MESSAGE_ERROR, GTK_BUTTONS_CLOSE, _tmp34_, _tmp36_, _tmp38_);
			g_object_ref_sink (_tmp39_);
			_data5_->dialog = _tmp39_;
			_tmp40_ = _data5_->dialog;
			g_signal_connect_data ((GtkDialog*) _tmp40_, "response", (GCallback) _____lambda25__gtk_dialog_response, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
			_tmp41_ = _data5_->dialog;
			gtk_widget_show ((GtkWidget*) _tmp41_);
			_g_error_free0 (e);
			block5_data_unref (_data5_);
			_data5_ = NULL;
		}
		__finally8:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (info);
			_g_free0 (path);
			buffer = (g_free (buffer), NULL);
			_JSStringRelease0 (s);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_g_object_unref0 (info);
		_g_free0 (path);
		buffer = (g_free (buffer), NULL);
		_JSStringRelease0 (s);
	}
	_tmp42_ = ctx;
	_tmp43_ = JSValueMakeUndefined (_tmp42_);
	result = _tmp43_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static Block6Data* block6_data_ref (Block6Data* _data6_) {
	g_atomic_int_inc (&_data6_->_ref_count_);
	return _data6_;
}


static void block6_data_unref (void * _userdata_) {
	Block6Data* _data6_;
	_data6_ = (Block6Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data6_->_ref_count_)) {
		_g_object_unref0 (_data6_->dialog);
		g_slice_free (Block6Data, _data6_);
	}
}


static void ____lambda26_ (Block6Data* _data6_) {
	GtkMessageDialog* _tmp0_ = NULL;
	_tmp0_ = _data6_->dialog;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
}


static void _____lambda26__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	____lambda26_ (self);
}


void* utils_js_open_uri (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 == 1) {
		void* s = NULL;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* _tmp2_ = NULL;
		void* _tmp3_ = NULL;
		void* _tmp4_ = NULL;
		gchar buffer[1024] = {0};
		void* _tmp5_ = NULL;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		_tmp2_ = _tmp1_[0];
		_tmp3_ = ctx;
		_tmp4_ = JSValueToStringCopy (_tmp3_, _tmp2_, NULL);
		s = _tmp4_;
		_tmp5_ = s;
		JSStringGetUTF8CString (_tmp5_, buffer, (gsize) 1024);
		{
			GdkScreen* _tmp6_ = NULL;
			guint32 _tmp7_ = 0U;
			_tmp6_ = gdk_screen_get_default ();
			_tmp7_ = gtk_get_current_event_time ();
			gtk_show_uri (_tmp6_, (const gchar*) buffer, _tmp7_, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch9_g_error;
			}
		}
		goto __finally9;
		__catch9_g_error:
		{
			GError* e = NULL;
			Block6Data* _data6_;
			const gchar* _tmp8_ = NULL;
			GError* _tmp9_ = NULL;
			const gchar* _tmp10_ = NULL;
			GtkMessageDialog* _tmp11_ = NULL;
			GtkMessageDialog* _tmp12_ = NULL;
			GtkMessageDialog* _tmp13_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_data6_ = g_slice_new0 (Block6Data);
			_data6_->_ref_count_ = 1;
			_tmp8_ = _ ("Error opening menu item '%s': %s");
			_tmp9_ = e;
			_tmp10_ = _tmp9_->message;
			_tmp11_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_DESTROY_WITH_PARENT, GTK_MESSAGE_ERROR, GTK_BUTTONS_CLOSE, _tmp8_, (const gchar*) buffer, _tmp10_);
			g_object_ref_sink (_tmp11_);
			_data6_->dialog = _tmp11_;
			_tmp12_ = _data6_->dialog;
			g_signal_connect_data ((GtkDialog*) _tmp12_, "response", (GCallback) _____lambda26__gtk_dialog_response, block6_data_ref (_data6_), (GClosureNotify) block6_data_unref, 0);
			_tmp13_ = _data6_->dialog;
			gtk_widget_show ((GtkWidget*) _tmp13_);
			_g_error_free0 (e);
			block6_data_unref (_data6_);
			_data6_ = NULL;
		}
		__finally9:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_JSStringRelease0 (s);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_JSStringRelease0 (s);
	}
	_tmp14_ = ctx;
	_tmp15_ = JSValueMakeUndefined (_tmp14_);
	result = _tmp15_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static Block7Data* block7_data_ref (Block7Data* _data7_) {
	g_atomic_int_inc (&_data7_->_ref_count_);
	return _data7_;
}


static void block7_data_unref (void * _userdata_) {
	Block7Data* _data7_;
	_data7_ = (Block7Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data7_->_ref_count_)) {
		_g_object_unref0 (_data7_->dialog);
		g_slice_free (Block7Data, _data7_);
	}
}


static void ____lambda27_ (Block7Data* _data7_) {
	GtkMessageDialog* _tmp0_ = NULL;
	_tmp0_ = _data7_->dialog;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
}


static void _____lambda27__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	____lambda27_ (self);
}


void* utils_js_run_command (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 == 1) {
		void* s = NULL;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* _tmp2_ = NULL;
		void* _tmp3_ = NULL;
		void* _tmp4_ = NULL;
		gchar buffer[1024] = {0};
		void* _tmp5_ = NULL;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		_tmp2_ = _tmp1_[0];
		_tmp3_ = ctx;
		_tmp4_ = JSValueToStringCopy (_tmp3_, _tmp2_, NULL);
		s = _tmp4_;
		_tmp5_ = s;
		JSStringGetUTF8CString (_tmp5_, buffer, (gsize) 1024);
		{
			GAppInfo* app = NULL;
			GAppInfo* _tmp6_ = NULL;
			GAppInfo* _tmp7_ = NULL;
			_tmp6_ = g_app_info_create_from_commandline ((const gchar*) buffer, (const gchar*) buffer, G_APP_INFO_CREATE_NONE, &_inner_error_);
			app = _tmp6_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch10_g_error;
			}
			_tmp7_ = app;
			g_app_info_launch (_tmp7_, NULL, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_object_unref0 (app);
				goto __catch10_g_error;
			}
			_g_object_unref0 (app);
		}
		goto __finally10;
		__catch10_g_error:
		{
			GError* e = NULL;
			Block7Data* _data7_;
			const gchar* _tmp8_ = NULL;
			GError* _tmp9_ = NULL;
			const gchar* _tmp10_ = NULL;
			GtkMessageDialog* _tmp11_ = NULL;
			GtkMessageDialog* _tmp12_ = NULL;
			GtkMessageDialog* _tmp13_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_data7_ = g_slice_new0 (Block7Data);
			_data7_->_ref_count_ = 1;
			_tmp8_ = _ ("Error running command '%s': %s");
			_tmp9_ = e;
			_tmp10_ = _tmp9_->message;
			_tmp11_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_DESTROY_WITH_PARENT, GTK_MESSAGE_ERROR, GTK_BUTTONS_CLOSE, _tmp8_, (const gchar*) buffer, _tmp10_);
			g_object_ref_sink (_tmp11_);
			_data7_->dialog = _tmp11_;
			_tmp12_ = _data7_->dialog;
			g_signal_connect_data ((GtkDialog*) _tmp12_, "response", (GCallback) _____lambda27__gtk_dialog_response, block7_data_ref (_data7_), (GClosureNotify) block7_data_unref, 0);
			_tmp13_ = _data7_->dialog;
			gtk_widget_show ((GtkWidget*) _tmp13_);
			_g_error_free0 (e);
			block7_data_unref (_data7_);
			_data7_ = NULL;
		}
		__finally10:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_JSStringRelease0 (s);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_JSStringRelease0 (s);
	}
	_tmp14_ = ctx;
	_tmp15_ = JSValueMakeUndefined (_tmp14_);
	result = _tmp15_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* utils_js_translate (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp17_ = NULL;
	void* _tmp18_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 == 1) {
		void* s = NULL;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* _tmp2_ = NULL;
		void* _tmp3_ = NULL;
		void* _tmp4_ = NULL;
		gchar* buffer = NULL;
		void* _tmp5_ = NULL;
		gsize _tmp6_ = 0UL;
		gchar* _tmp7_ = NULL;
		gint buffer_length1 = 0;
		gint _buffer_size_ = 0;
		void* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		gchar* _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		gchar* _tmp11_ = NULL;
		gint _tmp11__length1 = 0;
		const gchar* _tmp12_ = NULL;
		void* _tmp13_ = NULL;
		void* _result_ = NULL;
		void* _tmp14_ = NULL;
		void* _tmp15_ = NULL;
		void* _tmp16_ = NULL;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		_tmp2_ = _tmp1_[0];
		_tmp3_ = ctx;
		_tmp4_ = JSValueToStringCopy (_tmp3_, _tmp2_, NULL);
		s = _tmp4_;
		_tmp5_ = s;
		_tmp6_ = JSStringGetLength (_tmp5_);
		_tmp7_ = g_new0 (gchar, _tmp6_ + 1);
		buffer = _tmp7_;
		buffer_length1 = _tmp6_ + 1;
		_buffer_size_ = buffer_length1;
		_tmp8_ = s;
		_tmp9_ = buffer;
		_tmp9__length1 = buffer_length1;
		_tmp10_ = buffer;
		_tmp10__length1 = buffer_length1;
		JSStringGetUTF8CString (_tmp8_, _tmp9_, (gsize) _tmp10__length1);
		_tmp11_ = buffer;
		_tmp11__length1 = buffer_length1;
		_tmp12_ = _ ((const gchar*) _tmp11_);
		_tmp13_ = JSStringCreateWithUTF8CString (_tmp12_);
		_JSStringRelease0 (s);
		s = _tmp13_;
		_tmp14_ = ctx;
		_tmp15_ = s;
		_tmp16_ = JSValueMakeString (_tmp14_, _tmp15_);
		_result_ = _tmp16_;
		_JSStringRelease0 (s);
		s = NULL;
		buffer = (g_free (buffer), NULL);
		buffer = NULL;
		buffer_length1 = 0;
		_buffer_size_ = buffer_length1;
		result = _result_;
		buffer = (g_free (buffer), NULL);
		_JSStringRelease0 (s);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp17_ = ctx;
	_tmp18_ = JSValueMakeUndefined (_tmp17_);
	result = _tmp18_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* utils_js_get_icon_path (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp25_ = NULL;
	void* _tmp26_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 > 0) {
		void* s = NULL;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* _tmp2_ = NULL;
		void* _tmp3_ = NULL;
		void* _tmp4_ = NULL;
		gchar* buffer = NULL;
		void* _tmp5_ = NULL;
		gsize _tmp6_ = 0UL;
		gchar* _tmp7_ = NULL;
		gint buffer_length1 = 0;
		gint _buffer_size_ = 0;
		void* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		gchar* _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		gint size = 0;
		void** _tmp11_ = NULL;
		gint _tmp11__length1 = 0;
		gchar* _tmp17_ = NULL;
		gint _tmp17__length1 = 0;
		gint _tmp18_ = 0;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		void* _tmp21_ = NULL;
		void* _result_ = NULL;
		void* _tmp22_ = NULL;
		void* _tmp23_ = NULL;
		void* _tmp24_ = NULL;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		_tmp2_ = _tmp1_[0];
		_tmp3_ = ctx;
		_tmp4_ = JSValueToStringCopy (_tmp3_, _tmp2_, NULL);
		s = _tmp4_;
		_tmp5_ = s;
		_tmp6_ = JSStringGetLength (_tmp5_);
		_tmp7_ = g_new0 (gchar, _tmp6_ + 1);
		buffer = _tmp7_;
		buffer_length1 = _tmp6_ + 1;
		_buffer_size_ = buffer_length1;
		_tmp8_ = s;
		_tmp9_ = buffer;
		_tmp9__length1 = buffer_length1;
		_tmp10_ = buffer;
		_tmp10__length1 = buffer_length1;
		JSStringGetUTF8CString (_tmp8_, _tmp9_, (gsize) _tmp10__length1);
		size = 24;
		_tmp11_ = arguments;
		_tmp11__length1 = arguments_length1;
		if (_tmp11__length1 > 1) {
			gdouble size_d = 0.0;
			void** _tmp12_ = NULL;
			gint _tmp12__length1 = 0;
			void* _tmp13_ = NULL;
			void* _tmp14_ = NULL;
			gdouble _tmp15_ = 0.0;
			gdouble _tmp16_ = 0.0;
			_tmp12_ = arguments;
			_tmp12__length1 = arguments_length1;
			_tmp13_ = _tmp12_[1];
			_tmp14_ = ctx;
			_tmp15_ = JSValueToNumber (_tmp14_, _tmp13_, NULL);
			size_d = _tmp15_;
			_tmp16_ = size_d;
			size = (gint) _tmp16_;
		}
		_tmp17_ = buffer;
		_tmp17__length1 = buffer_length1;
		_tmp18_ = size;
		_tmp19_ = utils_get_icon_path ((const gchar*) _tmp17_, _tmp18_);
		_tmp20_ = _tmp19_;
		_tmp21_ = JSStringCreateWithUTF8CString (_tmp20_);
		_JSStringRelease0 (s);
		s = _tmp21_;
		_g_free0 (_tmp20_);
		_tmp22_ = ctx;
		_tmp23_ = s;
		_tmp24_ = JSValueMakeString (_tmp22_, _tmp23_);
		_result_ = _tmp24_;
		_JSStringRelease0 (s);
		s = NULL;
		buffer = (g_free (buffer), NULL);
		buffer = NULL;
		buffer_length1 = 0;
		_buffer_size_ = buffer_length1;
		result = _result_;
		buffer = (g_free (buffer), NULL);
		_JSStringRelease0 (s);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp25_ = ctx;
	_tmp26_ = JSValueMakeUndefined (_tmp25_);
	result = _tmp26_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static void g_time_local (time_t time, struct tm* result) {
	struct tm _result_ = {0};
	struct tm _tmp0_ = {0};
	localtime_r (&time, &_tmp0_);
	_result_ = _tmp0_;
	*result = _result_;
	return;
}


void* utils_js_get_time (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	gchar bufferClock[100] = {0};
	struct tm t = {0};
	time_t _tmp0_ = 0;
	struct tm _tmp1_ = {0};
	const gchar* _tmp2_ = NULL;
	void* s = NULL;
	const gchar* _tmp3_ = NULL;
	void* _tmp4_ = NULL;
	void* _result_ = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = time (NULL);
	g_time_local (_tmp0_, &_tmp1_);
	t = _tmp1_;
	_tmp2_ = _ ("%H:%M");
	strftime (bufferClock, 100, _tmp2_, &t);
	_tmp3_ = _ ((const gchar*) bufferClock);
	_tmp4_ = JSStringCreateWithUTF8CString (_tmp3_);
	s = _tmp4_;
	_tmp5_ = ctx;
	_tmp6_ = s;
	_tmp7_ = JSValueMakeString (_tmp5_, _tmp6_);
	_result_ = _tmp7_;
	_JSStringRelease0 (s);
	s = NULL;
	result = _result_;
	_JSStringRelease0 (s);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* utils_js_get_date (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	gchar bufferClock[100] = {0};
	struct tm t = {0};
	time_t _tmp0_ = 0;
	struct tm _tmp1_ = {0};
	const gchar* _tmp2_ = NULL;
	void* s = NULL;
	const gchar* _tmp3_ = NULL;
	void* _tmp4_ = NULL;
	void* _result_ = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = time (NULL);
	g_time_local (_tmp0_, &_tmp1_);
	t = _tmp1_;
	_tmp2_ = _ ("%A, %B %e %Y");
	strftime (bufferClock, 100, _tmp2_, &t);
	_tmp3_ = _ ((const gchar*) bufferClock);
	_tmp4_ = JSStringCreateWithUTF8CString (_tmp3_);
	s = _tmp4_;
	_tmp5_ = ctx;
	_tmp6_ = s;
	_tmp7_ = JSValueMakeString (_tmp5_, _tmp6_);
	_result_ = _tmp7_;
	_JSStringRelease0 (s);
	s = NULL;
	result = _result_;
	_JSStringRelease0 (s);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static void* _utils_js_run_desktop_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_run_desktop (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _utils_js_open_uri_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_open_uri (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _utils_js_run_command_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_run_command (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _utils_js_translate_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_translate (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _utils_js_get_icon_path_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_get_icon_path (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _utils_js_get_time_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_get_time (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _utils_js_get_date_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = utils_js_get_date (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


void utils_setup_js_class (void* context) {
	void* c = NULL;
	void* _tmp0_ = NULL;
	void* o = NULL;
	void* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* g = NULL;
	void* _tmp4_ = NULL;
	void* _tmp5_ = NULL;
	void* s = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	g_return_if_fail (context != NULL);
	_tmp0_ = JSClassCreate (&UTILS_js_class);
	c = _tmp0_;
	_tmp1_ = context;
	_tmp2_ = context;
	_tmp3_ = JSObjectMake (_tmp1_, c, _tmp2_);
	o = _tmp3_;
	_tmp4_ = context;
	_tmp5_ = JSContextGetGlobalObject (_tmp4_);
	g = _tmp5_;
	_tmp6_ = JSStringCreateWithUTF8CString ("Utils");
	s = _tmp6_;
	_tmp7_ = context;
	JSObjectSetProperty (_tmp7_, g, s, o, kJSPropertyAttributeNone, NULL);
	_JSStringRelease0 (s);
	_0 (g);
	_0 (o);
	_JSClassRelease0 (c);
}


gchar* utils_get_icon_path (const gchar* name, gint size) {
	gchar* result = NULL;
	GtkIconTheme* icon = NULL;
	GtkIconTheme* _tmp0_ = NULL;
	GtkIconTheme* _tmp1_ = NULL;
	GtkIconInfo* i = NULL;
	GtkIconTheme* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	GtkIconInfo* _tmp5_ = NULL;
	GtkIconInfo* _tmp6_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = gtk_icon_theme_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	icon = _tmp1_;
	_tmp2_ = icon;
	_tmp3_ = name;
	_tmp4_ = size;
	_tmp5_ = gtk_icon_theme_lookup_icon (_tmp2_, _tmp3_, _tmp4_, GTK_ICON_LOOKUP_GENERIC_FALLBACK);
	i = _tmp5_;
	_tmp6_ = i;
	if (_tmp6_ != NULL) {
		GtkIconInfo* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp7_ = i;
		_tmp8_ = gtk_icon_info_get_filename (_tmp7_);
		_tmp9_ = g_strdup (_tmp8_);
		result = _tmp9_;
		_gtk_icon_info_free0 (i);
		_g_object_unref0 (icon);
		return result;
	} else {
		const gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		_tmp10_ = name;
		_tmp11_ = g_strdup (_tmp10_);
		result = _tmp11_;
		_gtk_icon_info_free0 (i);
		_g_object_unref0 (icon);
		return result;
	}
	_gtk_icon_info_free0 (i);
	_g_object_unref0 (icon);
}



