/* xdg-data.c generated by valac 0.26.1, the Vala compiler
 * generated from xdg-data.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <JavaScriptCore/JavaScript.h>
#include <stdio.h>
#include <gnome-menus/gmenu-tree.h>
#include <glib/gi18n-lib.h>
#include <glib/gstdio.h>
#include <gobject/gvaluecollector.h>


#define TYPE_PANEL_XDG_DATA (panel_xdg_data_get_type ())
#define PANEL_XDG_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANEL_XDG_DATA, PanelXdgData))
#define PANEL_XDG_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANEL_XDG_DATA, PanelXdgDataClass))
#define IS_PANEL_XDG_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANEL_XDG_DATA))
#define IS_PANEL_XDG_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANEL_XDG_DATA))
#define PANEL_XDG_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANEL_XDG_DATA, PanelXdgDataClass))

typedef struct _PanelXdgData PanelXdgData;
typedef struct _PanelXdgDataClass PanelXdgDataClass;
typedef struct _PanelXdgDataPrivate PanelXdgDataPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _JSStringRelease0(var) ((var == NULL) ? NULL : (var = (JSStringRelease (var), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _gmenu_tree_item_unref0(var) ((var == NULL) ? NULL : (var = (gmenu_tree_item_unref (var), NULL)))
#define _gmenu_tree_unref0(var) ((var == NULL) ? NULL : (var = (gmenu_tree_unref (var), NULL)))
#define _JSClassRelease0(var) ((var == NULL) ? NULL : (var = (JSClassRelease (var), NULL)))
#define _panel_xdg_data_unref0(var) ((var == NULL) ? NULL : (var = (panel_xdg_data_unref (var), NULL)))
typedef struct _Block8Data Block8Data;
typedef struct _ParamSpecPanelXdgData ParamSpecPanelXdgData;

struct _PanelXdgData {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PanelXdgDataPrivate * priv;
};

struct _PanelXdgDataClass {
	GTypeClass parent_class;
	void (*finalize) (PanelXdgData *self);
};

struct _PanelXdgDataPrivate {
	GFileMonitor* xdg_menu_monitor;
	GFileMonitor* apps_monitor;
	gchar* catalog;
	GString* json;
	gint depth;
	GtkIconTheme* icon;
	void* jsObject;
	guint scheduled;
	guint64 last_schedule;
};

struct _Block8Data {
	int _ref_count_;
	GtkMessageDialog* dialog;
};

struct _ParamSpecPanelXdgData {
	GParamSpec parent_instance;
};


static gpointer panel_xdg_data_parent_class = NULL;
static void* panel_xdg_data_jsContext;
static void* panel_xdg_data_jsContext = NULL;

gpointer panel_xdg_data_ref (gpointer instance);
void panel_xdg_data_unref (gpointer instance);
GParamSpec* param_spec_panel_xdg_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_panel_xdg_data (GValue* value, gpointer v_object);
void value_take_panel_xdg_data (GValue* value, gpointer v_object);
gpointer value_get_panel_xdg_data (const GValue* value);
GType panel_xdg_data_get_type (void) G_GNUC_CONST;
#define PANEL_XDG_DATA_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANEL_XDG_DATA, PanelXdgDataPrivate))
enum  {
	PANEL_XDG_DATA_DUMMY_PROPERTY
};
void* panel_xdg_data_js_put_to_desktop (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_xdg_data_js_put_to_desktop_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void* panel_xdg_data_js_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception);
static void* _panel_xdg_data_js_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception);
PanelXdgData* panel_xdg_data_new (const gchar* catalog);
PanelXdgData* panel_xdg_data_construct (GType object_type, const gchar* catalog);
static void panel_xdg_data_monitor (PanelXdgData* self);
static void __lambda65_ (PanelXdgData* self);
static void panel_xdg_data_schedule_for_kick_js (PanelXdgData* self);
static void ___lambda65__panel_xdg_data_changed (PanelXdgData* _sender, gpointer self);
static gboolean panel_xdg_data_kick_js (PanelXdgData* self);
static gboolean _panel_xdg_data_kick_js_gsource_func (gpointer self);
static void ___lambda63_ (PanelXdgData* self);
static void ____lambda63__g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self);
static void ___lambda64_ (PanelXdgData* self);
static void ____lambda64__g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self);
static void panel_xdg_data_update_tree (PanelXdgData* self, GMenuTreeDirectory* root);
gchar* utils_get_icon_path (const gchar* name, gint size);
static void panel_xdg_data_populate (PanelXdgData* self);
static void panel_xdg_data_put_to_desktop (const gchar* filename);
static void panel_xdg_data_show_dialog (const gchar* message);
void* panel_xdg_data_js_update (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_xdg_data_js_update_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void* panel_xdg_data_js_set_update_callback (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
static void* _panel_xdg_data_js_set_update_callback_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception);
void panel_xdg_data_setup_js_class (void* context);
static Block8Data* block8_data_ref (Block8Data* _data8_);
static void block8_data_unref (void * _userdata_);
static void __lambda62_ (Block8Data* _data8_);
static void ___lambda62__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static void panel_xdg_data_finalize (PanelXdgData* obj);

static const JSStaticFunction PANEL_XDG_DATA_js_funcs[2] = {{"put_to_desktop", _panel_xdg_data_js_put_to_desktop_js_core_object_call_as_function_callback, kJSPropertyAttributeReadOnly}, {NULL, NULL, 0}};
static const JSClassDefinition PANEL_XDG_DATA_js_class = {0, kJSClassAttributeNone, "XdgDataBackEnd", NULL, NULL, PANEL_XDG_DATA_js_funcs, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, _panel_xdg_data_js_constructor_js_core_object_call_as_constructor_callback, NULL, NULL};

static void* _panel_xdg_data_js_put_to_desktop_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_xdg_data_js_put_to_desktop (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _panel_xdg_data_js_constructor_js_core_object_call_as_constructor_callback (void* ctx, void* constructor, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_xdg_data_js_constructor (ctx, constructor, arguments, arguments_length1, exception);
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda65_ (PanelXdgData* self) {
	guint _tmp0_ = 0U;
	_tmp0_ = self->priv->scheduled;
	if (_tmp0_ > ((guint) 0)) {
		return;
	}
	panel_xdg_data_schedule_for_kick_js (self);
}


static void ___lambda65__panel_xdg_data_changed (PanelXdgData* _sender, gpointer self) {
	__lambda65_ ((PanelXdgData*) self);
}


PanelXdgData* panel_xdg_data_construct (GType object_type, const gchar* catalog) {
	PanelXdgData* self = NULL;
	GString* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GtkIconTheme* _tmp3_ = NULL;
	GtkIconTheme* _tmp4_ = NULL;
	g_return_val_if_fail (catalog != NULL, NULL);
	self = (PanelXdgData*) g_type_create_instance (object_type);
	_tmp0_ = g_string_new ("");
	_g_string_free0 (self->priv->json);
	self->priv->json = _tmp0_;
	_tmp1_ = catalog;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (self->priv->catalog);
	self->priv->catalog = _tmp2_;
	_tmp3_ = gtk_icon_theme_get_default ();
	_tmp4_ = _g_object_ref0 (_tmp3_);
	_g_object_unref0 (self->priv->icon);
	self->priv->icon = _tmp4_;
	panel_xdg_data_monitor (self);
	g_signal_connect (self, "changed", (GCallback) ___lambda65__panel_xdg_data_changed, self);
	return self;
}


PanelXdgData* panel_xdg_data_new (const gchar* catalog) {
	return panel_xdg_data_construct (TYPE_PANEL_XDG_DATA, catalog);
}


static gboolean _panel_xdg_data_kick_js_gsource_func (gpointer self) {
	gboolean result;
	result = panel_xdg_data_kick_js ((PanelXdgData*) self);
	return result;
}


static void panel_xdg_data_schedule_for_kick_js (PanelXdgData* self) {
	GDateTime* d = NULL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	gint64 _tmp2_ = 0LL;
	guint64 _tmp3_ = 0ULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_date_time_new_now_local ();
	d = _tmp0_;
	_tmp1_ = d;
	_tmp2_ = g_date_time_to_unix (_tmp1_);
	_tmp3_ = self->priv->last_schedule;
	if ((_tmp2_ - _tmp3_) > ((guint64) 60)) {
		panel_xdg_data_kick_js (self);
	} else {
		guint _tmp4_ = 0U;
		_tmp4_ = self->priv->scheduled;
		if (_tmp4_ == ((guint) 0)) {
			guint _tmp5_ = 0U;
			_tmp5_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 60000, _panel_xdg_data_kick_js_gsource_func, panel_xdg_data_ref (self), panel_xdg_data_unref);
			self->priv->scheduled = _tmp5_;
		}
	}
	_g_date_time_unref0 (d);
}


static gboolean panel_xdg_data_kick_js (PanelXdgData* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	void* _tmp1_ = NULL;
	GDateTime* d = NULL;
	GDateTime* _tmp17_ = NULL;
	gint64 _tmp18_ = 0LL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp1_ = panel_xdg_data_jsContext;
	if (_tmp1_ != NULL) {
		void* _tmp2_ = NULL;
		_tmp2_ = self->priv->jsObject;
		_tmp0_ = _tmp2_ != NULL;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		void* s = NULL;
		void* _tmp3_ = NULL;
		void* v = NULL;
		void* _tmp4_ = NULL;
		void* _tmp5_ = NULL;
		void* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		_tmp3_ = JSStringCreateWithUTF8CString ("updateCallback");
		s = _tmp3_;
		_tmp4_ = self->priv->jsObject;
		_tmp5_ = panel_xdg_data_jsContext;
		_tmp6_ = s;
		_tmp7_ = JSObjectGetProperty (_tmp5_, _tmp4_, _tmp6_, NULL);
		v = _tmp7_;
		_tmp8_ = v;
		if (_tmp8_ != NULL) {
			void* _tmp9_ = NULL;
			void* _tmp10_ = NULL;
			void* _tmp11_ = NULL;
			gchar buffer[1024] = {0};
			void* _tmp12_ = NULL;
			void* _tmp13_ = NULL;
			void* _tmp14_ = NULL;
			void* _tmp15_ = NULL;
			void* _tmp16_ = NULL;
			_tmp9_ = v;
			_tmp10_ = panel_xdg_data_jsContext;
			_tmp11_ = JSValueToStringCopy (_tmp10_, _tmp9_, NULL);
			_JSStringRelease0 (s);
			s = _tmp11_;
			_tmp12_ = s;
			JSStringGetUTF8CString (_tmp12_, buffer, (gsize) 1024);
			_tmp13_ = panel_xdg_data_jsContext;
			_tmp14_ = s;
			_tmp15_ = JSEvaluateScript (_tmp13_, _tmp14_, NULL, NULL, 0, NULL);
			_tmp16_ = _tmp15_;
			_0 (_tmp16_);
			_JSStringRelease0 (s);
			s = NULL;
		}
		_0 (v);
		_JSStringRelease0 (s);
	}
	_tmp17_ = g_date_time_new_now_local ();
	d = _tmp17_;
	_tmp18_ = g_date_time_to_unix (d);
	self->priv->last_schedule = (guint64) _tmp18_;
	self->priv->scheduled = (guint) 0;
	result = FALSE;
	_g_date_time_unref0 (d);
	return result;
}


static void ___lambda63_ (PanelXdgData* self) {
	g_signal_emit_by_name (self, "changed");
}


static void ____lambda63__g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self) {
	___lambda63_ ((PanelXdgData*) self);
}


static void ___lambda64_ (PanelXdgData* self) {
	g_signal_emit_by_name (self, "changed");
}


static void ____lambda64__g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self) {
	___lambda64_ ((PanelXdgData*) self);
}


static void panel_xdg_data_monitor (PanelXdgData* self) {
	GFile* xdg_menu_dir = NULL;
	GFile* _tmp0_ = NULL;
	GFile* apps_dir = NULL;
	GFile* _tmp8_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_file_new_for_path ("/etc/xdg/menus");
	xdg_menu_dir = _tmp0_;
	{
		GFileMonitor* _tmp1_ = NULL;
		GFileMonitor* _tmp2_ = NULL;
		GFileMonitor* _tmp3_ = NULL;
		GFileMonitor* _tmp4_ = NULL;
		_tmp2_ = g_file_monitor (xdg_menu_dir, G_FILE_MONITOR_NONE, NULL, &_inner_error_);
		_tmp1_ = _tmp2_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch18_g_error;
		}
		_tmp3_ = _tmp1_;
		_tmp1_ = NULL;
		_g_object_unref0 (self->priv->xdg_menu_monitor);
		self->priv->xdg_menu_monitor = _tmp3_;
		_tmp4_ = self->priv->xdg_menu_monitor;
		g_signal_connect (_tmp4_, "changed", (GCallback) ____lambda63__g_file_monitor_changed, self);
		_g_object_unref0 (_tmp1_);
	}
	goto __finally18;
	__catch18_g_error:
	{
		GError* e = NULL;
		FILE* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = stdout;
		_tmp6_ = e;
		_tmp7_ = _tmp6_->message;
		fprintf (_tmp5_, "Can't monitor /etc/xdg/menus directory: %s\n", _tmp7_);
		_g_error_free0 (e);
	}
	__finally18:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (xdg_menu_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = g_file_new_for_path ("/usr/share/applications");
	apps_dir = _tmp8_;
	{
		GFileMonitor* _tmp9_ = NULL;
		GFileMonitor* _tmp10_ = NULL;
		GFileMonitor* _tmp11_ = NULL;
		GFileMonitor* _tmp12_ = NULL;
		_tmp10_ = g_file_monitor (apps_dir, G_FILE_MONITOR_NONE, NULL, &_inner_error_);
		_tmp9_ = _tmp10_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch19_g_error;
		}
		_tmp11_ = _tmp9_;
		_tmp9_ = NULL;
		_g_object_unref0 (self->priv->apps_monitor);
		self->priv->apps_monitor = _tmp11_;
		_tmp12_ = self->priv->apps_monitor;
		g_signal_connect (_tmp12_, "changed", (GCallback) ____lambda64__g_file_monitor_changed, self);
		_g_object_unref0 (_tmp9_);
	}
	goto __finally19;
	__catch19_g_error:
	{
		GError* e = NULL;
		FILE* _tmp13_ = NULL;
		GError* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp13_ = stdout;
		_tmp14_ = e;
		_tmp15_ = _tmp14_->message;
		fprintf (_tmp13_, "Can't monitor applications directory: %s\n", _tmp15_);
		_g_error_free0 (e);
	}
	__finally19:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (apps_dir);
		_g_object_unref0 (xdg_menu_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (apps_dir);
	_g_object_unref0 (xdg_menu_dir);
}


static gpointer _gmenu_tree_item_ref0 (gpointer self) {
	return self ? gmenu_tree_item_ref (self) : NULL;
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch20_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = regex;
		_tmp7_ = replacement;
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) (-1), 0, _tmp7_, 0, &_inner_error_);
		_tmp5_ = _tmp8_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch20_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp5_;
		_tmp5_ = NULL;
		result = _tmp9_;
		_g_free0 (_tmp5_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally20;
	__catch20_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally20:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static void panel_xdg_data_update_tree (PanelXdgData* self, GMenuTreeDirectory* root) {
	GMenuTreeDirectory* _tmp0_ = NULL;
	GSList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (root != NULL);
	_tmp0_ = root;
	_tmp1_ = gmenu_tree_directory_get_contents (_tmp0_);
	{
		GSList* item_collection = NULL;
		GSList* item_it = NULL;
		item_collection = _tmp1_;
		for (item_it = item_collection; item_it != NULL; item_it = item_it->next) {
			GMenuTreeItem* _tmp2_ = NULL;
			GMenuTreeItem* item = NULL;
			_tmp2_ = _gmenu_tree_item_ref0 ((GMenuTreeItem*) item_it->data);
			item = _tmp2_;
			{
				GMenuTreeItem* _tmp3_ = NULL;
				GMenuTreeItemType _tmp4_ = 0;
				_tmp3_ = item;
				_tmp4_ = gmenu_tree_item_get_type (_tmp3_);
				switch (_tmp4_) {
					case GMENU_TREE_ITEM_DIRECTORY:
					{
						gint _tmp5_ = 0;
						GMenuTreeDirectory* i = NULL;
						GMenuTreeItem* _tmp6_ = NULL;
						GMenuTreeDirectory* _tmp7_ = NULL;
						gchar* s = NULL;
						GMenuTreeDirectory* _tmp8_ = NULL;
						const gchar* _tmp9_ = NULL;
						gchar* _tmp10_ = NULL;
						gchar* _tmp11_ = NULL;
						gchar* _tmp12_ = NULL;
						gchar* _tmp13_ = NULL;
						gchar* _tmp14_ = NULL;
						gchar* _tmp15_ = NULL;
						gchar* _tmp16_ = NULL;
						gchar* _tmp17_ = NULL;
						GMenuTreeDirectory* _tmp18_ = NULL;
						const gchar* _tmp19_ = NULL;
						gchar* _tmp20_ = NULL;
						gchar* _tmp21_ = NULL;
						GString* _tmp22_ = NULL;
						const gchar* _tmp23_ = NULL;
						GString* _tmp24_ = NULL;
						gint _tmp25_ = 0;
						GMenuTreeDirectory* _tmp26_ = NULL;
						gint _tmp27_ = 0;
						GString* _tmp28_ = NULL;
						const gchar* _tmp29_ = NULL;
						GString* _tmp30_ = NULL;
						gssize _tmp31_ = 0L;
						gchar _tmp32_ = '\0';
						GString* _tmp36_ = NULL;
						GString* _tmp37_ = NULL;
						_tmp5_ = self->priv->depth;
						if (_tmp5_ > 0) {
							break;
						}
						_tmp6_ = item;
						_tmp7_ = _gmenu_tree_item_ref0 ((GMenuTreeDirectory*) _tmp6_);
						i = _tmp7_;
						_tmp8_ = i;
						_tmp9_ = gmenu_tree_directory_get_icon (_tmp8_);
						_tmp10_ = string_replace (_tmp9_, ".svg", "");
						_tmp11_ = _tmp10_;
						_tmp12_ = string_replace (_tmp11_, ".png", "");
						_tmp13_ = _tmp12_;
						_tmp14_ = string_replace (_tmp13_, ".xpm", "");
						_tmp15_ = _tmp14_;
						_tmp16_ = utils_get_icon_path (_tmp15_, 24);
						_tmp17_ = _tmp16_;
						_tmp18_ = i;
						_tmp19_ = gmenu_tree_directory_get_name (_tmp18_);
						_tmp20_ = g_strdup_printf ("{icon: '%s', name: '%s',", _tmp17_, _tmp19_);
						_tmp21_ = _tmp20_;
						_g_free0 (_tmp17_);
						_g_free0 (_tmp15_);
						_g_free0 (_tmp13_);
						_g_free0 (_tmp11_);
						s = _tmp21_;
						_tmp22_ = self->priv->json;
						_tmp23_ = s;
						g_string_append (_tmp22_, _tmp23_);
						_tmp24_ = self->priv->json;
						g_string_append (_tmp24_, "children:[");
						_tmp25_ = self->priv->depth;
						self->priv->depth = _tmp25_ + 1;
						_tmp26_ = i;
						panel_xdg_data_update_tree (self, _tmp26_);
						_tmp27_ = self->priv->depth;
						self->priv->depth = _tmp27_ - 1;
						_tmp28_ = self->priv->json;
						_tmp29_ = _tmp28_->str;
						_tmp30_ = self->priv->json;
						_tmp31_ = _tmp30_->len;
						_tmp32_ = string_get (_tmp29_, (glong) (_tmp31_ - 1));
						if (_tmp32_ == ',') {
							GString* _tmp33_ = NULL;
							GString* _tmp34_ = NULL;
							gssize _tmp35_ = 0L;
							_tmp33_ = self->priv->json;
							_tmp34_ = self->priv->json;
							_tmp35_ = _tmp34_->len;
							g_string_erase (_tmp33_, _tmp35_ - 1, (gssize) 1);
						}
						_tmp36_ = self->priv->json;
						g_string_append (_tmp36_, "]");
						_tmp37_ = self->priv->json;
						g_string_append (_tmp37_, "},");
						_g_free0 (s);
						_gmenu_tree_item_unref0 (i);
						break;
					}
					case GMENU_TREE_ITEM_ENTRY:
					{
						GMenuTreeEntry* i = NULL;
						GMenuTreeItem* _tmp38_ = NULL;
						GMenuTreeEntry* _tmp39_ = NULL;
						gchar* s = NULL;
						GMenuTreeEntry* _tmp40_ = NULL;
						const gchar* _tmp41_ = NULL;
						gchar* _tmp42_ = NULL;
						gchar* _tmp43_ = NULL;
						gchar* _tmp44_ = NULL;
						gchar* _tmp45_ = NULL;
						gchar* _tmp46_ = NULL;
						gchar* _tmp47_ = NULL;
						gchar* _tmp48_ = NULL;
						gchar* _tmp49_ = NULL;
						GMenuTreeEntry* _tmp50_ = NULL;
						const gchar* _tmp51_ = NULL;
						GMenuTreeEntry* _tmp52_ = NULL;
						const gchar* _tmp53_ = NULL;
						gchar* _tmp54_ = NULL;
						gchar* _tmp55_ = NULL;
						GString* _tmp56_ = NULL;
						const gchar* _tmp57_ = NULL;
						_tmp38_ = item;
						_tmp39_ = _gmenu_tree_item_ref0 ((GMenuTreeEntry*) _tmp38_);
						i = _tmp39_;
						_tmp40_ = i;
						_tmp41_ = gmenu_tree_entry_get_icon (_tmp40_);
						_tmp42_ = string_replace (_tmp41_, ".svg", "");
						_tmp43_ = _tmp42_;
						_tmp44_ = string_replace (_tmp43_, ".png", "");
						_tmp45_ = _tmp44_;
						_tmp46_ = string_replace (_tmp45_, ".xpm", "");
						_tmp47_ = _tmp46_;
						_tmp48_ = utils_get_icon_path (_tmp47_, 24);
						_tmp49_ = _tmp48_;
						_tmp50_ = i;
						_tmp51_ = gmenu_tree_entry_get_display_name (_tmp50_);
						_tmp52_ = i;
						_tmp53_ = gmenu_tree_entry_get_desktop_file_path (_tmp52_);
						_tmp54_ = g_strdup_printf ("{icon: '%s', name: '%s', desktop: '%s'},", _tmp49_, _tmp51_, _tmp53_);
						_tmp55_ = _tmp54_;
						_g_free0 (_tmp49_);
						_g_free0 (_tmp47_);
						_g_free0 (_tmp45_);
						_g_free0 (_tmp43_);
						s = _tmp55_;
						_tmp56_ = self->priv->json;
						_tmp57_ = s;
						g_string_append (_tmp56_, _tmp57_);
						_g_free0 (s);
						_gmenu_tree_item_unref0 (i);
						break;
					}
					default:
					break;
				}
				_gmenu_tree_item_unref0 (item);
			}
		}
	}
}


static gpointer _gmenu_tree_ref0 (gpointer self) {
	return self ? gmenu_tree_ref (self) : NULL;
}


static void panel_xdg_data_populate (PanelXdgData* self) {
	GMenuTree* tree = NULL;
	const gchar* _tmp0_ = NULL;
	GMenuTree* _tmp1_ = NULL;
	GMenuTree* _tmp2_ = NULL;
	GMenuTreeDirectory* root = NULL;
	GMenuTree* _tmp3_ = NULL;
	GMenuTreeDirectory* _tmp4_ = NULL;
	GMenuTreeDirectory* _tmp5_ = NULL;
	GString* _tmp6_ = NULL;
	GMenuTreeDirectory* _tmp7_ = NULL;
	GString* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	GString* _tmp10_ = NULL;
	gssize _tmp11_ = 0L;
	gchar _tmp12_ = '\0';
	GString* _tmp16_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->catalog;
	_tmp1_ = gmenu_tree_lookup (_tmp0_, GMENU_TREE_FLAGS_NONE);
	_tmp2_ = _gmenu_tree_ref0 (_tmp1_);
	tree = _tmp2_;
	_tmp3_ = tree;
	_tmp4_ = gmenu_tree_get_root_directory (_tmp3_);
	_tmp5_ = _gmenu_tree_item_ref0 (_tmp4_);
	root = _tmp5_;
	_tmp6_ = self->priv->json;
	g_string_assign (_tmp6_, "[");
	_tmp7_ = root;
	panel_xdg_data_update_tree (self, _tmp7_);
	_tmp8_ = self->priv->json;
	_tmp9_ = _tmp8_->str;
	_tmp10_ = self->priv->json;
	_tmp11_ = _tmp10_->len;
	_tmp12_ = string_get (_tmp9_, (glong) (_tmp11_ - 1));
	if (_tmp12_ == ',') {
		GString* _tmp13_ = NULL;
		GString* _tmp14_ = NULL;
		gssize _tmp15_ = 0L;
		_tmp13_ = self->priv->json;
		_tmp14_ = self->priv->json;
		_tmp15_ = _tmp14_->len;
		g_string_erase (_tmp13_, _tmp15_ - 1, (gssize) 1);
	}
	_tmp16_ = self->priv->json;
	g_string_append (_tmp16_, "]");
	_gmenu_tree_item_unref0 (root);
	_gmenu_tree_unref0 (tree);
}


static void panel_xdg_data_put_to_desktop (const gchar* filename) {
	GFile* input_file = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	gchar* path = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	GFile* file = NULL;
	const gchar* _tmp10_ = NULL;
	GFile* _tmp11_ = NULL;
	GFile* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
	GDataInputStream* input = NULL;
	GDataOutputStream* output = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (filename != NULL);
	_tmp0_ = filename;
	_tmp1_ = g_file_new_for_path (_tmp0_);
	input_file = _tmp1_;
	_tmp2_ = g_get_user_special_dir (G_USER_DIRECTORY_DESKTOP);
	_tmp3_ = g_strconcat (_tmp2_, "/", NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = input_file;
	_tmp6_ = g_file_get_basename (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat (_tmp4_, _tmp7_, NULL);
	_tmp9_ = _tmp8_;
	_g_free0 (_tmp7_);
	_g_free0 (_tmp4_);
	path = _tmp9_;
	_tmp10_ = path;
	_tmp11_ = g_file_new_for_path (_tmp10_);
	file = _tmp11_;
	_tmp12_ = file;
	_tmp13_ = g_file_query_exists (_tmp12_, NULL);
	if (_tmp13_) {
		const gchar* _tmp14_ = NULL;
		GFile* _tmp15_ = NULL;
		gchar* _tmp16_ = NULL;
		gchar* _tmp17_ = NULL;
		const gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		_tmp14_ = _ ("Shortcut %s already exists in %s");
		_tmp15_ = input_file;
		_tmp16_ = g_file_get_basename (_tmp15_);
		_tmp17_ = _tmp16_;
		_tmp18_ = path;
		_tmp19_ = g_strdup_printf (_tmp14_, _tmp17_, _tmp18_);
		_tmp20_ = _tmp19_;
		panel_xdg_data_show_dialog (_tmp20_);
		_g_free0 (_tmp20_);
		_g_free0 (_tmp17_);
		_g_object_unref0 (file);
		_g_free0 (path);
		_g_object_unref0 (input_file);
		return;
	}
	output = NULL;
	{
		GFileInputStream* _tmp21_ = NULL;
		GFile* _tmp22_ = NULL;
		GFileInputStream* _tmp23_ = NULL;
		GDataInputStream* _tmp24_ = NULL;
		_tmp22_ = input_file;
		_tmp23_ = g_file_read (_tmp22_, NULL, &_inner_error_);
		_tmp21_ = _tmp23_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch21_g_error;
		}
		_tmp24_ = g_data_input_stream_new ((GInputStream*) _tmp21_);
		_g_object_unref0 (input);
		input = _tmp24_;
		_g_object_unref0 (_tmp21_);
	}
	goto __finally21;
	__catch21_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp25_ = NULL;
		const gchar* _tmp26_ = NULL;
		GError* _tmp27_ = NULL;
		const gchar* _tmp28_ = NULL;
		gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp25_ = _ ("Unable to read %s: %s");
		_tmp26_ = filename;
		_tmp27_ = e;
		_tmp28_ = _tmp27_->message;
		_tmp29_ = g_strdup_printf (_tmp25_, _tmp26_, _tmp28_);
		_tmp30_ = _tmp29_;
		panel_xdg_data_show_dialog (_tmp30_);
		_g_free0 (_tmp30_);
		_g_error_free0 (e);
		_g_object_unref0 (output);
		_g_object_unref0 (input);
		_g_object_unref0 (file);
		_g_free0 (path);
		_g_object_unref0 (input_file);
		return;
	}
	__finally21:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (output);
		_g_object_unref0 (input);
		_g_object_unref0 (file);
		_g_free0 (path);
		_g_object_unref0 (input_file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	{
		GFileOutputStream* _tmp31_ = NULL;
		GFile* _tmp32_ = NULL;
		GFileOutputStream* _tmp33_ = NULL;
		GDataOutputStream* _tmp34_ = NULL;
		_tmp32_ = file;
		_tmp33_ = g_file_create (_tmp32_, G_FILE_CREATE_PRIVATE, NULL, &_inner_error_);
		_tmp31_ = _tmp33_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch22_g_error;
		}
		_tmp34_ = g_data_output_stream_new ((GOutputStream*) _tmp31_);
		_g_object_unref0 (output);
		output = _tmp34_;
		_g_object_unref0 (_tmp31_);
	}
	goto __finally22;
	__catch22_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp35_ = NULL;
		GFile* _tmp36_ = NULL;
		gchar* _tmp37_ = NULL;
		gchar* _tmp38_ = NULL;
		const gchar* _tmp39_ = NULL;
		GError* _tmp40_ = NULL;
		const gchar* _tmp41_ = NULL;
		gchar* _tmp42_ = NULL;
		gchar* _tmp43_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp35_ = _ ("Unable to create %s shortcut in %s: %s");
		_tmp36_ = input_file;
		_tmp37_ = g_file_get_basename (_tmp36_);
		_tmp38_ = _tmp37_;
		_tmp39_ = path;
		_tmp40_ = e;
		_tmp41_ = _tmp40_->message;
		_tmp42_ = g_strdup_printf (_tmp35_, _tmp38_, _tmp39_, _tmp41_);
		_tmp43_ = _tmp42_;
		panel_xdg_data_show_dialog (_tmp43_);
		_g_free0 (_tmp43_);
		_g_free0 (_tmp38_);
		{
			GDataInputStream* _tmp44_ = NULL;
			_tmp44_ = input;
			g_input_stream_close ((GInputStream*) _tmp44_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch23_g_error;
			}
		}
		goto __finally23;
		__catch23_g_error:
		{
			GError* e = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_g_error_free0 (e);
		}
		__finally23:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_error_free0 (e);
			_g_error_free0 (e);
			{
			}
			_g_object_unref0 (output);
			_g_object_unref0 (input);
			_g_object_unref0 (file);
			_g_free0 (path);
			_g_object_unref0 (input_file);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_g_error_free0 (e);
		{
		}
		_g_object_unref0 (output);
		_g_object_unref0 (input);
		_g_object_unref0 (file);
		_g_free0 (path);
		_g_object_unref0 (input_file);
		return;
	}
	__finally22:
	{
	}
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (output);
		_g_object_unref0 (input);
		_g_object_unref0 (file);
		_g_free0 (path);
		_g_object_unref0 (input_file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	{
		GDataOutputStream* _tmp45_ = NULL;
		gchar* line = NULL;
		GDataOutputStream* _tmp55_ = NULL;
		GDataInputStream* _tmp56_ = NULL;
		const gchar* _tmp57_ = NULL;
		_tmp45_ = output;
		g_data_output_stream_put_string (_tmp45_, "#!/usr/bin/env xdg-open\n\n", NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch24_g_error;
		}
		while (TRUE) {
			gchar* _tmp46_ = NULL;
			GDataInputStream* _tmp47_ = NULL;
			gchar* _tmp48_ = NULL;
			gchar* _tmp49_ = NULL;
			const gchar* _tmp50_ = NULL;
			GDataOutputStream* _tmp51_ = NULL;
			const gchar* _tmp52_ = NULL;
			gchar* _tmp53_ = NULL;
			gchar* _tmp54_ = NULL;
			_tmp47_ = input;
			_tmp48_ = g_data_input_stream_read_line (_tmp47_, NULL, NULL, &_inner_error_);
			_tmp46_ = _tmp48_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_free0 (line);
				goto __catch24_g_error;
			}
			_tmp49_ = _tmp46_;
			_tmp46_ = NULL;
			_g_free0 (line);
			line = _tmp49_;
			_tmp50_ = line;
			if (!(_tmp50_ != NULL)) {
				_g_free0 (_tmp46_);
				break;
			}
			_tmp51_ = output;
			_tmp52_ = line;
			_tmp53_ = g_strconcat (_tmp52_, "\n", NULL);
			_tmp54_ = _tmp53_;
			g_data_output_stream_put_string (_tmp51_, _tmp54_, NULL, &_inner_error_);
			_g_free0 (_tmp54_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_free0 (_tmp46_);
				_g_free0 (line);
				goto __catch24_g_error;
			}
			_g_free0 (_tmp46_);
		}
		_tmp55_ = output;
		g_output_stream_close ((GOutputStream*) _tmp55_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_free0 (line);
			goto __catch24_g_error;
		}
		_tmp56_ = input;
		g_input_stream_close ((GInputStream*) _tmp56_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_free0 (line);
			goto __catch24_g_error;
		}
		_tmp57_ = path;
		g_chmod (_tmp57_, 0700);
		_g_free0 (line);
	}
	goto __finally24;
	__catch24_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp58_ = NULL;
		GFile* _tmp59_ = NULL;
		gchar* _tmp60_ = NULL;
		gchar* _tmp61_ = NULL;
		const gchar* _tmp62_ = NULL;
		GError* _tmp63_ = NULL;
		const gchar* _tmp64_ = NULL;
		gchar* _tmp65_ = NULL;
		gchar* _tmp66_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp58_ = _ ("Unable to write %s shortcut in %s: %s");
		_tmp59_ = input_file;
		_tmp60_ = g_file_get_basename (_tmp59_);
		_tmp61_ = _tmp60_;
		_tmp62_ = path;
		_tmp63_ = e;
		_tmp64_ = _tmp63_->message;
		_tmp65_ = g_strdup_printf (_tmp58_, _tmp61_, _tmp62_, _tmp64_);
		_tmp66_ = _tmp65_;
		panel_xdg_data_show_dialog (_tmp66_);
		_g_free0 (_tmp66_);
		_g_free0 (_tmp61_);
		{
			GDataInputStream* _tmp67_ = NULL;
			GDataOutputStream* _tmp68_ = NULL;
			_tmp67_ = input;
			g_input_stream_close ((GInputStream*) _tmp67_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch25_g_error;
			}
			_tmp68_ = output;
			g_output_stream_close ((GOutputStream*) _tmp68_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch25_g_error;
			}
		}
		goto __finally25;
		__catch25_g_error:
		{
			GError* e = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_g_error_free0 (e);
		}
		__finally25:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_error_free0 (e);
			_g_error_free0 (e);
			_g_object_unref0 (output);
			_g_object_unref0 (input);
			_g_object_unref0 (file);
			_g_free0 (path);
			_g_object_unref0 (input_file);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_g_error_free0 (e);
		_g_object_unref0 (output);
		_g_object_unref0 (input);
		_g_object_unref0 (file);
		_g_free0 (path);
		_g_object_unref0 (input_file);
		return;
	}
	__finally24:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (output);
		_g_object_unref0 (input);
		_g_object_unref0 (file);
		_g_free0 (path);
		_g_object_unref0 (input_file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (output);
	_g_object_unref0 (input);
	_g_object_unref0 (file);
	_g_free0 (path);
	_g_object_unref0 (input_file);
}


static void* _panel_xdg_data_js_update_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_xdg_data_js_update (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


static void* _panel_xdg_data_js_set_update_callback_js_core_object_call_as_function_callback (void* ctx, void* function, void* thisObject, size_t arguments_length1, void** arguments, void** exception) {
	void* result;
	result = panel_xdg_data_js_set_update_callback (ctx, function, thisObject, arguments, arguments_length1, exception);
	return result;
}


void* panel_xdg_data_js_constructor (void* ctx, void* constructor, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void* c = NULL;
	void* _tmp0_ = NULL;
	void* o = NULL;
	void* _tmp1_ = NULL;
	void* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* s = NULL;
	void* _tmp4_ = NULL;
	void* f = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	void* _tmp8_ = NULL;
	void* _tmp9_ = NULL;
	void* _tmp10_ = NULL;
	void* _tmp11_ = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	void* _tmp16_ = NULL;
	void* _tmp17_ = NULL;
	void* _tmp18_ = NULL;
	void* _tmp19_ = NULL;
	void** _tmp20_ = NULL;
	gint _tmp20__length1 = 0;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (constructor != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = JSClassCreate (&PANEL_XDG_DATA_js_class);
	c = _tmp0_;
	_tmp1_ = ctx;
	_tmp2_ = c;
	_tmp3_ = JSObjectMake (_tmp1_, _tmp2_, NULL);
	o = _tmp3_;
	_tmp4_ = JSStringCreateWithUTF8CString ("update");
	s = _tmp4_;
	_tmp5_ = ctx;
	_tmp6_ = s;
	_tmp7_ = JSObjectMakeFunctionWithCallback (_tmp5_, _tmp6_, _panel_xdg_data_js_update_js_core_object_call_as_function_callback);
	f = _tmp7_;
	_tmp8_ = o;
	_tmp9_ = ctx;
	_tmp10_ = s;
	_tmp11_ = f;
	JSObjectSetProperty (_tmp9_, _tmp8_, _tmp10_, _tmp11_, 0, NULL);
	_tmp12_ = JSStringCreateWithUTF8CString ("updateCallback");
	_JSStringRelease0 (s);
	s = _tmp12_;
	_tmp13_ = ctx;
	_tmp14_ = s;
	_tmp15_ = JSObjectMakeFunctionWithCallback (_tmp13_, _tmp14_, _panel_xdg_data_js_set_update_callback_js_core_object_call_as_function_callback);
	_0 (f);
	f = _tmp15_;
	_tmp16_ = o;
	_tmp17_ = ctx;
	_tmp18_ = s;
	_tmp19_ = f;
	JSObjectSetProperty (_tmp17_, _tmp16_, _tmp18_, _tmp19_, 0, NULL);
	_tmp20_ = arguments;
	_tmp20__length1 = arguments_length1;
	if (_tmp20__length1 == 1) {
		void** _tmp21_ = NULL;
		gint _tmp21__length1 = 0;
		void* _tmp22_ = NULL;
		void* _tmp23_ = NULL;
		void* _tmp24_ = NULL;
		gchar buffer[1024] = {0};
		void* _tmp25_ = NULL;
		PanelXdgData* i = NULL;
		PanelXdgData* _tmp26_ = NULL;
		void* _tmp27_ = NULL;
		PanelXdgData* _tmp28_ = NULL;
		PanelXdgData* _tmp29_ = NULL;
		void* _tmp30_ = NULL;
		_tmp21_ = arguments;
		_tmp21__length1 = arguments_length1;
		_tmp22_ = _tmp21_[0];
		_tmp23_ = ctx;
		_tmp24_ = JSValueToStringCopy (_tmp23_, _tmp22_, NULL);
		_JSStringRelease0 (s);
		s = _tmp24_;
		_tmp25_ = s;
		JSStringGetUTF8CString (_tmp25_, buffer, (gsize) 1024);
		_tmp26_ = panel_xdg_data_new ((const gchar*) buffer);
		i = _tmp26_;
		_tmp27_ = o;
		_tmp28_ = i;
		JSObjectSetPrivate (_tmp27_, _tmp28_);
		_tmp29_ = i;
		_tmp30_ = o;
		_tmp29_->priv->jsObject = _tmp30_;
	}
	result = o;
	_0 (f);
	_JSStringRelease0 (s);
	_JSClassRelease0 (c);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


static gpointer _panel_xdg_data_ref0 (gpointer self) {
	return self ? panel_xdg_data_ref (self) : NULL;
}


void* panel_xdg_data_js_set_update_callback (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelXdgData* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelXdgData* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	PanelXdgData* _tmp4_ = NULL;
	void* _tmp12_ = NULL;
	void* _tmp13_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_xdg_data_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_XDG_DATA) ? ((PanelXdgData*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp4_ = i;
	if (_tmp4_ != NULL) {
		void** _tmp5_ = NULL;
		gint _tmp5__length1 = 0;
		_tmp5_ = arguments;
		_tmp5__length1 = arguments_length1;
		_tmp3_ = _tmp5__length1 == 1;
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		void* s = NULL;
		void* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		void* _tmp9_ = NULL;
		void** _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		void* _tmp11_ = NULL;
		_tmp6_ = JSStringCreateWithUTF8CString ("updateCallback");
		s = _tmp6_;
		_tmp7_ = thisObject;
		_tmp8_ = ctx;
		_tmp9_ = s;
		_tmp10_ = arguments;
		_tmp10__length1 = arguments_length1;
		_tmp11_ = _tmp10_[0];
		JSObjectSetProperty (_tmp8_, _tmp7_, _tmp9_, _tmp11_, 0, NULL);
		_JSStringRelease0 (s);
	}
	_tmp12_ = ctx;
	_tmp13_ = JSValueMakeUndefined (_tmp12_);
	result = _tmp13_;
	_panel_xdg_data_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* panel_xdg_data_js_update (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	PanelXdgData* i = NULL;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	PanelXdgData* _tmp2_ = NULL;
	PanelXdgData* _tmp3_ = NULL;
	void* _tmp14_ = NULL;
	void* _tmp15_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = thisObject;
	_tmp1_ = JSObjectGetPrivate (_tmp0_);
	_tmp2_ = _panel_xdg_data_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, TYPE_PANEL_XDG_DATA) ? ((PanelXdgData*) _tmp1_) : NULL);
	i = _tmp2_;
	_tmp3_ = i;
	if (_tmp3_ != NULL) {
		PanelXdgData* _tmp4_ = NULL;
		void* s = NULL;
		PanelXdgData* _tmp5_ = NULL;
		GString* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		void* _tmp8_ = NULL;
		void* r = NULL;
		void* _tmp9_ = NULL;
		void* _tmp10_ = NULL;
		void* _tmp11_ = NULL;
		PanelXdgData* _tmp12_ = NULL;
		GString* _tmp13_ = NULL;
		_tmp4_ = i;
		panel_xdg_data_populate (_tmp4_);
		_tmp5_ = i;
		_tmp6_ = _tmp5_->priv->json;
		_tmp7_ = _tmp6_->str;
		_tmp8_ = JSStringCreateWithUTF8CString (_tmp7_);
		s = _tmp8_;
		_tmp9_ = ctx;
		_tmp10_ = s;
		_tmp11_ = JSEvaluateScript (_tmp9_, _tmp10_, NULL, NULL, 0, NULL);
		r = _tmp11_;
		_JSStringRelease0 (s);
		s = NULL;
		_tmp12_ = i;
		_tmp13_ = _tmp12_->priv->json;
		g_string_assign (_tmp13_, "");
		result = r;
		_JSStringRelease0 (s);
		_panel_xdg_data_unref0 (i);
		if (exception) {
			*exception = _vala_exception;
		} else {
			_0 (_vala_exception);
		}
		return result;
	}
	_tmp14_ = ctx;
	_tmp15_ = JSValueMakeUndefined (_tmp14_);
	result = _tmp15_;
	_panel_xdg_data_unref0 (i);
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void* panel_xdg_data_js_put_to_desktop (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception) {
	void* _vala_exception = NULL;
	void* result = NULL;
	void** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	g_return_val_if_fail (ctx != NULL, NULL);
	g_return_val_if_fail (function != NULL, NULL);
	g_return_val_if_fail (thisObject != NULL, NULL);
	_0 (_vala_exception);
	_vala_exception = NULL;
	_tmp0_ = arguments;
	_tmp0__length1 = arguments_length1;
	if (_tmp0__length1 == 1) {
		void* s = NULL;
		void** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		void* _tmp2_ = NULL;
		void* _tmp3_ = NULL;
		void* _tmp4_ = NULL;
		gchar buffer[1024] = {0};
		void* _tmp5_ = NULL;
		_tmp1_ = arguments;
		_tmp1__length1 = arguments_length1;
		_tmp2_ = _tmp1_[0];
		_tmp3_ = ctx;
		_tmp4_ = JSValueToStringCopy (_tmp3_, _tmp2_, NULL);
		s = _tmp4_;
		_tmp5_ = s;
		JSStringGetUTF8CString (_tmp5_, buffer, (gsize) 1024);
		panel_xdg_data_put_to_desktop ((const gchar*) buffer);
		_JSStringRelease0 (s);
	}
	_tmp6_ = ctx;
	_tmp7_ = JSValueMakeUndefined (_tmp6_);
	result = _tmp7_;
	if (exception) {
		*exception = _vala_exception;
	} else {
		_0 (_vala_exception);
	}
	return result;
}


void panel_xdg_data_setup_js_class (void* context) {
	void* _tmp0_ = NULL;
	void* c = NULL;
	void* _tmp1_ = NULL;
	void* o = NULL;
	void* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	void* _tmp4_ = NULL;
	void* g = NULL;
	void* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* s = NULL;
	void* _tmp7_ = NULL;
	void* _tmp8_ = NULL;
	g_return_if_fail (context != NULL);
	_tmp0_ = context;
	panel_xdg_data_jsContext = _tmp0_;
	_tmp1_ = JSClassCreate (&PANEL_XDG_DATA_js_class);
	c = _tmp1_;
	_tmp2_ = context;
	_tmp3_ = context;
	_tmp4_ = JSObjectMake (_tmp2_, c, _tmp3_);
	o = _tmp4_;
	_tmp5_ = context;
	_tmp6_ = JSContextGetGlobalObject (_tmp5_);
	g = _tmp6_;
	_tmp7_ = JSStringCreateWithUTF8CString ("XdgDataBackEnd");
	s = _tmp7_;
	_tmp8_ = context;
	JSObjectSetProperty (_tmp8_, g, s, o, kJSPropertyAttributeNone, NULL);
	_JSStringRelease0 (s);
	_0 (g);
	_0 (o);
	_JSClassRelease0 (c);
}


static Block8Data* block8_data_ref (Block8Data* _data8_) {
	g_atomic_int_inc (&_data8_->_ref_count_);
	return _data8_;
}


static void block8_data_unref (void * _userdata_) {
	Block8Data* _data8_;
	_data8_ = (Block8Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data8_->_ref_count_)) {
		_g_object_unref0 (_data8_->dialog);
		g_slice_free (Block8Data, _data8_);
	}
}


static void __lambda62_ (Block8Data* _data8_) {
	gtk_widget_destroy ((GtkWidget*) _data8_->dialog);
}


static void ___lambda62__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	__lambda62_ (self);
}


static void panel_xdg_data_show_dialog (const gchar* message) {
	Block8Data* _data8_;
	const gchar* _tmp0_ = NULL;
	GtkMessageDialog* _tmp1_ = NULL;
	g_return_if_fail (message != NULL);
	_data8_ = g_slice_new0 (Block8Data);
	_data8_->_ref_count_ = 1;
	_tmp0_ = message;
	_tmp1_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_DESTROY_WITH_PARENT, GTK_MESSAGE_ERROR, GTK_BUTTONS_CLOSE, "%s", _tmp0_);
	g_object_ref_sink (_tmp1_);
	_data8_->dialog = _tmp1_;
	g_signal_connect_data ((GtkDialog*) _data8_->dialog, "response", (GCallback) ___lambda62__gtk_dialog_response, block8_data_ref (_data8_), (GClosureNotify) block8_data_unref, 0);
	gtk_widget_show ((GtkWidget*) _data8_->dialog);
	block8_data_unref (_data8_);
	_data8_ = NULL;
}


static void value_panel_xdg_data_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_panel_xdg_data_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		panel_xdg_data_unref (value->data[0].v_pointer);
	}
}


static void value_panel_xdg_data_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = panel_xdg_data_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_panel_xdg_data_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_panel_xdg_data_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		PanelXdgData* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = panel_xdg_data_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_panel_xdg_data_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PanelXdgData** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = panel_xdg_data_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_panel_xdg_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecPanelXdgData* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_PANEL_XDG_DATA), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_panel_xdg_data (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_XDG_DATA), NULL);
	return value->data[0].v_pointer;
}


void value_set_panel_xdg_data (GValue* value, gpointer v_object) {
	PanelXdgData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_XDG_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PANEL_XDG_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		panel_xdg_data_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		panel_xdg_data_unref (old);
	}
}


void value_take_panel_xdg_data (GValue* value, gpointer v_object) {
	PanelXdgData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PANEL_XDG_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PANEL_XDG_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		panel_xdg_data_unref (old);
	}
}


static void panel_xdg_data_class_init (PanelXdgDataClass * klass) {
	panel_xdg_data_parent_class = g_type_class_peek_parent (klass);
	((PanelXdgDataClass *) klass)->finalize = panel_xdg_data_finalize;
	g_type_class_add_private (klass, sizeof (PanelXdgDataPrivate));
	g_signal_new ("changed", TYPE_PANEL_XDG_DATA, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void panel_xdg_data_instance_init (PanelXdgData * self) {
	self->priv = PANEL_XDG_DATA_GET_PRIVATE (self);
	self->priv->xdg_menu_monitor = NULL;
	self->priv->apps_monitor = NULL;
	self->priv->depth = 0;
	self->priv->scheduled = (guint) 0;
	self->priv->last_schedule = (guint64) 0;
	self->ref_count = 1;
}


static void panel_xdg_data_finalize (PanelXdgData* obj) {
	PanelXdgData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PANEL_XDG_DATA, PanelXdgData);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->xdg_menu_monitor);
	_g_object_unref0 (self->priv->apps_monitor);
	_g_free0 (self->priv->catalog);
	_g_string_free0 (self->priv->json);
	_g_object_unref0 (self->priv->icon);
}


GType panel_xdg_data_get_type (void) {
	static volatile gsize panel_xdg_data_type_id__volatile = 0;
	if (g_once_init_enter (&panel_xdg_data_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_panel_xdg_data_init, value_panel_xdg_data_free_value, value_panel_xdg_data_copy_value, value_panel_xdg_data_peek_pointer, "p", value_panel_xdg_data_collect_value, "p", value_panel_xdg_data_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PanelXdgDataClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panel_xdg_data_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PanelXdgData), 0, (GInstanceInitFunc) panel_xdg_data_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType panel_xdg_data_type_id;
		panel_xdg_data_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PanelXdgData", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&panel_xdg_data_type_id__volatile, panel_xdg_data_type_id);
	}
	return panel_xdg_data_type_id__volatile;
}


gpointer panel_xdg_data_ref (gpointer instance) {
	PanelXdgData* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void panel_xdg_data_unref (gpointer instance) {
	PanelXdgData* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PANEL_XDG_DATA_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



